//! Renders an [`Api`](iohr_openapi::Api) as a generated SDK **surface**: the models and
//! the thin operation methods for the operations a set of profiles may call, on top of
//! the language's hand-written runtime (platform RFC 0020, ADR 0011).
//!
//! One [`Target`] per language. The Rust target is here; the others follow it. Output
//! is deterministic: the same model and options give byte-identical files, so a
//! regenerated surface diffs cleanly and `iohr sdk check` can compare files.
//!
//! This crate is part of the `iohr` command line and is not published on its own; its
//! API may change in any release.

#![forbid(unsafe_code)]

mod files;
pub mod rust;
mod target;

pub use files::Files;
pub use rust::{RustOptions, RustTarget};
pub use target::{RenderError, Target};

/// The line every generated file starts with, naming the cuts it was made from.
#[must_use]
pub fn header(api: &iohr_openapi::Api) -> String {
    let cuts: Vec<String> = api
        .profiles
        .iter()
        .map(|(name, cut)| format!("{name}={}", cut.hash))
        .collect();
    format!(
        "Generated by iohr sdk generate for cuts {}; do not edit.",
        cuts.join(", ")
    )
}
