// Code generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; DO NOT EDIT.

// Package acmeci is the InOrbit API surface for profile acme-ci: only the operations its cut holds, so a call it may not make does not build. FromEnv reads INORBIT_ACME_CI_TOKEN, or INORBIT_ACME_CI_KEY_ID, INORBIT_ACME_CI_KEY_SECRET and INORBIT_ACME_CI_SCOPES, and nothing else.
package acmeci

import (
	"context"
	"iter"

	"example.com/app/iohr/internal/ops"
	"example.com/app/iohr/models"
	inorbit "github.com/inorbithr/sdk/go"
	"github.com/inorbithr/sdk/go/codegen"
)

// The surface was generated for the runtime's contract 4: a runtime with another contract fails to build here, so run iohr sdk generate again.
const _ = codegen.V4

// Profile is the profile's name.
const Profile = "acme-ci"

// Client calls the operations profile acme-ci may call.
type Client struct {
	c *inorbit.Client
}

// New returns the profile's surface on c, a client built for its credential.
func New(c *inorbit.Client) *Client {
	return &Client{c: c}
}

// FromEnv returns the profile's surface with its credential from the environment; opts apply after it.
func FromEnv(opts ...inorbit.Option) (*Client, error) {
	c, err := inorbit.FromEnv("ACME_CI", opts...)
	if err != nil {
		return nil, err
	}
	return New(c), nil
}

// Load returns the profile's surface configured from code, INORBIT_ACME_CI_* (then INORBIT_* for settings), [profiles.acme-ci] and the iohr login (inorbit.Load).
func Load(ctx context.Context, opts ...inorbit.Option) (*Client, error) {
	c, err := inorbit.Load(ctx, append([]inorbit.Option{inorbit.WithProfileType("acme-ci")}, opts...)...)
	if err != nil {
		return nil, err
	}
	return New(c), nil
}

// Runtime returns the client underneath, for a raw call with Send.
func (p *Client) Runtime() *inorbit.Client {
	return p.c
}

// Me calls GET /v1/me; needs scope identity:read. A key needs scope `identity:read`.
func (p *Client) Me(ctx context.Context) (*inorbit.Response[models.Me], error) {
	return ops.Me(ctx, p.c)
}

// Accounts returns the accounts operations the profile may call.
func (p *Client) Accounts() Accounts {
	return Accounts{c: p.c}
}

// Accounts holds the accounts operations profile acme-ci may call.
type Accounts struct {
	c *inorbit.Client
}

// GetMe calls GET /v1/accounts/me; needs scope account:read. Transcoded from `/iohr.accounts.v1.AccountsService/GetMe` on the `accounts` backend.
func (h Accounts) GetMe(ctx context.Context) (*inorbit.Response[models.GetMeResponse], error) {
	return ops.GetMe(ctx, h.c)
}

// GetUnits calls GET /v1/accounts/orgs/{org_id}/units; needs scope usage:read. Transcoded from `/iohr.accounts.v1.AccountsService/GetUnits` on the `accounts` backend.
func (h Accounts) GetUnits(ctx context.Context, orgID string) (*inorbit.Response[models.GetUnitsResponse], error) {
	return ops.GetUnits(ctx, h.c, orgID)
}

// GetUsage calls GET /v1/accounts/orgs/{org_id}/usage; needs scope usage:read. Transcoded from `/iohr.accounts.v1.AccountsService/GetUsage` on the `accounts` backend.
func (h Accounts) GetUsage(ctx context.Context, orgID string, params *models.AccountsGetUsageParams) (*inorbit.Response[models.GetUsageResponse], error) {
	return ops.GetUsage(ctx, h.c, orgID, params)
}

// ListUnitCategories calls GET /v1/accounts/units/categories; needs scope usage:read. Transcoded from `/iohr.accounts.v1.AccountsService/ListUnitCategories` on the `accounts` backend.
func (h Accounts) ListUnitCategories(ctx context.Context, params *models.AccountsListUnitCategoriesParams) (*inorbit.Response[models.ListUnitCategoriesResponse], error) {
	return ops.ListUnitCategories(ctx, h.c, params)
}

// AllListUnitCategories iterates over every item ListUnitCategories returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Accounts) AllListUnitCategories(ctx context.Context, params *models.AccountsListUnitCategoriesParams) iter.Seq2[models.UnitCategory, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.UnitCategory, string, error) {
		p := models.AccountsListUnitCategoriesParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListUnitCategories(ctx, h.c, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Categories, r.Value.NextPageToken, nil
	})
}

// Events returns the events operations the profile may call.
func (p *Client) Events() Events {
	return Events{c: p.c}
}

// Events holds the events operations profile acme-ci may call.
type Events struct {
	c *inorbit.Client
}

// DeleteEndpoint calls DELETE /v1/webhooks/endpoints/{endpoint_id}; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/DeleteEndpoint` on the `events` backend.
func (h Events) DeleteEndpoint(ctx context.Context, endpointID string) (*inorbit.Response[models.DeleteEndpointResponse], error) {
	return ops.DeleteEndpoint(ctx, h.c, endpointID)
}

// DeleteInbox calls DELETE /v1/webhooks/inboxes/{inbox_id}; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/DeleteInbox` on the `events` backend.
func (h Events) DeleteInbox(ctx context.Context, inboxID string) (*inorbit.Response[models.DeleteInboxResponse], error) {
	return ops.DeleteInbox(ctx, h.c, inboxID)
}

// StreamEvents calls GET /v1/events/events; needs scope events:read. Transcoded from `/iohr.events.v1.EventsService/StreamEvents` on the `events` backend.
// It yields each event as it arrives; an error ends the stream, and breaking out of the loop or ending ctx closes it.
func (h Events) StreamEvents(ctx context.Context, params *models.EventsStreamEventsParams) iter.Seq2[*models.StreamEventsResponse, error] {
	return ops.StreamEvents(ctx, h.c, params)
}

// ListEventTypes calls GET /v1/events/types; needs scope events:read. Transcoded from `/iohr.events.v1.EventsService/ListEventTypes` on the `events` backend.
func (h Events) ListEventTypes(ctx context.Context, params *models.EventsListEventTypesParams) (*inorbit.Response[models.ListEventTypesResponse], error) {
	return ops.ListEventTypes(ctx, h.c, params)
}

// AllListEventTypes iterates over every item ListEventTypes returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Events) AllListEventTypes(ctx context.Context, params *models.EventsListEventTypesParams) iter.Seq2[models.EventType, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.EventType, string, error) {
		p := models.EventsListEventTypesParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListEventTypes(ctx, h.c, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Types, r.Value.NextPageToken, nil
	})
}

// ListEndpoints calls GET /v1/webhooks/endpoints; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/ListEndpoints` on the `events` backend.
func (h Events) ListEndpoints(ctx context.Context, params *models.EventsListEndpointsParams) (*inorbit.Response[models.ListEndpointsResponse], error) {
	return ops.ListEndpoints(ctx, h.c, params)
}

// AllListEndpoints iterates over every item ListEndpoints returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Events) AllListEndpoints(ctx context.Context, params *models.EventsListEndpointsParams) iter.Seq2[models.Endpoint, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.Endpoint, string, error) {
		p := models.EventsListEndpointsParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListEndpoints(ctx, h.c, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Endpoints, r.Value.NextPageToken, nil
	})
}

// GetEndpoint calls GET /v1/webhooks/endpoints/{endpoint_id}; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/GetEndpoint` on the `events` backend.
func (h Events) GetEndpoint(ctx context.Context, endpointID string) (*inorbit.Response[models.Endpoint], error) {
	return ops.GetEndpoint(ctx, h.c, endpointID)
}

// ListDeliveries calls GET /v1/webhooks/endpoints/{endpoint_id}/deliveries; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/ListDeliveries` on the `events` backend.
func (h Events) ListDeliveries(ctx context.Context, endpointID string, params *models.EventsListDeliveriesParams) (*inorbit.Response[models.ListDeliveriesResponse], error) {
	return ops.ListDeliveries(ctx, h.c, endpointID, params)
}

// AllListDeliveries iterates over every item ListDeliveries returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Events) AllListDeliveries(ctx context.Context, endpointID string, params *models.EventsListDeliveriesParams) iter.Seq2[models.Delivery, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.Delivery, string, error) {
		p := models.EventsListDeliveriesParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListDeliveries(ctx, h.c, endpointID, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Deliveries, r.Value.NextPageToken, nil
	})
}

// ListInboxes calls GET /v1/webhooks/inboxes; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/ListInboxes` on the `events` backend.
func (h Events) ListInboxes(ctx context.Context, params *models.EventsListInboxesParams) (*inorbit.Response[models.ListInboxesResponse], error) {
	return ops.ListInboxes(ctx, h.c, params)
}

// AllListInboxes iterates over every item ListInboxes returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Events) AllListInboxes(ctx context.Context, params *models.EventsListInboxesParams) iter.Seq2[models.Inbox, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.Inbox, string, error) {
		p := models.EventsListInboxesParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListInboxes(ctx, h.c, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Inboxes, r.Value.NextPageToken, nil
	})
}

// ListInboxRequests calls GET /v1/webhooks/inboxes/{inbox_id}/requests; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/ListInboxRequests` on the `events` backend.
func (h Events) ListInboxRequests(ctx context.Context, inboxID string, params *models.EventsListInboxRequestsParams) (*inorbit.Response[models.ListInboxRequestsResponse], error) {
	return ops.ListInboxRequests(ctx, h.c, inboxID, params)
}

// AllListInboxRequests iterates over every item ListInboxRequests returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Events) AllListInboxRequests(ctx context.Context, inboxID string, params *models.EventsListInboxRequestsParams) iter.Seq2[models.InboxRequest, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.InboxRequest, string, error) {
		p := models.EventsListInboxRequestsParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListInboxRequests(ctx, h.c, inboxID, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Requests, r.Value.NextPageToken, nil
	})
}

// UpdateEndpoint calls PATCH /v1/webhooks/endpoints/{endpoint_id}; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/UpdateEndpoint` on the `events` backend.
func (h Events) UpdateEndpoint(ctx context.Context, endpointID string, body models.UpdateEndpointRequest) (*inorbit.Response[models.Endpoint], error) {
	return ops.UpdateEndpoint(ctx, h.c, endpointID, body)
}

// RetryDelivery calls POST /v1/webhooks/deliveries/{delivery_id}/retry; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/RetryDelivery` on the `events` backend.
func (h Events) RetryDelivery(ctx context.Context, deliveryID string) (*inorbit.Response[models.RetryDeliveryResponse], error) {
	return ops.RetryDelivery(ctx, h.c, deliveryID)
}

// CreateEndpoint calls POST /v1/webhooks/endpoints; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/CreateEndpoint` on the `events` backend.
func (h Events) CreateEndpoint(ctx context.Context, body models.CreateEndpointRequest) (*inorbit.Response[models.CreateEndpointResponse], error) {
	return ops.CreateEndpoint(ctx, h.c, body)
}

// RotateSecret calls POST /v1/webhooks/endpoints/{endpoint_id}/rotate; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/RotateSecret` on the `events` backend.
func (h Events) RotateSecret(ctx context.Context, endpointID string) (*inorbit.Response[models.RotateSecretResponse], error) {
	return ops.RotateSecret(ctx, h.c, endpointID)
}

// SendTest calls POST /v1/webhooks/endpoints/{endpoint_id}/test; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/SendTest` on the `events` backend.
func (h Events) SendTest(ctx context.Context, endpointID string) (*inorbit.Response[models.SendTestResponse], error) {
	return ops.SendTest(ctx, h.c, endpointID)
}

// CreateInbox calls POST /v1/webhooks/inboxes; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/CreateInbox` on the `events` backend.
func (h Events) CreateInbox(ctx context.Context, body models.CreateInboxRequest) (*inorbit.Response[models.CreateInboxResponse], error) {
	return ops.CreateInbox(ctx, h.c, body)
}

// Radar returns the radar operations the profile may call.
func (p *Client) Radar() Radar {
	return Radar{c: p.c}
}

// Radar holds the radar operations profile acme-ci may call.
type Radar struct {
	c *inorbit.Client
}

// ListDigests calls GET /v1/radar/digests; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/ListDigests` on the `radar` backend.
func (h Radar) ListDigests(ctx context.Context, params *models.RadarListDigestsParams) (*inorbit.Response[models.ListDigestsResponse], error) {
	return ops.ListDigests(ctx, h.c, params)
}

// AllListDigests iterates over every item ListDigests returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Radar) AllListDigests(ctx context.Context, params *models.RadarListDigestsParams) iter.Seq2[models.Digest, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.Digest, string, error) {
		p := models.RadarListDigestsParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListDigests(ctx, h.c, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Digests, r.Value.NextPageToken, nil
	})
}

// GetDigest calls GET /v1/radar/digests/{id}; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/GetDigest` on the `radar` backend.
func (h Radar) GetDigest(ctx context.Context, id string) (*inorbit.Response[models.GetDigestResponse], error) {
	return ops.GetDigest(ctx, h.c, id)
}

// ListItems calls GET /v1/radar/items; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/ListItems` on the `radar` backend.
func (h Radar) ListItems(ctx context.Context, params *models.RadarListItemsParams) (*inorbit.Response[models.ListItemsResponse], error) {
	return ops.ListItems(ctx, h.c, params)
}

// AllListItems iterates over every item ListItems returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Radar) AllListItems(ctx context.Context, params *models.RadarListItemsParams) iter.Seq2[models.Item, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.Item, string, error) {
		p := models.RadarListItemsParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListItems(ctx, h.c, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Items, r.Value.NextPageToken, nil
	})
}
