// Code generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; DO NOT EDIT.

// Package acmeci is the InOrbit API surface for profile acme-ci: only the operations its cut holds, so a call it may not make does not build. FromEnv reads INORBIT_ACME_CI_TOKEN, or INORBIT_ACME_CI_KEY_ID, INORBIT_ACME_CI_KEY_SECRET and INORBIT_ACME_CI_SCOPES, and nothing else.
package acmeci

import (
	"context"
	"iter"

	"example.com/app/iohr/internal/ops"
	"example.com/app/iohr/models"
	inorbit "github.com/inorbithr/sdk/go"
	"github.com/inorbithr/sdk/go/codegen"
)

// The surface was generated for the runtime's contract 2: a runtime with another contract fails to build here, so run iohr sdk generate again.
const _ = codegen.V2

// Profile is the profile's name.
const Profile = "acme-ci"

// Client calls the operations profile acme-ci may call.
type Client struct {
	c *inorbit.Client
}

// New returns the profile's surface on c, a client built for its credential.
func New(c *inorbit.Client) *Client {
	return &Client{c: c}
}

// FromEnv returns the profile's surface with its credential from the environment; opts apply after it.
func FromEnv(opts ...inorbit.Option) (*Client, error) {
	c, err := inorbit.FromEnv("ACME_CI", opts...)
	if err != nil {
		return nil, err
	}
	return New(c), nil
}

// Runtime returns the client underneath, for a raw call with Send.
func (p *Client) Runtime() *inorbit.Client {
	return p.c
}

// Me calls GET /v1/me; needs scope identity:read. A key needs scope `identity:read`.
func (p *Client) Me(ctx context.Context) (*inorbit.Response[models.Me], error) {
	return ops.Me(ctx, p.c)
}

// Accounts returns the accounts operations the profile may call.
func (p *Client) Accounts() Accounts {
	return Accounts{c: p.c}
}

// Accounts holds the accounts operations profile acme-ci may call.
type Accounts struct {
	c *inorbit.Client
}

// GetMe calls GET /v1/accounts/me; needs scope account:read. Transcoded from `/iohr.accounts.v1.AccountsService/GetMe` on the `accounts` backend.
func (h Accounts) GetMe(ctx context.Context) (*inorbit.Response[models.GetMeResponse], error) {
	return ops.GetMe(ctx, h.c)
}

// GetUnits calls GET /v1/accounts/orgs/{org_id}/units; needs scope usage:read. Transcoded from `/iohr.accounts.v1.AccountsService/GetUnits` on the `accounts` backend.
func (h Accounts) GetUnits(ctx context.Context, orgID string) (*inorbit.Response[models.GetUnitsResponse], error) {
	return ops.GetUnits(ctx, h.c, orgID)
}

// GetUsage calls GET /v1/accounts/orgs/{org_id}/usage; needs scope usage:read. Transcoded from `/iohr.accounts.v1.AccountsService/GetUsage` on the `accounts` backend.
func (h Accounts) GetUsage(ctx context.Context, orgID string, params *models.AccountsGetUsageParams) (*inorbit.Response[models.GetUsageResponse], error) {
	return ops.GetUsage(ctx, h.c, orgID, params)
}

// ListUnitCategories calls GET /v1/accounts/units/categories; needs scope usage:read. Transcoded from `/iohr.accounts.v1.AccountsService/ListUnitCategories` on the `accounts` backend.
func (h Accounts) ListUnitCategories(ctx context.Context) (*inorbit.Response[models.ListUnitCategoriesResponse], error) {
	return ops.ListUnitCategories(ctx, h.c)
}

// Events returns the events operations the profile may call.
func (p *Client) Events() Events {
	return Events{c: p.c}
}

// Events holds the events operations profile acme-ci may call.
type Events struct {
	c *inorbit.Client
}

// DeleteEndpoint calls DELETE /v1/webhooks/endpoints/{endpoint_id}; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/DeleteEndpoint` on the `events` backend.
func (h Events) DeleteEndpoint(ctx context.Context, endpointID string) (*inorbit.Response[models.DeleteEndpointResponse], error) {
	return ops.DeleteEndpoint(ctx, h.c, endpointID)
}

// DeleteInbox calls DELETE /v1/webhooks/inboxes/{inbox_id}; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/DeleteInbox` on the `events` backend.
func (h Events) DeleteInbox(ctx context.Context, inboxID string) (*inorbit.Response[models.DeleteInboxResponse], error) {
	return ops.DeleteInbox(ctx, h.c, inboxID)
}

// ListEventTypes calls GET /v1/events/types; needs scope events:read. Transcoded from `/iohr.events.v1.EventsService/ListEventTypes` on the `events` backend.
func (h Events) ListEventTypes(ctx context.Context) (*inorbit.Response[models.ListEventTypesResponse], error) {
	return ops.ListEventTypes(ctx, h.c)
}

// ListEndpoints calls GET /v1/webhooks/endpoints; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/ListEndpoints` on the `events` backend.
func (h Events) ListEndpoints(ctx context.Context, params *models.EventsListEndpointsParams) (*inorbit.Response[models.ListEndpointsResponse], error) {
	return ops.ListEndpoints(ctx, h.c, params)
}

// GetEndpoint calls GET /v1/webhooks/endpoints/{endpoint_id}; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/GetEndpoint` on the `events` backend.
func (h Events) GetEndpoint(ctx context.Context, endpointID string) (*inorbit.Response[models.Endpoint], error) {
	return ops.GetEndpoint(ctx, h.c, endpointID)
}

// ListDeliveries calls GET /v1/webhooks/endpoints/{endpoint_id}/deliveries; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/ListDeliveries` on the `events` backend.
func (h Events) ListDeliveries(ctx context.Context, endpointID string, params *models.EventsListDeliveriesParams) (*inorbit.Response[models.ListDeliveriesResponse], error) {
	return ops.ListDeliveries(ctx, h.c, endpointID, params)
}

// AllListDeliveries iterates over every item ListDeliveries returns, page after page, following NextPageToken until the last page. It stops at the first error, which it yields, and when the loop breaks or ctx is done.
func (h Events) AllListDeliveries(ctx context.Context, endpointID string, params *models.EventsListDeliveriesParams) iter.Seq2[models.Delivery, error] {
	return codegen.Pages(ctx, func(ctx context.Context, token string) ([]models.Delivery, string, error) {
		p := models.EventsListDeliveriesParams{}
		if params != nil {
			p = *params
		}
		if token != "" {
			p.PageToken = &token
		}
		r, err := ops.ListDeliveries(ctx, h.c, endpointID, &p)
		if err != nil {
			return nil, "", err
		}
		return r.Value.Deliveries, r.Value.NextPageToken, nil
	})
}

// ListInboxes calls GET /v1/webhooks/inboxes; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/ListInboxes` on the `events` backend.
func (h Events) ListInboxes(ctx context.Context, params *models.EventsListInboxesParams) (*inorbit.Response[models.ListInboxesResponse], error) {
	return ops.ListInboxes(ctx, h.c, params)
}

// ListInboxRequests calls GET /v1/webhooks/inboxes/{inbox_id}/requests; needs scope webhooks:read. Transcoded from `/iohr.events.v1.EventsService/ListInboxRequests` on the `events` backend.
func (h Events) ListInboxRequests(ctx context.Context, inboxID string) (*inorbit.Response[models.ListInboxRequestsResponse], error) {
	return ops.ListInboxRequests(ctx, h.c, inboxID)
}

// UpdateEndpoint calls PATCH /v1/webhooks/endpoints/{endpoint_id}; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/UpdateEndpoint` on the `events` backend.
func (h Events) UpdateEndpoint(ctx context.Context, endpointID string, body models.UpdateEndpointRequest) (*inorbit.Response[models.Endpoint], error) {
	return ops.UpdateEndpoint(ctx, h.c, endpointID, body)
}

// RetryDelivery calls POST /v1/webhooks/deliveries/{delivery_id}/retry; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/RetryDelivery` on the `events` backend.
func (h Events) RetryDelivery(ctx context.Context, deliveryID string) (*inorbit.Response[models.RetryDeliveryResponse], error) {
	return ops.RetryDelivery(ctx, h.c, deliveryID)
}

// CreateEndpoint calls POST /v1/webhooks/endpoints; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/CreateEndpoint` on the `events` backend.
func (h Events) CreateEndpoint(ctx context.Context, body models.CreateEndpointRequest) (*inorbit.Response[models.CreateEndpointResponse], error) {
	return ops.CreateEndpoint(ctx, h.c, body)
}

// RotateSecret calls POST /v1/webhooks/endpoints/{endpoint_id}/rotate; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/RotateSecret` on the `events` backend.
func (h Events) RotateSecret(ctx context.Context, endpointID string) (*inorbit.Response[models.RotateSecretResponse], error) {
	return ops.RotateSecret(ctx, h.c, endpointID)
}

// SendTest calls POST /v1/webhooks/endpoints/{endpoint_id}/test; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/SendTest` on the `events` backend.
func (h Events) SendTest(ctx context.Context, endpointID string) (*inorbit.Response[models.SendTestResponse], error) {
	return ops.SendTest(ctx, h.c, endpointID)
}

// CreateInbox calls POST /v1/webhooks/inboxes; needs scope webhooks:write. Transcoded from `/iohr.events.v1.EventsService/CreateInbox` on the `events` backend.
func (h Events) CreateInbox(ctx context.Context, body models.CreateInboxRequest) (*inorbit.Response[models.CreateInboxResponse], error) {
	return ops.CreateInbox(ctx, h.c, body)
}

// Radar returns the radar operations the profile may call.
func (p *Client) Radar() Radar {
	return Radar{c: p.c}
}

// Radar holds the radar operations profile acme-ci may call.
type Radar struct {
	c *inorbit.Client
}

// ListDigests calls GET /v1/radar/digests; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/ListDigests` on the `radar` backend.
func (h Radar) ListDigests(ctx context.Context, params *models.RadarListDigestsParams) (*inorbit.Response[models.ListDigestsResponse], error) {
	return ops.ListDigests(ctx, h.c, params)
}

// GetDigest calls GET /v1/radar/digests/{id}; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/GetDigest` on the `radar` backend.
func (h Radar) GetDigest(ctx context.Context, id string) (*inorbit.Response[models.GetDigestResponse], error) {
	return ops.GetDigest(ctx, h.c, id)
}

// ListItems calls GET /v1/radar/items; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/ListItems` on the `radar` backend.
func (h Radar) ListItems(ctx context.Context, params *models.RadarListItemsParams) (*inorbit.Response[models.ListItemsResponse], error) {
	return ops.ListItems(ctx, h.c, params)
}
