// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.events.v1.CreateEndpointRequest</code>
 *
 * @param accountId the <code>account_id</code> field; <code>null</code> when unset, and then left out on the wire
 * @param description the <code>description</code> field; <code>null</code> when unset, and then left out on the wire
 * @param eventTypes the <code>event_types</code> field; <code>null</code> when unset, and then left out on the wire
 * @param url the <code>url</code> field; <code>null</code> when unset, and then left out on the wire
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record CreateEndpointRequest(
        @JsonProperty("account_id") String accountId,
        @JsonProperty("description") String description,
        @JsonProperty("event_types") List<String> eventTypes,
        @JsonProperty("url") String url) {

    /**
     * A builder.
     *
     * @return a builder with every field unset
     */
    public static Builder builder() {
        return new Builder();
    }

    /** Builds a <code>CreateEndpointRequest</code>. */
    public static final class Builder {
        private String accountId;
        private String description;
        private List<String> eventTypes;
        private String url;

        private Builder() {}

        /**
         * Sets <code>accountId</code>.
         *
         * @param accountId the value
         * @return this builder
         */
        public Builder accountId(String accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * Sets <code>description</code>.
         *
         * @param description the value
         * @return this builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Sets <code>eventTypes</code>.
         *
         * @param eventTypes the value
         * @return this builder
         */
        public Builder eventTypes(List<String> eventTypes) {
            this.eventTypes = eventTypes;
            return this;
        }

        /**
         * Sets <code>url</code>.
         *
         * @param url the value
         * @return this builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * The value.
         *
         * @return the <code>CreateEndpointRequest</code>
         */
        public CreateEndpointRequest build() {
            return new CreateEndpointRequest(accountId, description, eventTypes, url);
        }
    }
}
