// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.CreateInboxRequest</code>
 *
 * @param accountId the <code>account_id</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record CreateInboxRequest(
        @JsonProperty("account_id") String accountId) {

    /**
     * A builder.
     *
     * @return a builder with every field unset
     */
    public static Builder builder() {
        return new Builder();
    }

    /** Builds a <code>CreateInboxRequest</code>. */
    public static final class Builder {
        private String accountId;

        private Builder() {}

        /**
         * Sets <code>accountId</code>.
         *
         * @param accountId the value
         * @return this builder
         */
        public Builder accountId(String accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * The value.
         *
         * @return the <code>CreateInboxRequest</code>
         */
        public CreateInboxRequest build() {
            return new CreateInboxRequest(accountId);
        }
    }
}
