// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.CreateInboxResponse</code>
 *
 * @param inbox the <code>inbox</code> field; <code>null</code> when the answer leaves it out
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record CreateInboxResponse(
        @JsonProperty("inbox") Inbox inbox) {}
