// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.CreateEndpointResponse</code>
 *
 * @param endpoint the <code>endpoint</code> field; <code>null</code> when the answer leaves it out
 * @param secret the <code>secret</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record CreateEndpointResponse(
        @JsonProperty("endpoint") Endpoint endpoint,
        @JsonProperty("secret") String secret) {}
