// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.events.v1.Endpoint</code>
 *
 * @param createdAt the <code>created_at</code> field
 * @param description the <code>description</code> field
 * @param disabledReason the <code>disabled_reason</code> field
 * @param enabled the <code>enabled</code> field
 * @param eventTypes the <code>event_types</code> field
 * @param failed24h the <code>failed_24h</code> field
 * @param id the <code>id</code> field
 * @param lastDeliveryAt the <code>last_delivery_at</code> field
 * @param lastDeliveryStatus the <code>last_delivery_status</code> field
 * @param secretRotatedAt the <code>secret_rotated_at</code> field
 * @param succeeded24h the <code>succeeded_24h</code> field
 * @param url the <code>url</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Endpoint(
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("description") String description,
        @JsonProperty("disabled_reason") String disabledReason,
        @JsonProperty("enabled") boolean enabled,
        @JsonProperty("event_types") List<String> eventTypes,
        @JsonProperty("failed_24h") int failed24h,
        @JsonProperty("id") String id,
        @JsonProperty("last_delivery_at") String lastDeliveryAt,
        @JsonProperty("last_delivery_status") String lastDeliveryStatus,
        @JsonProperty("secret_rotated_at") String secretRotatedAt,
        @JsonProperty("succeeded_24h") int succeeded24h,
        @JsonProperty("url") String url) {}
