// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
package iohr;

import hr.inorbit.sdk.Client;
import java.util.Objects;

/**
 * Profile <code>hooks</code>: the operations its cut holds. <code>fromEnv()</code> reads <code>INORBIT_HOOKS_TOKEN</code>, or <code>INORBIT_HOOKS_KEY_ID</code>, <code>INORBIT_HOOKS_KEY_SECRET</code> and <code>INORBIT_HOOKS_SCOPES</code>, and nothing else.
 */
public final class Hooks {

    /** The profile's name. */
    public static final String PROFILE = "hooks";

    private final Client client;
    private final HooksEvents events;

    /**
     * The profile on a client built for its credential.
     *
     * @param client the client
     */
    public Hooks(Client client) {
        this.client = Objects.requireNonNull(client, "client");
        this.events = new HooksEvents(client);
    }

    /**
     * The profile with its credential from the environment.
     *
     * @return the profile
     * @throws hr.inorbit.sdk.errors.ConfigException naming the variables to set when no credential is there
     */
    public static Hooks fromEnv() {
        return new Hooks(Client.fromEnv("HOOKS"));
    }

    /**
     * The profile from code, the environment, the <code>iohr</code> config file and login, and the defaults (docs/config.md).
     *
     * @return the profile
     * @throws hr.inorbit.sdk.errors.ConfigException listing every problem found, each with its setting and source
     */
    public static Hooks load() {
        return new Hooks(Client.builder().profileType("hooks").load());
    }

    /**
     * The client the profile calls with.
     *
     * @return the client
     */
    public Client client() {
        return client;
    }

    /**
     * The <code>events</code> operations.
     *
     * @return the handle
     */
    public HooksEvents events() {
        return events;
    }
}
