// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
/**
 * The InOrbit API surface for <code>hooks</code> (API 0.1.0): the models and the operations these profiles may
 * call, on the <code>hr.inorbit.sdk</code> runtime. Generated by <code>iohr sdk generate</code>; regenerate it, never
 * edit it. <code>iohr sdk check</code> says when the API's cut has moved.
 */
package iohr;
