// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
/**
 * The InOrbit API surface for <code>hooks</code> (API 0.1.0): the models and the operations these profiles may
 * call, on the <code>hr.inorbit.sdk</code> runtime. Generated by <code>iohr sdk generate</code>; regenerate it, never
 * edit it. <code>iohr sdk check</code> says when the API's cut has moved.
 */
package iohr;
