// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import hr.inorbit.sdk.errors.Code;
import hr.inorbit.sdk.errors.Detail;
import java.util.List;

/**
 * <code>{"code","error","details"}</code>: the REST body and the SSE <code>error</code> payload.
 *
 * @param code The slug.
 * @param details Typed details.
 * @param error The sentence.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Problem(
        @JsonProperty("code") Code code,
        @JsonProperty("details") List<Detail> details,
        @JsonProperty("error") String error) {}
