// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.RetryDeliveryResponse</code>
 *
 * @param delivery the <code>delivery</code> field; <code>null</code> when unset, and then left out on the wire
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record RetryDeliveryResponse(
        @JsonProperty("delivery") Delivery delivery) {}
