// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.RotateSecretResponse</code>
 *
 * @param previousExpiresAt the <code>previous_expires_at</code> field
 * @param secret the <code>secret</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record RotateSecretResponse(
        @JsonProperty("previous_expires_at") String previousExpiresAt,
        @JsonProperty("secret") String secret) {}
