# Generated by iohr sdk generate for cuts public=sha256:2ee56b0e0332e9ffad4f4789c88cb88a98c632cd474e957c1b19428019182014; do not edit.
"""The models of the InOrbit API this surface was generated from."""

from __future__ import annotations

from typing import Literal

from pydantic import (
    BaseModel,
    ConfigDict,
)
from pydantic import Field as _Field

from ..runtime import (
    Code,
    Detail,
    Int64,
)


class _Model(BaseModel):
    """Fields this version does not know are kept; wire names are accepted too."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)


class Account(_Model):
    """`iohr.accounts.v1.Account`"""

    created_at: str
    erase_after: str
    id: str
    kind: str
    name: str
    plan: str
    probe: bool
    role: str
    slug: str
    status: str


class AccountsKey(_Model):
    """`iohr.accounts.v1.Key`"""

    client_id: str
    created_at: str
    created_by: str
    expires_at: str
    id: str
    kind: str
    last_used_at: str
    name: str
    revoked_at: str
    scopes: list[str]
    secret_hint: str


class ActionResult(_Model):
    """`iohr.connections.v1.ActionResult`"""

    error_class: str
    executor: str
    latency_ms: int
    message: str
    ok: bool
    output: Struct | None = None
    started_at: str
    status: str
    status_code: int
    use_id: str


class AddCommentRequest(_Model):
    """`iohr.decisions.v1.AddCommentRequest`"""

    anchor: str | None = None
    body: str | None = None
    document_id: str | None = None
    parent_id: str | None = None
    quote: Quote | None = None
    space_id: str | None = None


class AddCommentResponse(_Model):
    """`iohr.decisions.v1.AddCommentResponse`"""

    comment: Comment | None = None


class AddDomainRequest(_Model):
    """`iohr.accounts.v1.AddDomainRequest`"""

    domain: str | None = None
    org_id: str | None = None
    scope: str | None = None


class AddDomainResponse(_Model):
    """`iohr.accounts.v1.AddDomainResponse`"""

    domain: Domain | None = None


class Agent(_Model):
    """`iohr.agents.v1.Agent`"""

    agent_id: str
    arch: str
    capabilities: list[str]
    checks: AgentChecks | None = None
    clock_skew_ms: Int64 | None = None
    domains: list[str]
    enrolled_at: str
    environment: str
    last_seen_at: str
    metadata: Struct | None = None
    name: str
    os: str
    policy_hash: str
    revoked_at: str
    rtt_last_ms: int | None = None
    rtt_p95_ms: int | None = None
    status: str
    version: str


class AgentChecks(_Model):
    """`iohr.agents.v1.AgentChecks`"""

    accepted: int
    checks_hash: str
    reconciled_at: str
    rejected: list[RejectedCheck]


class AppendStatusRequest(_Model):
    """`iohr.decisions.v1.AppendStatusRequest`"""

    base_version: int | None = None
    date: str | None = None
    document_id: str | None = None
    line: str | None = None
    space_id: str | None = None


class AppendStatusResponse(_Model):
    """`iohr.decisions.v1.AppendStatusResponse`"""

    document: Document | None = None
    findings: list[Finding]
    version: int


class AuthMode(_Model):
    """`iohr.connections.v1.AuthMode`"""

    fields: list[ConnectorField]
    label: str
    mode: str
    needs_app: bool
    optional_scopes: list[str]
    refresh: bool
    scopes: list[str]


class CallActionRequest(_Model):
    """`iohr.connections.v1.CallActionRequest`"""

    action: str | None = None
    connection_id: str | None = None
    org_id: str | None = None
    params: Struct | None = None


class CallActionResponse(_Model):
    """`iohr.connections.v1.CallActionResponse`"""

    result: ActionResult | None = None


class CallToolRequest(_Model):
    """`iohr.connections.v1.CallToolRequest`"""

    args_json: str | None = None
    name: str | None = None


class CallToolResponse(_Model):
    """`iohr.connections.v1.CallToolResponse`"""

    ms: Int64
    ok: bool
    result_json: str
    tool: str


class Change(_Model):
    """`iohr.radar.v1.Change`"""

    advanced: str
    after: str
    area: str
    example: Example | None = None
    impact: Literal["IMPACT_UNSPECIFIED", "IMPACT_BREAKING", "IMPACT_WORTH_KNOWING", "IMPACT_NICE_TO_KNOW"]
    """`iohr.radar.v1.Impact`"""
    novice: str
    practitioner: str
    production_impact: str
    title: str
    try_it: str
    url: str
    what: str


class CheckDetail(_Model):
    """`iohr.agents.v1.CheckDetail`"""

    error_class: str
    invariants: list[Invariant]
    latency_ms: int
    ok: bool
    status_code: int
    tls_expires_at: str


class CheckDomainRequest(_Model):
    """`iohr.accounts.v1.CheckDomainRequest`"""

    domain: str | None = None
    org_id: str | None = None


class CheckDomainResponse(_Model):
    """`iohr.accounts.v1.CheckDomainResponse`"""

    domain: Domain | None = None
    resolvers: list[ResolverAnswer]
    status: str


class ClientSetup(_Model):
    """`iohr.connections.v1.ClientSetup`"""

    description: str
    mcp_url: str
    snippets: list[ClientSnippet]
    suggested_scopes: list[str]


class ClientSnippet(_Model):
    """`iohr.connections.v1.ClientSnippet`"""

    label: str
    language: str
    path: str
    text: str


class Comment(_Model):
    """`iohr.decisions.v1.Comment`"""

    anchor: str
    author: str
    body: str
    comment_id: str
    created_at: str
    document_id: str
    parent_id: str
    quote: Quote | None = None
    resolved: bool
    resolved_at: str
    resolved_by: str
    version: int


class CompleteConnectRequest(_Model):
    """`iohr.connections.v1.CompleteConnectRequest`"""

    code: str | None = None
    error: str | None = None
    error_description: str | None = None
    org_id: str | None = None
    state: str | None = None


class CompleteConnectResponse(_Model):
    """`iohr.connections.v1.CompleteConnectResponse`"""

    connection: Connection | None = None


class ConfirmDomainRequest(_Model):
    """`iohr.accounts.v1.ConfirmDomainRequest`"""

    domain: str | None = None
    org_id: str | None = None


class ConfirmDomainResponse(_Model):
    """`iohr.accounts.v1.ConfirmDomainResponse`"""

    domain: Domain | None = None


class Connection(_Model):
    """`iohr.connections.v1.Connection`"""

    account_id: str
    auth_mode: str
    config: dict[str, str]
    connector: str
    created_at: str
    credential: Credential | None = None
    description: str
    executor: Executor | None = None
    external_id: str
    grants: int
    id: str
    kind: str
    label: str
    last_test_at: str
    last_test_error: str
    last_test_ok: bool
    name: str
    owner: str
    receive_url: str
    scopes: list[str]
    status: str
    token_expires_at: str
    updated_at: str
    used_by: list[str]


class Connector(_Model):
    """`iohr.connections.v1.Connector`"""

    actions: list[ConnectorAction]
    ai: bool
    auth_modes: list[AuthMode]
    category: str
    config_fields: list[ConnectorField]
    description: str
    docs: str
    hosts: list[str]
    icon: str
    id: str
    kind: str
    name: str
    redirect_url: str
    setup: ClientSetup | None = None
    status: str
    triggers: list[ConnectorTrigger]


class ConnectorAction(_Model):
    """`iohr.connections.v1.ConnectorAction`"""

    auth_modes: list[str]
    class_: str = _Field(alias="class")
    model: str
    name: str
    params: list[ConnectorField]
    title: str


class ConnectorField(_Model):
    """`iohr.connections.v1.ConnectorField`"""

    after_consent: bool
    choices: list[str]
    default: str
    help: str
    label: str
    max: Int64
    name: str
    required: bool
    secret: bool
    type: str


class ConnectorTrigger(_Model):
    """`iohr.connections.v1.ConnectorTrigger`"""

    name: str
    title: str


class Consumer(_Model):
    """`iohr.connections.v1.Consumer`"""

    id: str | None = None
    kind: str | None = None


class CreateConnectionRequest(_Model):
    """`iohr.connections.v1.CreateConnectionRequest`"""

    auth_mode: str | None = None
    config: dict[str, str] | None = None
    credentials: dict[str, str] | None = None
    description: str | None = None
    executor: Executor | None = None
    kind: str | None = None
    name: str | None = None
    org_id: str | None = None
    secret: str | None = None
    secret_ref: str | None = None


class CreateConnectionResponse(_Model):
    """`iohr.connections.v1.CreateConnectionResponse`"""

    connection: Connection | None = None
    webhook_secret: str


class CreateDiagramRequest(_Model):
    """`iohr.decisions.v1.CreateDiagramRequest`"""

    model: str | None = None
    name: str | None = None
    space_id: str | None = None


class CreateDiagramResponse(_Model):
    """`iohr.decisions.v1.CreateDiagramResponse`"""

    diagram: Diagram | None = None
    model: str


class CreateDocumentRequest(_Model):
    """`iohr.decisions.v1.CreateDocumentRequest`"""

    child_index: int | None = None
    kind: str | None = None
    number: int | None = None
    outward: bool | None = None
    parent_id: str | None = None
    space_id: str | None = None
    summary: str | None = None
    template: str | None = None
    title: str | None = None


class CreateDocumentResponse(_Model):
    """`iohr.decisions.v1.CreateDocumentResponse`"""

    document: Document | None = None
    findings: list[Finding]
    text: str


class CreateEndpointRequest(_Model):
    """`iohr.events.v1.CreateEndpointRequest`"""

    account_id: str | None = None
    description: str | None = None
    event_types: list[str] | None = None
    url: str | None = None


class CreateEndpointResponse(_Model):
    """`iohr.events.v1.CreateEndpointResponse`"""

    endpoint: Endpoint | None = None
    secret: str


class CreateEnrollmentRequest(_Model):
    """`iohr.agents.v1.CreateEnrollmentRequest`"""

    domains: list[str] | None = None
    environment: str | None = None
    name: str | None = None
    org_id: str | None = None


class CreateEnrollmentResponse(_Model):
    """`iohr.agents.v1.CreateEnrollmentResponse`"""

    enrollment_id: str
    expires_at: str
    token: str


class CreateInboxRequest(_Model):
    """`iohr.events.v1.CreateInboxRequest`"""

    account_id: str | None = None


class CreateInboxResponse(_Model):
    """`iohr.events.v1.CreateInboxResponse`"""

    inbox: Inbox | None = None


class CreateMonitorRequest(_Model):
    """`iohr.connections.v1.CreateMonitorRequest`"""

    category: str | None = None
    connection_id: str | None = None
    fail_after: int | None = None
    interval_secs: int | None = None
    name: str | None = None
    org_id: str | None = None
    params: MonitorParams | None = None
    rfc: str | None = None
    tags: dict[str, str] | None = None


class CreateMonitorResponse(_Model):
    """`iohr.connections.v1.CreateMonitorResponse`"""

    monitor: Monitor | None = None


class CreateSpaceRequest(_Model):
    """`iohr.decisions.v1.CreateSpaceRequest`"""

    account_id: str | None = None
    description: str | None = None
    name: str | None = None
    slug: str | None = None


class CreateSpaceResponse(_Model):
    """`iohr.decisions.v1.CreateSpaceResponse`"""

    space: Space | None = None


class Credential(_Model):
    """`iohr.connections.v1.Credential`"""

    kind: str
    reference: str
    set_at: str


class DecisionsListVersionsResponse(_Model):
    """`iohr.decisions.v1.ListVersionsResponse`"""

    next_page_token: str
    versions: list[DecisionsVersion]


class DecisionsVersion(_Model):
    """`iohr.decisions.v1.Version`"""

    author: str
    bytes: int
    message: str
    saved_at: str
    version: int


class DeclaredCheck(_Model):
    """`iohr.connections.v1.DeclaredCheck`"""

    expect: DeclaredExpect | None = None
    key: str
    notify: bool
    refuse_by: str
    service: str
    surface: str
    target: DeclaredTarget | None = None


class DeclaredExpect(_Model):
    """`iohr.connections.v1.DeclaredExpect`"""

    max_ms: int
    status: int
    valid_for_days: int


class DeclaredTarget(_Model):
    """`iohr.connections.v1.DeclaredTarget`"""

    host: str
    port: int
    tls: bool
    url: str


class DeleteAgentResponse(_Model):
    """`iohr.agents.v1.DeleteAgentResponse`"""


class DeleteConnectionResponse(_Model):
    """`iohr.connections.v1.DeleteConnectionResponse`"""


class DeleteDiagramResponse(_Model):
    """`iohr.decisions.v1.DeleteDiagramResponse`"""


class DeleteEndpointResponse(_Model):
    """`iohr.events.v1.DeleteEndpointResponse`"""


class DeleteInboxResponse(_Model):
    """`iohr.events.v1.DeleteInboxResponse`"""


class DeleteMonitorResponse(_Model):
    """`iohr.connections.v1.DeleteMonitorResponse`"""


class DeleteRecordingResponse(_Model):
    """`iohr.trails.v1.DeleteRecordingResponse`"""


class DeleteSpaceResponse(_Model):
    """`iohr.decisions.v1.DeleteSpaceResponse`"""


class Delivery(_Model):
    """`iohr.events.v1.Delivery`"""

    attempts: int
    created_at: str
    endpoint_id: str
    event_id: str
    event_type: str
    id: str
    last_error: str
    last_latency_ms: int
    last_status_code: int
    next_attempt_at: str
    status: str
    updated_at: str


class DeliveryErrorCount(_Model):
    """`iohr.events.v1.DeliveryErrorCount`"""

    count: Int64
    error: str
    last_at: str
    status_code: int


class DeliveryStatsBucket(_Model):
    """`iohr.events.v1.DeliveryStatsBucket`"""

    failed: Int64
    p50_ms: int
    p95_ms: int
    start: str
    succeeded: Int64


class DeliveryTypeCount(_Model):
    """`iohr.events.v1.DeliveryTypeCount`"""

    failed: Int64
    succeeded: Int64
    type: str


class Diagram(_Model):
    """`iohr.decisions.v1.Diagram`"""

    created_at: str
    created_by: str
    current_version: int
    diagram_id: str
    element_kinds: list[str]
    kind: str
    name: str
    nodes: int
    space_id: str
    space_name: str
    svg_path: str
    updated_at: str
    used_in_count: int


class DiagramUse(_Model):
    """`iohr.decisions.v1.DiagramUse`"""

    display_number: str
    document_id: str
    kind: str
    number: int
    position: int
    space_id: str
    status: str
    title: str


class DiagramVersion(_Model):
    """`iohr.decisions.v1.DiagramVersion`"""

    author: str
    message: str
    saved_at: str
    version: int


class DiffLine(_Model):
    """`iohr.decisions.v1.DiffLine`"""

    kind: str
    text: str


class Digest(_Model):
    """`iohr.radar.v1.Digest`"""

    ai_written: bool
    changed: str
    changes: list[Change]
    checked: bool
    created_at: str
    drill: str
    drill_code: DrillCode | None = None
    id: Int64
    item_count: int
    lang: str
    language: str
    model: str
    origin: str
    published_at: str
    script: str
    status: str
    stub: bool
    summary: str
    week: str
    why: str


class Document(_Model):
    """`iohr.decisions.v1.Document`"""

    access: str
    approved_by: str
    child_index: int
    children: int
    created_at: str
    created_by: str
    current_version: int
    decider: str
    display_number: str
    document_id: str
    headline: str
    headline_note: str
    kind: str
    measures_id: str
    number: int
    outward: bool
    parent_id: str
    path: str
    public: bool
    review_by: str
    review_overdue: bool
    slug: str
    source: str
    space_id: str
    stage: str
    status: str
    summary: str
    superseded_by: str
    supersedes_id: str
    title: str
    updated_at: str


class Domain(_Model):
    """`iohr.accounts.v1.Domain`"""

    created_at: str
    dns_provider: str
    domain: str
    expires_at: str
    last_checked_at: str
    record_name: str
    record_value: str
    scope: str
    status: str
    unverified_reason: str
    verified_at: str


class DrillCode(_Model):
    """`iohr.radar.v1.DrillCode`"""

    output: str
    solution: str
    starter: str
    stub: bool
    tests: str
    toolchain: str


class Endpoint(_Model):
    """`iohr.events.v1.Endpoint`"""

    created_at: str
    description: str
    disabled_reason: str
    enabled: bool
    event_types: list[str]
    failed_24h: int
    id: str
    last_delivery_at: str
    last_delivery_status: str
    secret_rotated_at: str
    succeeded_24h: int
    url: str


class EventStatsRow(_Model):
    """`iohr.events.v1.EventStatsRow`"""

    count: Int64
    day: str
    type: str


class EventType(_Model):
    """`iohr.events.v1.EventType`"""

    description: str
    schema_: str = _Field(alias="schema")
    type: str


class Evidence(_Model):
    """`iohr.extensions.v1.Evidence`"""

    record_ids: list[str]
    summary: str


class Example(_Model):
    """`iohr.radar.v1.Example`"""

    source: str
    stderr: str
    stdout: str
    stub: bool
    tests: str
    toolchain: str


class Executor(_Model):
    """`iohr.connections.v1.Executor`"""

    agent_id: str | None = None
    kind: str | None = None


class Expect(_Model):
    """`iohr.agents.v1.Expect`"""

    max_ms: int | None = None
    status: int | None = None


class ExportFile(_Model):
    """`iohr.decisions.v1.ExportFile`"""

    content: str
    path: str


class ExportSpaceResponse(_Model):
    """`iohr.decisions.v1.ExportSpaceResponse`"""

    files: list[ExportFile]
    next_page_token: str


class Extension(_Model):
    """`iohr.extensions.v1.Extension`"""

    coming: bool
    created_at: str
    description: str
    first_party: bool
    included_by: str
    install: str
    kind: str
    latest: ExtensionsVersion | None = None
    name: str
    publisher: str
    publisher_name: str
    shared_with: list[str]
    signer: str
    source: str
    updated_at: str
    visibility: str


class ExtensionsListVersionsResponse(_Model):
    """`iohr.extensions.v1.ListVersionsResponse`"""

    next_page_token: str
    versions: list[ExtensionsVersion]


class ExtensionsVersion(_Model):
    """`iohr.extensions.v1.Version`"""

    description: str
    digest: str
    entrypoint: str
    evidence: Evidence | None = None
    platforms: list[str]
    privileges: list[str]
    published_at: str
    scopes: list[str]
    signer: str
    version: str


class Field(_Model):
    """`iohr.connections.v1.Field`"""

    choices: list[str]
    default_value: str
    description: str
    max: Int64
    min: Int64
    name: str
    required: bool
    type: str


class Finding(_Model):
    """`iohr.decisions.v1.Finding`"""

    line: int
    message: str
    rule: str


class GetAgentResponse(_Model):
    """`iohr.agents.v1.GetAgentResponse`"""

    agent: Agent | None = None


class GetConnectSessionResponse(_Model):
    """`iohr.connections.v1.GetConnectSessionResponse`"""

    connection: Connection | None = None
    error: str
    expires_at: str
    status: str


class GetConnectionResponse(_Model):
    """`iohr.connections.v1.GetConnectionResponse`"""

    connection: Connection | None = None


class GetConnectorResponse(_Model):
    """`iohr.connections.v1.GetConnectorResponse`"""

    connector: Connector | None = None


class GetDeliveryStatsResponse(_Model):
    """`iohr.events.v1.GetDeliveryStatsResponse`"""

    bucket: str
    buckets: list[DeliveryStatsBucket]
    errors: list[DeliveryErrorCount]
    failed: Int64
    in_flight: Int64
    p50_ms: int
    p95_ms: int
    range: str
    succeeded: Int64
    types: list[DeliveryTypeCount]


class GetDiagramResponse(_Model):
    """`iohr.decisions.v1.GetDiagramResponse`"""

    diagram: Diagram | None = None
    model: str
    svg: str
    used_in: list[DiagramUse]
    version: int


class GetDigestResponse(_Model):
    """`iohr.radar.v1.GetDigestResponse`"""

    digest: Digest | None = None


class GetDocumentResponse(_Model):
    """`iohr.decisions.v1.GetDocumentResponse`"""

    author: str
    children: list[Document]
    context: list[Document]
    context_for: list[Document]
    diagrams: list[Diagram]
    diff: VersionDiff | None = None
    document: Document | None = None
    findings: list[Finding]
    implemented_by: list[Document]
    implements: list[Document]
    measured_by: list[Document]
    measures: Document | None = None
    mentioned_in: list[Document]
    mentions: list[Document]
    message: str
    parent: Document | None = None
    saved_at: str
    successors: list[Document]
    supersedes: Document | None = None
    text: str
    version: int


class GetDomainResponse(_Model):
    """`iohr.accounts.v1.GetDomainResponse`"""

    domain: Domain | None = None


class GetEntitlementsResponse(_Model):
    """`iohr.accounts.v1.GetEntitlementsResponse`"""

    account_id: str
    extensions: list[str]
    features: list[str]
    granted_by: str
    plan: str


class GetEventStatsResponse(_Model):
    """`iohr.events.v1.GetEventStatsResponse`"""

    range: str
    rows: list[EventStatsRow]


class GetExtensionResponse(_Model):
    """`iohr.extensions.v1.GetExtensionResponse`"""

    extension: Extension | None = None


class GetMeResponse(_Model):
    """`iohr.accounts.v1.GetMeResponse`"""

    account: Account | None = None
    email: str
    email_verified: bool
    key: AccountsKey | None = None
    name: str
    stub: bool
    subject: str
    teams: list[Account]
    user_id: str


class GetMonitorResponse(_Model):
    """`iohr.connections.v1.GetMonitorResponse`"""

    monitor: Monitor | None = None


class GetMonitorSeriesResponse(_Model):
    """`iohr.connections.v1.GetMonitorSeriesResponse`"""

    bucket_secs: int
    buckets: list[MonitorBucket]
    failed: int
    failures: list[MonitorFailureClass]
    from_: str = _Field(alias="from")
    p50: int | None = None
    p95: int | None = None
    p99: int | None = None
    runs: int
    to: str
    uptime: float | None = None


class GetMonitorSummaryResponse(_Model):
    """`iohr.connections.v1.GetMonitorSummaryResponse`"""

    health: str
    last_failure: MonitorRun | None = None
    latency_ms: Latency | None = None
    since: str
    state: str
    uptime: Uptime | None = None


class GetPublicDiagramResponse(_Model):
    """`iohr.decisions.v1.GetPublicDiagramResponse`"""

    diagram: Diagram | None = None
    model: str
    svg: str
    version: int


class GetPublicDocumentResponse(_Model):
    """`iohr.decisions.v1.GetPublicDocumentResponse`"""

    children: list[Document]
    document: Document | None = None
    measured_by: list[Document]
    measures: Document | None = None
    mentioned_in: list[Document]
    mentions: list[Document]
    message: str
    parent: Document | None = None
    saved_at: str
    space: SpaceRef | None = None
    successors: list[Document]
    supersedes: Document | None = None
    text: str
    version: int


class GetPublisherResponse(_Model):
    """`iohr.extensions.v1.GetPublisherResponse`"""

    listings: int
    publisher: Publisher | None = None


class GetRecordingResponse(_Model):
    """`iohr.trails.v1.GetRecordingResponse`"""

    recording: Recording | None = None


class GetSettingsResponse(_Model):
    """`iohr.decisions.v1.GetSettingsResponse`"""

    settings: Settings | None = None


class GetSpaceResponse(_Model):
    """`iohr.decisions.v1.GetSpaceResponse`"""

    space: Space | None = None


class GetUnitSeriesResponse(_Model):
    """`iohr.accounts.v1.GetUnitSeriesResponse`"""

    by: str
    from_: str = _Field(alias="from")
    groups: list[UnitSeriesGroup]
    rows: list[UnitSeriesRow]
    to: str


class GetUnitsResponse(_Model):
    """`iohr.accounts.v1.GetUnitsResponse`"""

    account_id: str
    allowance: Int64
    days: list[UnitDay]
    granted: Int64
    month: str
    plan: Plan | None = None
    remaining: Int64
    resets_at: str
    usage: list[UnitUsage]
    used: Int64


class GetUsageResponse(_Model):
    """`iohr.accounts.v1.GetUsageResponse`"""

    plan: str
    rows: list[UsageRow]


class Grant(_Model):
    """`iohr.connections.v1.Grant`"""

    actions: list[str]
    connection_id: str
    consumer: Consumer | None = None
    created_at: str
    created_by: str
    expires_at: str
    id: str
    revoked_at: str
    status: str


class Inbox(_Model):
    """`iohr.events.v1.Inbox`"""

    created_at: str
    expires_at: str
    id: str
    url: str


class InboxRequest(_Model):
    """`iohr.events.v1.InboxRequest`"""

    body: str
    content_type: str
    endpoint_id: str
    headers: dict[str, str]
    id: str
    method: str
    received_at: str
    signature: str
    size: int


class Invariant(_Model):
    """`iohr.agents.v1.Invariant`"""

    expected: str
    name: str
    path: str
    status: str


class Item(_Model):
    """`iohr.radar.v1.Item`"""

    id: Int64
    language: str
    published_at: str
    source: str
    summary: str
    title: str
    url: str


class JobResult(_Model):
    """`iohr.agents.v1.JobResult`"""

    detail: CheckDetail | None = None
    finished_at: str
    job_id: str
    refusal: Refusal | None = None
    started_at: str
    status: str


class Key(_Model):
    """The key claims, as `OpenAPI` sees them."""

    id: str
    """Key id."""
    parent: str | None = None
    """The parent key, for a sub-key."""


class Kind(_Model):
    """`iohr.connections.v1.Kind`"""

    actions: list[KindAction]
    auth: str
    config: list[Field]
    description: str
    executors: list[str]
    name: str
    test_action: str
    title: str


class KindAction(_Model):
    """`iohr.connections.v1.KindAction`"""

    class_: str = _Field(alias="class")
    description: str
    executors: list[str]
    name: str
    params: list[Field]
    reads_private: bool
    reads_untrusted: bool
    schema_: str = _Field(alias="schema")
    sends_out: bool


class Latency(_Model):
    """`iohr.connections.v1.Latency`"""

    p50: int | None = None
    p95: int | None = None


class ListAccountHistoryResponse(_Model):
    """`iohr.connections.v1.ListAccountHistoryResponse`"""

    next_page_token: str
    uses: list[Use]


class ListAgentsResponse(_Model):
    """`iohr.agents.v1.ListAgentsResponse`"""

    agents: list[Agent]
    next_page_token: str


class ListCommentsResponse(_Model):
    """`iohr.decisions.v1.ListCommentsResponse`"""

    comments: list[Comment]
    next_page_token: str


class ListConnectionsResponse(_Model):
    """`iohr.connections.v1.ListConnectionsResponse`"""

    connections: list[Connection]
    next_page_token: str


class ListConnectorsResponse(_Model):
    """`iohr.connections.v1.ListConnectorsResponse`"""

    connectors: list[Connector]
    next_page_token: str


class ListDeliveriesResponse(_Model):
    """`iohr.events.v1.ListDeliveriesResponse`"""

    deliveries: list[Delivery]
    next_page_token: str


class ListDiagramVersionsResponse(_Model):
    """`iohr.decisions.v1.ListDiagramVersionsResponse`"""

    next_page_token: str
    versions: list[DiagramVersion]


class ListDiagramsResponse(_Model):
    """`iohr.decisions.v1.ListDiagramsResponse`"""

    diagrams: list[Diagram]
    next_page_token: str


class ListDigestsResponse(_Model):
    """`iohr.radar.v1.ListDigestsResponse`"""

    digests: list[Digest]
    next_page_token: str


class ListDocumentsResponse(_Model):
    """`iohr.decisions.v1.ListDocumentsResponse`"""

    documents: list[Document]
    next_page_token: str


class ListDomainsResponse(_Model):
    """`iohr.accounts.v1.ListDomainsResponse`"""

    domains: list[Domain]
    next_page_token: str
    total_size: int


class ListEndpointsResponse(_Model):
    """`iohr.events.v1.ListEndpointsResponse`"""

    endpoints: list[Endpoint]
    next_page_token: str


class ListEventTypesResponse(_Model):
    """`iohr.events.v1.ListEventTypesResponse`"""

    next_page_token: str
    types: list[EventType]


class ListExtensionsResponse(_Model):
    """`iohr.extensions.v1.ListExtensionsResponse`"""

    extensions: list[Extension]
    next_page_token: str


class ListGrantsResponse(_Model):
    """`iohr.connections.v1.ListGrantsResponse`"""

    grants: list[Grant]
    next_page_token: str


class ListHistoryResponse(_Model):
    """`iohr.connections.v1.ListHistoryResponse`"""

    next_page_token: str
    uses: list[Use]


class ListInboxRequestsResponse(_Model):
    """`iohr.events.v1.ListInboxRequestsResponse`"""

    inbox: Inbox | None = None
    next_page_token: str
    requests: list[InboxRequest]


class ListInboxesResponse(_Model):
    """`iohr.events.v1.ListInboxesResponse`"""

    inboxes: list[Inbox]
    next_page_token: str


class ListItemsResponse(_Model):
    """`iohr.radar.v1.ListItemsResponse`"""

    items: list[Item]
    next_page_token: str


class ListKindsResponse(_Model):
    """`iohr.connections.v1.ListKindsResponse`"""

    kinds: list[Kind]
    next_page_token: str


class ListMonitorRunsResponse(_Model):
    """`iohr.connections.v1.ListMonitorRunsResponse`"""

    next_page_token: str
    runs: list[MonitorRun]


class ListMonitorsResponse(_Model):
    """`iohr.connections.v1.ListMonitorsResponse`"""

    monitors: list[Monitor]
    next_page_token: str


class ListNotificationsResponse(_Model):
    """`iohr.events.v1.ListNotificationsResponse`"""

    next_page_token: str
    notifications: list[Notification]
    unread: int


class ListPublicDocumentsResponse(_Model):
    """`iohr.decisions.v1.ListPublicDocumentsResponse`"""

    documents: list[Document]
    next_page_token: str
    spaces: list[SpaceRef]


class ListRecordingsResponse(_Model):
    """`iohr.trails.v1.ListRecordingsResponse`"""

    next_page_token: str
    recordings: list[Recording]


class ListRequestsResponse(_Model):
    """`iohr.accounts.v1.ListRequestsResponse`"""

    next_page_token: str
    requests: list[RequestEntry]


class ListReviewQueueResponse(_Model):
    """`iohr.decisions.v1.ListReviewQueueResponse`"""

    next_page_token: str
    reviews: list[Review]


class ListReviewsResponse(_Model):
    """`iohr.decisions.v1.ListReviewsResponse`"""

    approvals: int
    approvals_required: int
    counted_from_version: int
    current_version: int
    next_page_token: str
    reviews: list[Review]


class ListSpacesResponse(_Model):
    """`iohr.decisions.v1.ListSpacesResponse`"""

    next_page_token: str
    spaces: list[Space]


class ListTeamEventsResponse(_Model):
    """`iohr.accounts.v1.ListTeamEventsResponse`"""

    events: list[TeamEvent]
    next_page_token: str


class ListTimelineResponse(_Model):
    """`iohr.decisions.v1.ListTimelineResponse`"""

    entries: list[TimelineEntry]
    next_page_token: str


class ListToolsResponse(_Model):
    """`iohr.connections.v1.ListToolsResponse`"""

    next_page_token: str
    tools: list[ToolInfo]


class ListUnitCategoriesResponse(_Model):
    """`iohr.accounts.v1.ListUnitCategoriesResponse`"""

    categories: list[UnitCategory]
    next_page_token: str


class ListValue(_Model):
    """`google.protobuf.ListValue`"""

    values: list[Value] | None = None


class Me(_Model):
    """`GET /v1/me` body."""

    client_id: str | None = None
    """The OAuth client the call came through, if any."""
    email: str | None = None
    """E-mail address, when the token carries one (a person's ID token does)."""
    key: Key | None = None
    kind: str
    """`person`, `client` or `service`."""
    name: str | None = None
    """Display name, when the token carries one."""
    org: str | None = None
    """Organisation, when minted."""
    role: str | None = None
    """Role, when the consent step stamped one."""
    scopes: list[str]
    """Granted scopes."""
    subject: str
    """The `sub` claim."""


class Monitor(_Model):
    """`iohr.connections.v1.Monitor`"""

    agent_id: str
    category: str
    check: DeclaredCheck | None = None
    connection_id: str
    created_at: str
    executor: Executor | None = None
    fail_after: int
    health: str
    interval_secs: int
    last_run_at: str
    managed_by: str
    monitor_id: str
    name: str
    next_run_at: str
    params: MonitorParams | None = None
    paused_reason: str
    rfc: str
    slo_target: float | None = None
    state: str
    tags: dict[str, str]


class MonitorBucket(_Model):
    """`iohr.connections.v1.MonitorBucket`"""

    failed: int
    p50: int | None = None
    p95: int | None = None
    p99: int | None = None
    passed: int
    runs: int
    seen: int
    start: str
    uptime: float | None = None


class MonitorFailureClass(_Model):
    """`iohr.connections.v1.MonitorFailureClass`"""

    count: int
    error_class: str
    last_at: str
    last_run_id: str


class MonitorParams(_Model):
    """`iohr.connections.v1.MonitorParams`"""

    expect_status: int | None = None
    max_ms: int | None = None
    path: str | None = None


class MonitorRun(_Model):
    """`iohr.connections.v1.MonitorRun`"""

    at: str
    error_class: str | None = None
    failure: str
    invariant: str
    latency_ms: int
    ok: bool
    run_id: str
    status: str
    status_code: int | None = None


class MonitorTags(_Model):
    """`iohr.connections.v1.MonitorTags`"""

    values: dict[str, str] | None = None


class Notification(_Model):
    """`iohr.events.v1.Notification`"""

    data: dict[str, str]
    id: str
    occurred_at: str
    read: bool
    type: str


class Pattern(_Model):
    """`iohr.decisions.v1.Pattern`"""

    id: str | None = None
    re: str | None = None
    why: str | None = None


class Plan(_Model):
    """`iohr.accounts.v1.Plan`"""

    accounts: Int64
    at_zero: str
    description: str
    monthly_units: Int64
    name: str
    updated_at: str


class Problem(_Model):
    """`{"code","error","details","request_id"}`: the REST body and the SSE `error` payload."""

    code: Code
    """The slug."""
    details: list[Detail]
    """Typed details."""
    error: str
    """The sentence."""
    request_id: str
    """The request's id, the `x-request-id` the answer carries: name it when asking about a call. Empty on a socket or MQTT frame, whose own id names the call."""


class Publisher(_Model):
    """`iohr.extensions.v1.Publisher`"""

    account_id: str
    created_at: str
    display_name: str
    domain: str
    first_party: bool
    namespace: str


class Quote(_Model):
    """`iohr.decisions.v1.Quote`"""

    exact: str | None = None
    prefix: str | None = None
    start: int | None = None
    suffix: str | None = None


class Recording(_Model):
    """`iohr.trails.v1.Recording`"""

    account_id: str
    bytes: int
    client: str
    created_at: str
    created_by: str
    dropped: int
    duration_ms: int
    event_count: int
    events: list[Struct]
    pages: int
    recording_id: str
    rejected: int
    site: str
    started_at: str


class RecoverEndpointRequest(_Model):
    """`iohr.events.v1.RecoverEndpointRequest`"""

    endpoint_id: str | None = None
    since: str | None = None


class RecoverEndpointResponse(_Model):
    """`iohr.events.v1.RecoverEndpointResponse`"""

    created: int
    retried: int
    truncated: bool


class Redaction(_Model):
    """`iohr.decisions.v1.Redaction`"""

    domains: list[str] | None = None
    patterns: list[Pattern] | None = None
    words: list[str] | None = None


class Refusal(_Model):
    """`iohr.agents.v1.Refusal`"""

    reason: str


class RejectedCheck(_Model):
    """`iohr.agents.v1.RejectedCheck`"""

    key: str
    reason: str


class RemoveDomainResponse(_Model):
    """`iohr.accounts.v1.RemoveDomainResponse`"""


class RequestEntry(_Model):
    """`iohr.accounts.v1.RequestEntry`"""

    at: str
    code: str
    duration_ms: int
    key_id: str
    key_name: str
    outcome: str
    person_name: str
    request_id: str
    rpc: str


class RequestReviewRequest(_Model):
    """`iohr.decisions.v1.RequestReviewRequest`"""

    document_id: str | None = None
    reviewers: list[str] | None = None
    space_id: str | None = None


class RequestReviewResponse(_Model):
    """`iohr.decisions.v1.RequestReviewResponse`"""

    reviews: list[Review]


class ResolveCommentRequest(_Model):
    """`iohr.decisions.v1.ResolveCommentRequest`"""

    comment_id: str | None = None
    document_id: str | None = None
    resolved: bool | None = None
    space_id: str | None = None


class ResolveCommentResponse(_Model):
    """`iohr.decisions.v1.ResolveCommentResponse`"""

    comment: Comment | None = None


class ResolverAnswer(_Model):
    """`iohr.accounts.v1.ResolverAnswer`"""

    answered: bool
    dnssec: bool
    name: str
    seen: bool
    value: str


class RetryDeliveryResponse(_Model):
    """`iohr.events.v1.RetryDeliveryResponse`"""

    delivery: Delivery | None = None


class Review(_Model):
    """`iohr.decisions.v1.Review`"""

    decided_at: str
    decision: str
    display_number: str
    document_id: str
    kind: str
    number: int
    requested_at: str
    requested_by: str
    review_id: str
    reviewer: str
    space_id: str
    space_name: str
    title: str
    version: int


class RevokeAgentRequest(_Model):
    """`iohr.agents.v1.RevokeAgentRequest`"""

    agent_id: str | None = None
    org_id: str | None = None


class RevokeAgentResponse(_Model):
    """`iohr.agents.v1.RevokeAgentResponse`"""

    agent: Agent | None = None


class RevokeGrantResponse(_Model):
    """`iohr.connections.v1.RevokeGrantResponse`"""

    grant: Grant | None = None


class RotateSecretResponse(_Model):
    """`iohr.events.v1.RotateSecretResponse`"""

    previous_expires_at: str
    secret: str


class RunCheckRequest(_Model):
    """`iohr.agents.v1.RunCheckRequest`"""

    agent_id: str | None = None
    auth: str | None = None
    expect: Expect | None = None
    org_id: str | None = None
    service: str | None = None
    surface: str | None = None
    target: Target | None = None


class RunCheckResponse(_Model):
    """`iohr.agents.v1.RunCheckResponse`"""

    result: JobResult | None = None


class SaveDiagramRequest(_Model):
    """`iohr.decisions.v1.SaveDiagramRequest`"""

    base_version: int | None = None
    diagram_id: str | None = None
    message: str | None = None
    model: str | None = None
    name: str | None = None
    space_id: str | None = None


class SaveDiagramResponse(_Model):
    """`iohr.decisions.v1.SaveDiagramResponse`"""

    diagram: Diagram | None = None
    version: int


class SaveDocumentRequest(_Model):
    """`iohr.decisions.v1.SaveDocumentRequest`"""

    base_version: int | None = None
    document_id: str | None = None
    message: str | None = None
    space_id: str | None = None
    text: str | None = None


class SaveDocumentResponse(_Model):
    """`iohr.decisions.v1.SaveDocumentResponse`"""

    document: Document | None = None
    findings: list[Finding]
    version: int


class SearchDiagramsResponse(_Model):
    """`iohr.decisions.v1.SearchDiagramsResponse`"""

    diagrams: list[Diagram]
    next_page_token: str


class SendTestResponse(_Model):
    """`iohr.events.v1.SendTestResponse`"""

    delivery: Delivery | None = None


class SetAccessRequest(_Model):
    """`iohr.decisions.v1.SetAccessRequest`"""

    access: str | None = None
    document_id: str | None = None
    space_id: str | None = None


class SetAccessResponse(_Model):
    """`iohr.decisions.v1.SetAccessResponse`"""

    document: Document | None = None


class SetOutwardRequest(_Model):
    """`iohr.decisions.v1.SetOutwardRequest`"""

    document_id: str | None = None
    outward: bool | None = None
    space_id: str | None = None


class SetOutwardResponse(_Model):
    """`iohr.decisions.v1.SetOutwardResponse`"""

    document: Document | None = None


class SetSourceRequest(_Model):
    """`iohr.decisions.v1.SetSourceRequest`"""

    document_id: str | None = None
    source: str | None = None
    space_id: str | None = None


class SetSourceResponse(_Model):
    """`iohr.decisions.v1.SetSourceResponse`"""

    document: Document | None = None


class SetStageRequest(_Model):
    """`iohr.decisions.v1.SetStageRequest`"""

    base_version: int | None = None
    document_id: str | None = None
    reason: str | None = None
    space_id: str | None = None
    stage: str | None = None


class SetStageResponse(_Model):
    """`iohr.decisions.v1.SetStageResponse`"""

    document: Document | None = None
    version: int


class SetStatusRequest(_Model):
    """`iohr.decisions.v1.SetStatusRequest`"""

    base_version: int | None = None
    decider: str | None = None
    document_id: str | None = None
    review_by: str | None = None
    space_id: str | None = None
    status: str | None = None
    successor_id: str | None = None


class SetStatusResponse(_Model):
    """`iohr.decisions.v1.SetStatusResponse`"""

    document: Document | None = None


class Settings(_Model):
    """`iohr.decisions.v1.Settings`"""

    approvals_required: int
    redaction: Redaction | None = None
    updated_at: str


class Space(_Model):
    """`iohr.decisions.v1.Space`"""

    account_id: str
    awaiting_review: int
    created_at: str
    description: str
    documents: int
    name: str
    open: int
    slug: str
    space_id: str
    updated_at: str


class SpaceRef(_Model):
    """`iohr.decisions.v1.SpaceRef`"""

    name: str
    slug: str
    space_id: str


class StartConnectRequest(_Model):
    """`iohr.connections.v1.StartConnectRequest`"""

    auth_mode: str | None = None
    config: dict[str, str] | None = None
    connection_id: str | None = None
    connector: str | None = None
    name: str | None = None
    org_id: str | None = None
    scopes: list[str] | None = None


class StartConnectResponse(_Model):
    """`iohr.connections.v1.StartConnectResponse`"""

    authorize_url: str
    expires_at: str
    session_id: str


class StreamEventsResponse(_Model):
    """`iohr.events.v1.StreamEventsResponse`"""

    account_id: str
    data: dict[str, str]
    id: str
    occurred_at: str
    type: str


class Struct(_Model):
    """`google.protobuf.Struct`"""

    fields: dict[str, Value] | None = None


class SubmitReviewRequest(_Model):
    """`iohr.decisions.v1.SubmitReviewRequest`"""

    decision: str | None = None
    document_id: str | None = None
    space_id: str | None = None
    version: int | None = None


class SubmitReviewResponse(_Model):
    """`iohr.decisions.v1.SubmitReviewResponse`"""

    review: Review | None = None


class Target(_Model):
    """`iohr.agents.v1.Target`"""

    host: str | None = None
    port: int | None = None
    tls: bool | None = None
    url: str | None = None


class TeamEvent(_Model):
    """`iohr.accounts.v1.TeamEvent`"""

    action: str
    actor_name: str
    actor_sub: str
    after: str
    at: str
    before: str
    id: str
    subject: str


class TestConnectionResponse(_Model):
    """`iohr.connections.v1.TestConnectionResponse`"""

    result: ActionResult | None = None


class TimelineEntry(_Model):
    """`iohr.decisions.v1.TimelineEntry`"""

    date: str
    display_number: str
    document_id: str
    kind: str
    status: str
    text: str
    title: str


class ToolInfo(_Model):
    """`iohr.connections.v1.ToolInfo`"""

    account_id: str
    action: str
    connection_id: str
    description: str
    name: str
    schema_json_: str = _Field(alias="schema_json")


class UnitCategory(_Model):
    """`iohr.accounts.v1.UnitCategory`"""

    description: str | None = None
    name: str | None = None
    units_per_1k_tokens: Int64 | None = None
    units_per_call: Int64 | None = None
    updated_at: str | None = None


class UnitDay(_Model):
    """`iohr.accounts.v1.UnitDay`"""

    day: str
    units: Int64


class UnitSeriesGroup(_Model):
    """`iohr.accounts.v1.UnitSeriesGroup`"""

    id: str
    label: str
    units: Int64


class UnitSeriesRow(_Model):
    """`iohr.accounts.v1.UnitSeriesRow`"""

    calls: Int64
    client_errors: Int64
    day: str
    group: str
    p50_ms: int
    p95_ms: int
    platform_errors: Int64
    tokens: Int64
    units: Int64


class UnitUsage(_Model):
    """`iohr.accounts.v1.UnitUsage`"""

    calls: Int64
    category: str
    client_errors: Int64
    key_id: str
    key_name: str
    p50_ms: int
    p95_ms: int
    platform_errors: Int64
    rpc: str
    tokens: Int64
    units: Int64
    user_id: str
    user_name: str


class UpdateConnectionRequest(_Model):
    """`iohr.connections.v1.UpdateConnectionRequest`"""

    auth_mode: str | None = None
    config: dict[str, str] | None = None
    connection_id: str | None = None
    credentials: dict[str, str] | None = None
    description: str | None = None
    name: str | None = None
    org_id: str | None = None
    paused: bool | None = None
    rotate_webhook_secret: bool | None = None
    secret: str | None = None
    secret_ref: str | None = None


class UpdateConnectionResponse(_Model):
    """`iohr.connections.v1.UpdateConnectionResponse`"""

    connection: Connection | None = None
    webhook_secret: str


class UpdateDiagramRequest(_Model):
    """`iohr.decisions.v1.UpdateDiagramRequest`"""

    diagram_id: str | None = None
    name: str | None = None
    space_id: str | None = None


class UpdateDiagramResponse(_Model):
    """`iohr.decisions.v1.UpdateDiagramResponse`"""

    diagram: Diagram | None = None


class UpdateEndpointRequest(_Model):
    """`iohr.events.v1.UpdateEndpointRequest`"""

    description: str | None = None
    enabled: bool | None = None
    endpoint_id: str | None = None
    event_types: list[str] | None = None
    url: str | None = None


class UpdateMonitorRequest(_Model):
    """`iohr.connections.v1.UpdateMonitorRequest`"""

    category: str | None = None
    fail_after: int | None = None
    interval_secs: int | None = None
    monitor_id: str | None = None
    name: str | None = None
    org_id: str | None = None
    params: MonitorParams | None = None
    rfc: str | None = None
    slo_target: float | None = None
    state: str | None = None
    tags: MonitorTags | None = None


class UpdateMonitorResponse(_Model):
    """`iohr.connections.v1.UpdateMonitorResponse`"""

    monitor: Monitor | None = None


class UpdateSettingsRequest(_Model):
    """`iohr.decisions.v1.UpdateSettingsRequest`"""

    approvals_required: int | None = None
    redaction: Redaction | None = None
    space_id: str | None = None


class UpdateSettingsResponse(_Model):
    """`iohr.decisions.v1.UpdateSettingsResponse`"""

    settings: Settings | None = None


class UpdateSpaceRequest(_Model):
    """`iohr.decisions.v1.UpdateSpaceRequest`"""

    description: str | None = None
    name: str | None = None
    set_description: bool | None = None
    space_id: str | None = None


class UpdateSpaceResponse(_Model):
    """`iohr.decisions.v1.UpdateSpaceResponse`"""

    space: Space | None = None


class UploadRecordingRequest(_Model):
    """`iohr.trails.v1.UploadRecordingRequest`"""

    client: str | None = None
    dropped: int | None = None
    events: list[Struct] | None = None
    site: str | None = None
    started_at: str | None = None


class UploadRecordingResponse(_Model):
    """`iohr.trails.v1.UploadRecordingResponse`"""

    recording: Recording | None = None
    rejected: int


class Uptime(_Model):
    """`iohr.connections.v1.Uptime`"""

    d30: float | None = None
    d7: float | None = None
    h24: float | None = None


class UsageRow(_Model):
    """`iohr.accounts.v1.UsageRow`"""

    amount: Int64
    day: str
    metric: str
    service: str


class Use(_Model):
    """`iohr.connections.v1.Use`"""

    action: str
    at: str
    caller: str
    caller_kind: str
    connection_id: str
    error_class: str
    executor: str
    grant_id: str
    id: str
    input_tokens: int
    latency_ms: int
    output_tokens: int
    status: str
    status_code: int


class Value(_Model):
    """`google.protobuf.Value`"""

    bool_value: bool | None = None
    list_value: ListValue | None = None
    null_value: Literal["NULL_VALUE"] | None = None
    """`google.protobuf.NullValue`"""
    number_value: float | None = None
    string_value: str | None = None
    struct_value: Struct | None = None


class VersionDiff(_Model):
    """`iohr.decisions.v1.VersionDiff`"""

    bookkeeping_only: bool
    from_version: int
    lines: list[DiffLine]
    notes: list[VersionNote]
    sections_added: list[str]
    sections_changed: list[str]
    sections_removed: list[str]
    summary: str
    to_version: int
    truncated: bool
    words_added: int
    words_removed: int


class VersionNote(_Model):
    """`iohr.decisions.v1.VersionNote`"""

    message: str
    version: int


for _model in (
    Account,
    AccountsKey,
    ActionResult,
    AddCommentRequest,
    AddCommentResponse,
    AddDomainRequest,
    AddDomainResponse,
    Agent,
    AgentChecks,
    AppendStatusRequest,
    AppendStatusResponse,
    AuthMode,
    CallActionRequest,
    CallActionResponse,
    CallToolRequest,
    CallToolResponse,
    Change,
    CheckDetail,
    CheckDomainRequest,
    CheckDomainResponse,
    ClientSetup,
    ClientSnippet,
    Comment,
    CompleteConnectRequest,
    CompleteConnectResponse,
    ConfirmDomainRequest,
    ConfirmDomainResponse,
    Connection,
    Connector,
    ConnectorAction,
    ConnectorField,
    ConnectorTrigger,
    Consumer,
    CreateConnectionRequest,
    CreateConnectionResponse,
    CreateDiagramRequest,
    CreateDiagramResponse,
    CreateDocumentRequest,
    CreateDocumentResponse,
    CreateEndpointRequest,
    CreateEndpointResponse,
    CreateEnrollmentRequest,
    CreateEnrollmentResponse,
    CreateInboxRequest,
    CreateInboxResponse,
    CreateMonitorRequest,
    CreateMonitorResponse,
    CreateSpaceRequest,
    CreateSpaceResponse,
    Credential,
    DecisionsListVersionsResponse,
    DecisionsVersion,
    DeclaredCheck,
    DeclaredExpect,
    DeclaredTarget,
    DeleteAgentResponse,
    DeleteConnectionResponse,
    DeleteDiagramResponse,
    DeleteEndpointResponse,
    DeleteInboxResponse,
    DeleteMonitorResponse,
    DeleteRecordingResponse,
    DeleteSpaceResponse,
    Delivery,
    DeliveryErrorCount,
    DeliveryStatsBucket,
    DeliveryTypeCount,
    Diagram,
    DiagramUse,
    DiagramVersion,
    DiffLine,
    Digest,
    Document,
    Domain,
    DrillCode,
    Endpoint,
    EventStatsRow,
    EventType,
    Evidence,
    Example,
    Executor,
    Expect,
    ExportFile,
    ExportSpaceResponse,
    Extension,
    ExtensionsListVersionsResponse,
    ExtensionsVersion,
    Field,
    Finding,
    GetAgentResponse,
    GetConnectSessionResponse,
    GetConnectionResponse,
    GetConnectorResponse,
    GetDeliveryStatsResponse,
    GetDiagramResponse,
    GetDigestResponse,
    GetDocumentResponse,
    GetDomainResponse,
    GetEntitlementsResponse,
    GetEventStatsResponse,
    GetExtensionResponse,
    GetMeResponse,
    GetMonitorResponse,
    GetMonitorSeriesResponse,
    GetMonitorSummaryResponse,
    GetPublicDiagramResponse,
    GetPublicDocumentResponse,
    GetPublisherResponse,
    GetRecordingResponse,
    GetSettingsResponse,
    GetSpaceResponse,
    GetUnitSeriesResponse,
    GetUnitsResponse,
    GetUsageResponse,
    Grant,
    Inbox,
    InboxRequest,
    Invariant,
    Item,
    JobResult,
    Key,
    Kind,
    KindAction,
    Latency,
    ListAccountHistoryResponse,
    ListAgentsResponse,
    ListCommentsResponse,
    ListConnectionsResponse,
    ListConnectorsResponse,
    ListDeliveriesResponse,
    ListDiagramVersionsResponse,
    ListDiagramsResponse,
    ListDigestsResponse,
    ListDocumentsResponse,
    ListDomainsResponse,
    ListEndpointsResponse,
    ListEventTypesResponse,
    ListExtensionsResponse,
    ListGrantsResponse,
    ListHistoryResponse,
    ListInboxRequestsResponse,
    ListInboxesResponse,
    ListItemsResponse,
    ListKindsResponse,
    ListMonitorRunsResponse,
    ListMonitorsResponse,
    ListNotificationsResponse,
    ListPublicDocumentsResponse,
    ListRecordingsResponse,
    ListRequestsResponse,
    ListReviewQueueResponse,
    ListReviewsResponse,
    ListSpacesResponse,
    ListTeamEventsResponse,
    ListTimelineResponse,
    ListToolsResponse,
    ListUnitCategoriesResponse,
    ListValue,
    Me,
    Monitor,
    MonitorBucket,
    MonitorFailureClass,
    MonitorParams,
    MonitorRun,
    MonitorTags,
    Notification,
    Pattern,
    Plan,
    Problem,
    Publisher,
    Quote,
    Recording,
    RecoverEndpointRequest,
    RecoverEndpointResponse,
    Redaction,
    Refusal,
    RejectedCheck,
    RemoveDomainResponse,
    RequestEntry,
    RequestReviewRequest,
    RequestReviewResponse,
    ResolveCommentRequest,
    ResolveCommentResponse,
    ResolverAnswer,
    RetryDeliveryResponse,
    Review,
    RevokeAgentRequest,
    RevokeAgentResponse,
    RevokeGrantResponse,
    RotateSecretResponse,
    RunCheckRequest,
    RunCheckResponse,
    SaveDiagramRequest,
    SaveDiagramResponse,
    SaveDocumentRequest,
    SaveDocumentResponse,
    SearchDiagramsResponse,
    SendTestResponse,
    SetAccessRequest,
    SetAccessResponse,
    SetOutwardRequest,
    SetOutwardResponse,
    SetSourceRequest,
    SetSourceResponse,
    SetStageRequest,
    SetStageResponse,
    SetStatusRequest,
    SetStatusResponse,
    Settings,
    Space,
    SpaceRef,
    StartConnectRequest,
    StartConnectResponse,
    StreamEventsResponse,
    Struct,
    SubmitReviewRequest,
    SubmitReviewResponse,
    Target,
    TeamEvent,
    TestConnectionResponse,
    TimelineEntry,
    ToolInfo,
    UnitCategory,
    UnitDay,
    UnitSeriesGroup,
    UnitSeriesRow,
    UnitUsage,
    UpdateConnectionRequest,
    UpdateConnectionResponse,
    UpdateDiagramRequest,
    UpdateDiagramResponse,
    UpdateEndpointRequest,
    UpdateMonitorRequest,
    UpdateMonitorResponse,
    UpdateSettingsRequest,
    UpdateSettingsResponse,
    UpdateSpaceRequest,
    UpdateSpaceResponse,
    UploadRecordingRequest,
    UploadRecordingResponse,
    Uptime,
    UsageRow,
    Use,
    Value,
    VersionDiff,
    VersionNote,
):
    _model.model_rebuild()
