# Generated by iohr sdk generate for cuts public=sha256:43c8985d109bc2ca597c47125896c58fd6bbd949727f605821a53f857ddc46ce; do not edit.
"""The models of the InOrbit API this surface was generated from."""

from __future__ import annotations

from typing import Literal

from pydantic import (
    BaseModel,
    ConfigDict,
)
from pydantic import Field as _Field

from ..runtime import (
    Code,
    Detail,
    Int64,
)


class _Model(BaseModel):
    """Fields this version does not know are kept; wire names are accepted too."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)


class Account(_Model):
    """`iohr.accounts.v1.Account`"""

    created_at: str
    erase_after: str
    id: str
    kind: str
    name: str
    plan: str
    role: str
    slug: str
    status: str


class AccountsKey(_Model):
    """`iohr.accounts.v1.Key`"""

    client_id: str
    created_at: str
    created_by: str
    expires_at: str
    id: str
    kind: str
    last_used_at: str
    name: str
    revoked_at: str
    scopes: list[str]
    secret_hint: str


class ActionResult(_Model):
    """`iohr.connections.v1.ActionResult`"""

    error_class: str
    executor: str
    latency_ms: int
    message: str
    ok: bool
    output: Struct | None = None
    started_at: str
    status: str
    status_code: int
    use_id: str


class AddDomainRequest(_Model):
    """`iohr.accounts.v1.AddDomainRequest`"""

    domain: str
    org_id: str
    scope: str


class AddDomainResponse(_Model):
    """`iohr.accounts.v1.AddDomainResponse`"""

    domain: Domain | None = None


class Agent(_Model):
    """`iohr.agents.v1.Agent`"""

    agent_id: str
    arch: str
    domains: list[str]
    enrolled_at: str
    environment: str
    last_seen_at: str
    name: str
    os: str
    policy_hash: str
    revoked_at: str
    status: str
    version: str


class CallActionRequest(_Model):
    """`iohr.connections.v1.CallActionRequest`"""

    action: str
    connection_id: str
    org_id: str
    params: Struct | None = None


class CallActionResponse(_Model):
    """`iohr.connections.v1.CallActionResponse`"""

    result: ActionResult | None = None


class CallToolRequest(_Model):
    """`iohr.connections.v1.CallToolRequest`"""

    args_json: str
    name: str


class CallToolResponse(_Model):
    """`iohr.connections.v1.CallToolResponse`"""

    ms: Int64
    ok: bool
    result_json: str
    tool: str


class Change(_Model):
    """`iohr.radar.v1.Change`"""

    advanced: str
    after: str
    area: str
    example: Example | None = None
    impact: Literal["IMPACT_UNSPECIFIED", "IMPACT_BREAKING", "IMPACT_WORTH_KNOWING", "IMPACT_NICE_TO_KNOW"]
    """`iohr.radar.v1.Impact`"""
    novice: str
    practitioner: str
    production_impact: str
    title: str
    try_it: str
    url: str
    what: str


class CheckDetail(_Model):
    """`iohr.agents.v1.CheckDetail`"""

    error_class: str
    latency_ms: int
    ok: bool
    status_code: int
    tls_expires_at: str


class CheckDomainRequest(_Model):
    """`iohr.accounts.v1.CheckDomainRequest`"""

    domain: str
    org_id: str


class CheckDomainResponse(_Model):
    """`iohr.accounts.v1.CheckDomainResponse`"""

    domain: Domain | None = None
    resolvers: list[ResolverAnswer]
    status: str


class ConfirmDomainRequest(_Model):
    """`iohr.accounts.v1.ConfirmDomainRequest`"""

    domain: str
    org_id: str


class ConfirmDomainResponse(_Model):
    """`iohr.accounts.v1.ConfirmDomainResponse`"""

    domain: Domain | None = None


class Connection(_Model):
    """`iohr.connections.v1.Connection`"""

    account_id: str
    config: dict[str, str]
    created_at: str
    credential: Credential | None = None
    description: str
    executor: Executor | None = None
    grants: int
    id: str
    kind: str
    last_test_at: str
    last_test_error: str
    last_test_ok: bool
    name: str
    receive_url: str
    status: str
    updated_at: str


class Consumer(_Model):
    """`iohr.connections.v1.Consumer`"""

    id: str
    kind: str


class CreateConnectionRequest(_Model):
    """`iohr.connections.v1.CreateConnectionRequest`"""

    config: dict[str, str]
    description: str
    executor: Executor | None = None
    kind: str
    name: str
    org_id: str
    secret: str
    secret_ref: str


class CreateConnectionResponse(_Model):
    """`iohr.connections.v1.CreateConnectionResponse`"""

    connection: Connection | None = None
    webhook_secret: str


class CreateEndpointRequest(_Model):
    """`iohr.events.v1.CreateEndpointRequest`"""

    account_id: str
    description: str
    event_types: list[str]
    url: str


class CreateEndpointResponse(_Model):
    """`iohr.events.v1.CreateEndpointResponse`"""

    endpoint: Endpoint | None = None
    secret: str


class CreateEnrollmentRequest(_Model):
    """`iohr.agents.v1.CreateEnrollmentRequest`"""

    domains: list[str]
    environment: str
    name: str
    org_id: str


class CreateEnrollmentResponse(_Model):
    """`iohr.agents.v1.CreateEnrollmentResponse`"""

    enrollment_id: str
    expires_at: str
    token: str


class CreateInboxRequest(_Model):
    """`iohr.events.v1.CreateInboxRequest`"""

    account_id: str


class CreateInboxResponse(_Model):
    """`iohr.events.v1.CreateInboxResponse`"""

    inbox: Inbox | None = None


class CreateMonitorRequest(_Model):
    """`iohr.connections.v1.CreateMonitorRequest`"""

    connection_id: str
    fail_after: int
    interval_secs: int
    name: str
    org_id: str
    params: MonitorParams | None = None


class CreateMonitorResponse(_Model):
    """`iohr.connections.v1.CreateMonitorResponse`"""

    monitor: Monitor | None = None


class Credential(_Model):
    """`iohr.connections.v1.Credential`"""

    kind: str
    reference: str
    set_at: str


class DeleteAgentResponse(_Model):
    """`iohr.agents.v1.DeleteAgentResponse`"""


class DeleteConnectionResponse(_Model):
    """`iohr.connections.v1.DeleteConnectionResponse`"""


class DeleteEndpointResponse(_Model):
    """`iohr.events.v1.DeleteEndpointResponse`"""


class DeleteInboxResponse(_Model):
    """`iohr.events.v1.DeleteInboxResponse`"""


class DeleteMonitorResponse(_Model):
    """`iohr.connections.v1.DeleteMonitorResponse`"""


class Delivery(_Model):
    """`iohr.events.v1.Delivery`"""

    attempts: int
    created_at: str
    endpoint_id: str
    event_id: str
    event_type: str
    id: str
    last_error: str
    last_latency_ms: int
    last_status_code: int
    next_attempt_at: str
    status: str
    updated_at: str


class DeliveryErrorCount(_Model):
    """`iohr.events.v1.DeliveryErrorCount`"""

    count: Int64
    error: str
    last_at: str
    status_code: int


class DeliveryStatsBucket(_Model):
    """`iohr.events.v1.DeliveryStatsBucket`"""

    failed: Int64
    p50_ms: int
    p95_ms: int
    start: str
    succeeded: Int64


class DeliveryTypeCount(_Model):
    """`iohr.events.v1.DeliveryTypeCount`"""

    failed: Int64
    succeeded: Int64
    type: str


class Digest(_Model):
    """`iohr.radar.v1.Digest`"""

    ai_written: bool
    changed: str
    changes: list[Change]
    checked: bool
    created_at: str
    drill: str
    drill_code: DrillCode | None = None
    id: Int64
    item_count: int
    lang: str
    language: str
    model: str
    origin: str
    published_at: str
    script: str
    status: str
    stub: bool
    summary: str
    week: str
    why: str


class Domain(_Model):
    """`iohr.accounts.v1.Domain`"""

    created_at: str
    dns_provider: str
    domain: str
    expires_at: str
    last_checked_at: str
    record_name: str
    record_value: str
    scope: str
    status: str
    unverified_reason: str
    verified_at: str


class DrillCode(_Model):
    """`iohr.radar.v1.DrillCode`"""

    output: str
    solution: str
    starter: str
    stub: bool
    tests: str
    toolchain: str


class Endpoint(_Model):
    """`iohr.events.v1.Endpoint`"""

    created_at: str
    description: str
    disabled_reason: str
    enabled: bool
    event_types: list[str]
    failed_24h: int
    id: str
    last_delivery_at: str
    last_delivery_status: str
    secret_rotated_at: str
    succeeded_24h: int
    url: str


class EventStatsRow(_Model):
    """`iohr.events.v1.EventStatsRow`"""

    count: Int64
    day: str
    type: str


class EventType(_Model):
    """`iohr.events.v1.EventType`"""

    description: str
    schema_: str = _Field(alias="schema")
    type: str


class Example(_Model):
    """`iohr.radar.v1.Example`"""

    source: str
    stderr: str
    stdout: str
    stub: bool
    tests: str
    toolchain: str


class Executor(_Model):
    """`iohr.connections.v1.Executor`"""

    agent_id: str
    kind: str


class Expect(_Model):
    """`iohr.agents.v1.Expect`"""

    max_ms: int
    status: int


class Field(_Model):
    """`iohr.connections.v1.Field`"""

    choices: list[str]
    default_value: str
    description: str
    max: Int64
    min: Int64
    name: str
    required: bool
    type: str


class GetAgentResponse(_Model):
    """`iohr.agents.v1.GetAgentResponse`"""

    agent: Agent | None = None


class GetConnectionResponse(_Model):
    """`iohr.connections.v1.GetConnectionResponse`"""

    connection: Connection | None = None


class GetDeliveryStatsResponse(_Model):
    """`iohr.events.v1.GetDeliveryStatsResponse`"""

    bucket: str
    buckets: list[DeliveryStatsBucket]
    errors: list[DeliveryErrorCount]
    failed: Int64
    in_flight: Int64
    p50_ms: int
    p95_ms: int
    range: str
    succeeded: Int64
    types: list[DeliveryTypeCount]


class GetDigestResponse(_Model):
    """`iohr.radar.v1.GetDigestResponse`"""

    digest: Digest | None = None


class GetDomainResponse(_Model):
    """`iohr.accounts.v1.GetDomainResponse`"""

    domain: Domain | None = None


class GetEventStatsResponse(_Model):
    """`iohr.events.v1.GetEventStatsResponse`"""

    range: str
    rows: list[EventStatsRow]


class GetMeResponse(_Model):
    """`iohr.accounts.v1.GetMeResponse`"""

    account: Account | None = None
    email: str
    email_verified: bool
    key: AccountsKey | None = None
    name: str
    stub: bool
    subject: str
    teams: list[Account]
    user_id: str


class GetMonitorResponse(_Model):
    """`iohr.connections.v1.GetMonitorResponse`"""

    monitor: Monitor | None = None


class GetMonitorSummaryResponse(_Model):
    """`iohr.connections.v1.GetMonitorSummaryResponse`"""

    health: str
    last_failure: MonitorRun | None = None
    latency_ms: Latency | None = None
    since: str
    state: str
    uptime: Uptime | None = None


class GetUnitSeriesResponse(_Model):
    """`iohr.accounts.v1.GetUnitSeriesResponse`"""

    by: str
    from_: str = _Field(alias="from")
    groups: list[UnitSeriesGroup]
    rows: list[UnitSeriesRow]
    to: str


class GetUnitsResponse(_Model):
    """`iohr.accounts.v1.GetUnitsResponse`"""

    account_id: str
    allowance: Int64
    days: list[UnitDay]
    granted: Int64
    month: str
    plan: Plan | None = None
    remaining: Int64
    resets_at: str
    usage: list[UnitUsage]
    used: Int64


class GetUsageResponse(_Model):
    """`iohr.accounts.v1.GetUsageResponse`"""

    plan: str
    rows: list[UsageRow]


class Grant(_Model):
    """`iohr.connections.v1.Grant`"""

    actions: list[str]
    connection_id: str
    consumer: Consumer | None = None
    created_at: str
    created_by: str
    expires_at: str
    id: str
    revoked_at: str
    status: str


class Inbox(_Model):
    """`iohr.events.v1.Inbox`"""

    created_at: str
    expires_at: str
    id: str
    url: str


class InboxRequest(_Model):
    """`iohr.events.v1.InboxRequest`"""

    body: str
    content_type: str
    endpoint_id: str
    headers: dict[str, str]
    id: str
    method: str
    received_at: str
    signature: str
    size: int


class Item(_Model):
    """`iohr.radar.v1.Item`"""

    id: Int64
    language: str
    published_at: str
    source: str
    summary: str
    title: str
    url: str


class JobResult(_Model):
    """`iohr.agents.v1.JobResult`"""

    detail: CheckDetail | None = None
    finished_at: str
    job_id: str
    refusal: Refusal | None = None
    started_at: str
    status: str


class Key(_Model):
    """The key claims, as `OpenAPI` sees them."""

    id: str
    """Key id."""
    parent: str | None = None
    """The parent key, for a sub-key."""


class Kind(_Model):
    """`iohr.connections.v1.Kind`"""

    actions: list[KindAction]
    auth: str
    config: list[Field]
    description: str
    executors: list[str]
    name: str
    test_action: str
    title: str


class KindAction(_Model):
    """`iohr.connections.v1.KindAction`"""

    class_: str = _Field(alias="class")
    description: str
    executors: list[str]
    name: str
    params: list[Field]
    reads_private: bool
    reads_untrusted: bool
    schema_: str = _Field(alias="schema")
    sends_out: bool


class Latency(_Model):
    """`iohr.connections.v1.Latency`"""

    p50: int
    p95: int


class ListAgentsResponse(_Model):
    """`iohr.agents.v1.ListAgentsResponse`"""

    agents: list[Agent]
    next_page_token: str


class ListConnectionsResponse(_Model):
    """`iohr.connections.v1.ListConnectionsResponse`"""

    connections: list[Connection]
    next_page_token: str


class ListDeliveriesResponse(_Model):
    """`iohr.events.v1.ListDeliveriesResponse`"""

    deliveries: list[Delivery]
    next_page_token: str


class ListDigestsResponse(_Model):
    """`iohr.radar.v1.ListDigestsResponse`"""

    digests: list[Digest]
    next_page_token: str


class ListDomainsResponse(_Model):
    """`iohr.accounts.v1.ListDomainsResponse`"""

    domains: list[Domain]
    next_page_token: str
    total_size: int


class ListEndpointsResponse(_Model):
    """`iohr.events.v1.ListEndpointsResponse`"""

    endpoints: list[Endpoint]
    next_page_token: str


class ListEventTypesResponse(_Model):
    """`iohr.events.v1.ListEventTypesResponse`"""

    next_page_token: str
    types: list[EventType]


class ListGrantsResponse(_Model):
    """`iohr.connections.v1.ListGrantsResponse`"""

    grants: list[Grant]
    next_page_token: str


class ListHistoryResponse(_Model):
    """`iohr.connections.v1.ListHistoryResponse`"""

    next_page_token: str
    uses: list[Use]


class ListInboxRequestsResponse(_Model):
    """`iohr.events.v1.ListInboxRequestsResponse`"""

    inbox: Inbox | None = None
    next_page_token: str
    requests: list[InboxRequest]


class ListInboxesResponse(_Model):
    """`iohr.events.v1.ListInboxesResponse`"""

    inboxes: list[Inbox]
    next_page_token: str


class ListItemsResponse(_Model):
    """`iohr.radar.v1.ListItemsResponse`"""

    items: list[Item]
    next_page_token: str


class ListKindsResponse(_Model):
    """`iohr.connections.v1.ListKindsResponse`"""

    kinds: list[Kind]
    next_page_token: str


class ListMonitorRunsResponse(_Model):
    """`iohr.connections.v1.ListMonitorRunsResponse`"""

    next_page_token: str
    runs: list[MonitorRun]


class ListMonitorsResponse(_Model):
    """`iohr.connections.v1.ListMonitorsResponse`"""

    monitors: list[Monitor]
    next_page_token: str


class ListTeamEventsResponse(_Model):
    """`iohr.accounts.v1.ListTeamEventsResponse`"""

    events: list[TeamEvent]
    next_page_token: str


class ListToolsResponse(_Model):
    """`iohr.connections.v1.ListToolsResponse`"""

    next_page_token: str
    tools: list[ToolInfo]


class ListUnitCategoriesResponse(_Model):
    """`iohr.accounts.v1.ListUnitCategoriesResponse`"""

    categories: list[UnitCategory]
    next_page_token: str


class ListValue(_Model):
    """`google.protobuf.ListValue`"""

    values: list[Value]


class Me(_Model):
    """`GET /v1/me` body."""

    client_id: str | None = None
    """The OAuth client the call came through, if any."""
    email: str | None = None
    """E-mail address, when the token carries one (a person's ID token does)."""
    key: Key | None = None
    kind: str
    """`person`, `client` or `service`."""
    name: str | None = None
    """Display name, when the token carries one."""
    org: str | None = None
    """Organisation, when minted."""
    role: str | None = None
    """Role, when the consent step stamped one."""
    scopes: list[str]
    """Granted scopes."""
    subject: str
    """The `sub` claim."""


class Monitor(_Model):
    """`iohr.connections.v1.Monitor`"""

    connection_id: str
    created_at: str
    executor: Executor | None = None
    fail_after: int
    health: str
    interval_secs: int
    last_run_at: str
    monitor_id: str
    name: str
    next_run_at: str
    params: MonitorParams | None = None
    paused_reason: str
    state: str


class MonitorParams(_Model):
    """`iohr.connections.v1.MonitorParams`"""

    expect_status: int
    max_ms: int
    path: str


class MonitorRun(_Model):
    """`iohr.connections.v1.MonitorRun`"""

    at: str
    error_class: str
    latency_ms: int
    ok: bool
    run_id: str
    status: str
    status_code: int


class Plan(_Model):
    """`iohr.accounts.v1.Plan`"""

    accounts: Int64
    at_zero: str
    description: str
    monthly_units: Int64
    name: str
    updated_at: str


class Problem(_Model):
    """`{"code","error","details","request_id"}`: the REST body and the SSE `error` payload."""

    code: Code
    """The slug."""
    details: list[Detail]
    """Typed details."""
    error: str
    """The sentence."""
    request_id: str
    """The request's id, the `x-request-id` the answer carries: name it when asking about a call. Empty on a socket or MQTT frame, whose own id names the call."""


class RecoverEndpointRequest(_Model):
    """`iohr.events.v1.RecoverEndpointRequest`"""

    endpoint_id: str
    since: str


class RecoverEndpointResponse(_Model):
    """`iohr.events.v1.RecoverEndpointResponse`"""

    created: int
    retried: int
    truncated: bool


class Refusal(_Model):
    """`iohr.agents.v1.Refusal`"""

    reason: str


class RemoveDomainResponse(_Model):
    """`iohr.accounts.v1.RemoveDomainResponse`"""


class ResolverAnswer(_Model):
    """`iohr.accounts.v1.ResolverAnswer`"""

    answered: bool
    dnssec: bool
    name: str
    seen: bool
    value: str


class RetryDeliveryResponse(_Model):
    """`iohr.events.v1.RetryDeliveryResponse`"""

    delivery: Delivery | None = None


class RevokeAgentRequest(_Model):
    """`iohr.agents.v1.RevokeAgentRequest`"""

    agent_id: str
    org_id: str


class RevokeAgentResponse(_Model):
    """`iohr.agents.v1.RevokeAgentResponse`"""

    agent: Agent | None = None


class RevokeGrantResponse(_Model):
    """`iohr.connections.v1.RevokeGrantResponse`"""

    grant: Grant | None = None


class RotateSecretResponse(_Model):
    """`iohr.events.v1.RotateSecretResponse`"""

    previous_expires_at: str
    secret: str


class RunCheckRequest(_Model):
    """`iohr.agents.v1.RunCheckRequest`"""

    agent_id: str
    auth: str
    expect: Expect | None = None
    org_id: str
    service: str
    surface: str
    target: Target | None = None


class RunCheckResponse(_Model):
    """`iohr.agents.v1.RunCheckResponse`"""

    result: JobResult | None = None


class SendTestResponse(_Model):
    """`iohr.events.v1.SendTestResponse`"""

    delivery: Delivery | None = None


class StreamEventsResponse(_Model):
    """`iohr.events.v1.StreamEventsResponse`"""

    account_id: str
    data: dict[str, str]
    id: str
    occurred_at: str
    type: str


class Struct(_Model):
    """`google.protobuf.Struct`"""

    fields: dict[str, Value]


class Target(_Model):
    """`iohr.agents.v1.Target`"""

    host: str
    port: int
    tls: bool
    url: str


class TeamEvent(_Model):
    """`iohr.accounts.v1.TeamEvent`"""

    action: str
    actor_name: str
    actor_sub: str
    after: str
    at: str
    before: str
    id: str
    subject: str


class TestConnectionResponse(_Model):
    """`iohr.connections.v1.TestConnectionResponse`"""

    result: ActionResult | None = None


class ToolInfo(_Model):
    """`iohr.connections.v1.ToolInfo`"""

    account_id: str
    action: str
    connection_id: str
    description: str
    name: str
    schema_json_: str = _Field(alias="schema_json")


class UnitCategory(_Model):
    """`iohr.accounts.v1.UnitCategory`"""

    description: str
    name: str
    units_per_1k_tokens: Int64
    units_per_call: Int64
    updated_at: str


class UnitDay(_Model):
    """`iohr.accounts.v1.UnitDay`"""

    day: str
    units: Int64


class UnitSeriesGroup(_Model):
    """`iohr.accounts.v1.UnitSeriesGroup`"""

    id: str
    label: str
    units: Int64


class UnitSeriesRow(_Model):
    """`iohr.accounts.v1.UnitSeriesRow`"""

    calls: Int64
    client_errors: Int64
    day: str
    group: str
    p50_ms: int
    p95_ms: int
    platform_errors: Int64
    tokens: Int64
    units: Int64


class UnitUsage(_Model):
    """`iohr.accounts.v1.UnitUsage`"""

    calls: Int64
    category: str
    client_errors: Int64
    key_id: str
    key_name: str
    p50_ms: int
    p95_ms: int
    platform_errors: Int64
    rpc: str
    tokens: Int64
    units: Int64
    user_id: str
    user_name: str


class UpdateConnectionRequest(_Model):
    """`iohr.connections.v1.UpdateConnectionRequest`"""

    config: dict[str, str]
    connection_id: str
    description: str
    name: str
    org_id: str
    paused: bool
    rotate_webhook_secret: bool
    secret: str
    secret_ref: str


class UpdateConnectionResponse(_Model):
    """`iohr.connections.v1.UpdateConnectionResponse`"""

    connection: Connection | None = None
    webhook_secret: str


class UpdateEndpointRequest(_Model):
    """`iohr.events.v1.UpdateEndpointRequest`"""

    description: str
    enabled: bool
    endpoint_id: str
    event_types: list[str]
    url: str


class UpdateMonitorRequest(_Model):
    """`iohr.connections.v1.UpdateMonitorRequest`"""

    fail_after: int
    interval_secs: int
    monitor_id: str
    name: str
    org_id: str
    params: MonitorParams | None = None
    state: str


class UpdateMonitorResponse(_Model):
    """`iohr.connections.v1.UpdateMonitorResponse`"""

    monitor: Monitor | None = None


class Uptime(_Model):
    """`iohr.connections.v1.Uptime`"""

    d30: float
    d7: float
    h24: float


class UsageRow(_Model):
    """`iohr.accounts.v1.UsageRow`"""

    amount: Int64
    day: str
    metric: str
    service: str


class Use(_Model):
    """`iohr.connections.v1.Use`"""

    action: str
    at: str
    caller: str
    caller_kind: str
    error_class: str
    executor: str
    grant_id: str
    id: str
    latency_ms: int
    status: str
    status_code: int


class Value(_Model):
    """`google.protobuf.Value`"""

    bool_value: bool
    list_value: ListValue | None = None
    null_value: Literal["NULL_VALUE"]
    """`google.protobuf.NullValue`"""
    number_value: float
    string_value: str
    struct_value: Struct | None = None


for _model in (
    Account,
    AccountsKey,
    ActionResult,
    AddDomainRequest,
    AddDomainResponse,
    Agent,
    CallActionRequest,
    CallActionResponse,
    CallToolRequest,
    CallToolResponse,
    Change,
    CheckDetail,
    CheckDomainRequest,
    CheckDomainResponse,
    ConfirmDomainRequest,
    ConfirmDomainResponse,
    Connection,
    Consumer,
    CreateConnectionRequest,
    CreateConnectionResponse,
    CreateEndpointRequest,
    CreateEndpointResponse,
    CreateEnrollmentRequest,
    CreateEnrollmentResponse,
    CreateInboxRequest,
    CreateInboxResponse,
    CreateMonitorRequest,
    CreateMonitorResponse,
    Credential,
    DeleteAgentResponse,
    DeleteConnectionResponse,
    DeleteEndpointResponse,
    DeleteInboxResponse,
    DeleteMonitorResponse,
    Delivery,
    DeliveryErrorCount,
    DeliveryStatsBucket,
    DeliveryTypeCount,
    Digest,
    Domain,
    DrillCode,
    Endpoint,
    EventStatsRow,
    EventType,
    Example,
    Executor,
    Expect,
    Field,
    GetAgentResponse,
    GetConnectionResponse,
    GetDeliveryStatsResponse,
    GetDigestResponse,
    GetDomainResponse,
    GetEventStatsResponse,
    GetMeResponse,
    GetMonitorResponse,
    GetMonitorSummaryResponse,
    GetUnitSeriesResponse,
    GetUnitsResponse,
    GetUsageResponse,
    Grant,
    Inbox,
    InboxRequest,
    Item,
    JobResult,
    Key,
    Kind,
    KindAction,
    Latency,
    ListAgentsResponse,
    ListConnectionsResponse,
    ListDeliveriesResponse,
    ListDigestsResponse,
    ListDomainsResponse,
    ListEndpointsResponse,
    ListEventTypesResponse,
    ListGrantsResponse,
    ListHistoryResponse,
    ListInboxRequestsResponse,
    ListInboxesResponse,
    ListItemsResponse,
    ListKindsResponse,
    ListMonitorRunsResponse,
    ListMonitorsResponse,
    ListTeamEventsResponse,
    ListToolsResponse,
    ListUnitCategoriesResponse,
    ListValue,
    Me,
    Monitor,
    MonitorParams,
    MonitorRun,
    Plan,
    Problem,
    RecoverEndpointRequest,
    RecoverEndpointResponse,
    Refusal,
    RemoveDomainResponse,
    ResolverAnswer,
    RetryDeliveryResponse,
    RevokeAgentRequest,
    RevokeAgentResponse,
    RevokeGrantResponse,
    RotateSecretResponse,
    RunCheckRequest,
    RunCheckResponse,
    SendTestResponse,
    StreamEventsResponse,
    Struct,
    Target,
    TeamEvent,
    TestConnectionResponse,
    ToolInfo,
    UnitCategory,
    UnitDay,
    UnitSeriesGroup,
    UnitSeriesRow,
    UnitUsage,
    UpdateConnectionRequest,
    UpdateConnectionResponse,
    UpdateEndpointRequest,
    UpdateMonitorRequest,
    UpdateMonitorResponse,
    Uptime,
    UsageRow,
    Use,
    Value,
):
    _model.model_rebuild()
