# Generated by iohr sdk generate for cuts public=sha256:6339411bc907ba74eb8778f783884753485f7c3aa5107d2a4793c162b231e31a; do not edit.
"""Each operation of this surface as the runtime's `Operation`, built from its arguments."""

from __future__ import annotations

from ..runtime import (
    Operation,
    codegen,
)
from .models import (
    AddDomainRequest,
    CallActionRequest,
    CallToolRequest,
    CheckDomainRequest,
    ConfirmDomainRequest,
    CreateConnectionRequest,
    CreateEndpointRequest,
    CreateEnrollmentRequest,
    CreateInboxRequest,
    CreateMonitorRequest,
    RecoverEndpointRequest,
    RevokeAgentRequest,
    RunCheckRequest,
    UpdateConnectionRequest,
    UpdateEndpointRequest,
    UpdateMonitorRequest,
)


def delete_agent(org_id: str, agent_id: str) -> Operation:
    """`DELETE /v1/accounts/orgs/{org_id}/agents/{agent_id}`; needs scope `agents:write`. Transcoded from `/iohr.agents.v1.AgentsService/DeleteAgent` on the `agents` backend."""
    return Operation(
        name="agents.delete_agent",
        method="DELETE",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/agents/{codegen.path_segment(agent_id)}",
        scopes=("agents:write",),
    )


def delete_connection(org_id: str, connection_id: str) -> Operation:
    """`DELETE /v1/accounts/orgs/{org_id}/connections/{connection_id}`; needs scope `connections:write`. Transcoded from `/iohr.connections.v1.ConnectionsService/DeleteConnection` on the `connections` backend."""
    return Operation(
        name="connections.delete_connection",
        method="DELETE",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}",
        scopes=("connections:write",),
    )


def revoke_grant(org_id: str, connection_id: str, grant_id: str) -> Operation:
    """`DELETE /v1/accounts/orgs/{org_id}/connections/{connection_id}/grants/{grant_id}`; needs scope `connections:write`. Transcoded from `/iohr.connections.v1.ConnectionsService/RevokeGrant` on the `connections` backend."""
    return Operation(
        name="connections.revoke_grant",
        method="DELETE",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}/grants/{codegen.path_segment(grant_id)}",
        scopes=("connections:write",),
    )


def remove_domain(org_id: str, domain: str) -> Operation:
    """`DELETE /v1/accounts/orgs/{org_id}/domains/{domain}`; needs scope `domains:write`. Transcoded from `/iohr.accounts.v1.AccountsService/RemoveDomain` on the `accounts` backend."""
    return Operation(
        name="accounts.remove_domain",
        method="DELETE",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/domains/{codegen.path_segment(domain)}",
        scopes=("domains:write",),
    )


def delete_monitor(org_id: str, monitor_id: str) -> Operation:
    """`DELETE /v1/accounts/orgs/{org_id}/monitors/{monitor_id}`; needs scope `connections:write`. Transcoded from `/iohr.connections.v1.ConnectionsService/DeleteMonitor` on the `connections` backend."""
    return Operation(
        name="connections.delete_monitor",
        method="DELETE",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/monitors/{codegen.path_segment(monitor_id)}",
        scopes=("connections:write",),
    )


def delete_endpoint(endpoint_id: str) -> Operation:
    """`DELETE /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/DeleteEndpoint` on the `events` backend."""
    return Operation(
        name="events.delete_endpoint",
        method="DELETE",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}",
        scopes=("webhooks:write",),
    )


def delete_inbox(inbox_id: str) -> Operation:
    """`DELETE /v1/webhooks/inboxes/{inbox_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/DeleteInbox` on the `events` backend."""
    return Operation(
        name="events.delete_inbox",
        method="DELETE",
        path=f"/v1/webhooks/inboxes/{codegen.path_segment(inbox_id)}",
        scopes=("webhooks:write",),
    )


def get_me() -> Operation:
    """`GET /v1/accounts/me`; needs scope `account:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetMe` on the `accounts` backend."""
    return Operation(
        name="accounts.get_me",
        method="GET",
        path="/v1/accounts/me",
        scopes=("account:read",),
    )


def list_agents(org_id: str, *, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/agents`; needs scope `agents:read`. Transcoded from `/iohr.agents.v1.AgentsService/ListAgents` on the `agents` backend."""
    return Operation(
        name="agents.list_agents",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/agents",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("agents:read",),
    )


def get_agent(org_id: str, agent_id: str) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/agents/{agent_id}`; needs scope `agents:read`. Transcoded from `/iohr.agents.v1.AgentsService/GetAgent` on the `agents` backend."""
    return Operation(
        name="agents.get_agent",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/agents/{codegen.path_segment(agent_id)}",
        scopes=("agents:read",),
    )


def list_team_events(org_id: str, *, action: str | None = None, actor: str | None = None, from_: str | None = None, to: str | None = None, query: str | None = None, page_token: str | None = None, limit: int | None = None, after: str | None = None, page_size: int | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/audit`; needs scope `account:audit`. Transcoded from `/iohr.accounts.v1.AccountsService/ListTeamEvents` on the `accounts` backend."""
    return Operation(
        name="accounts.list_team_events",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/audit",
        query=(("action", action), ("actor", actor), ("from", from_), ("to", to), ("query", query), ("page_token", page_token), ("limit", limit), ("after", after), ("page_size", page_size),),
        scopes=("account:audit",),
    )


def list_connections(org_id: str, *, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/connections`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/ListConnections` on the `connections` backend."""
    return Operation(
        name="connections.list_connections",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("connections:read",),
    )


def get_connection(org_id: str, connection_id: str) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/connections/{connection_id}`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/GetConnection` on the `connections` backend."""
    return Operation(
        name="connections.get_connection",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}",
        scopes=("connections:read",),
    )


def list_grants(org_id: str, connection_id: str, *, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/connections/{connection_id}/grants`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/ListGrants` on the `connections` backend."""
    return Operation(
        name="connections.list_grants",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}/grants",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("connections:read",),
    )


def list_history(org_id: str, connection_id: str, *, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/connections/{connection_id}/history`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/ListHistory` on the `connections` backend."""
    return Operation(
        name="connections.list_history",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}/history",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("connections:read",),
    )


def list_domains(org_id: str, *, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/domains`; needs scope `domains:read`. Transcoded from `/iohr.accounts.v1.AccountsService/ListDomains` on the `accounts` backend."""
    return Operation(
        name="accounts.list_domains",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/domains",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("domains:read",),
    )


def get_domain(org_id: str, domain: str) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/domains/{domain}`; needs scope `domains:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetDomain` on the `accounts` backend."""
    return Operation(
        name="accounts.get_domain",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/domains/{codegen.path_segment(domain)}",
        scopes=("domains:read",),
    )


def list_monitors(org_id: str, *, page_size: int | None = None, page_token: str | None = None, connection_id: str | None = None, agent_id: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/monitors`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/ListMonitors` on the `connections` backend."""
    return Operation(
        name="connections.list_monitors",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/monitors",
        query=(("page_size", page_size), ("page_token", page_token), ("connection_id", connection_id), ("agent_id", agent_id),),
        scopes=("connections:read",),
    )


def get_monitor(org_id: str, monitor_id: str) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/monitors/{monitor_id}`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/GetMonitor` on the `connections` backend."""
    return Operation(
        name="connections.get_monitor",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/monitors/{codegen.path_segment(monitor_id)}",
        scopes=("connections:read",),
    )


def list_monitor_runs(org_id: str, monitor_id: str, *, page_size: int | None = None, page_token: str | None = None, from_: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/monitors/{monitor_id}/runs`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/ListMonitorRuns` on the `connections` backend."""
    return Operation(
        name="connections.list_monitor_runs",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/monitors/{codegen.path_segment(monitor_id)}/runs",
        query=(("page_size", page_size), ("page_token", page_token), ("from", from_),),
        scopes=("connections:read",),
    )


def get_monitor_summary(org_id: str, monitor_id: str) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/monitors/{monitor_id}/summary`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/GetMonitorSummary` on the `connections` backend."""
    return Operation(
        name="connections.get_monitor_summary",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/monitors/{codegen.path_segment(monitor_id)}/summary",
        scopes=("connections:read",),
    )


def list_requests(org_id: str, *, page_size: int | None = None, page_token: str | None = None, status: str | None = None, query: str | None = None, after: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/requests`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/ListRequests` on the `accounts` backend."""
    return Operation(
        name="accounts.list_requests",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/requests",
        query=(("page_size", page_size), ("page_token", page_token), ("status", status), ("query", query), ("after", after),),
        scopes=("usage:read",),
    )


def get_units(org_id: str) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/units`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetUnits` on the `accounts` backend."""
    return Operation(
        name="accounts.get_units",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/units",
        scopes=("usage:read",),
    )


def get_unit_series(org_id: str, *, from_: str | None = None, to: str | None = None, by: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/units/series`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetUnitSeries` on the `accounts` backend."""
    return Operation(
        name="accounts.get_unit_series",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/units/series",
        query=(("from", from_), ("to", to), ("by", by),),
        scopes=("usage:read",),
    )


def get_usage(org_id: str, *, from_: str | None = None, to: str | None = None) -> Operation:
    """`GET /v1/accounts/orgs/{org_id}/usage`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetUsage` on the `accounts` backend."""
    return Operation(
        name="accounts.get_usage",
        method="GET",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/usage",
        query=(("from", from_), ("to", to),),
        scopes=("usage:read",),
    )


def list_unit_categories(*, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/accounts/units/categories`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/ListUnitCategories` on the `accounts` backend."""
    return Operation(
        name="accounts.list_unit_categories",
        method="GET",
        path="/v1/accounts/units/categories",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("usage:read",),
    )


def list_kinds(*, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/connections/kinds`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/ListKinds` on the `connections` backend."""
    return Operation(
        name="connections.list_kinds",
        method="GET",
        path="/v1/connections/kinds",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("connections:read",),
    )


def list_tools(*, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/connections/tools`; needs scope `connections:read`. Transcoded from `/iohr.connections.v1.ConnectionsService/ListTools` on the `connections` backend."""
    return Operation(
        name="connections.list_tools",
        method="GET",
        path="/v1/connections/tools",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("connections:read",),
    )


def list_notifications(*, page_size: int | None = None, page_token: str | None = None, account_id: str | None = None, types: str | None = None) -> Operation:
    """`GET /v1/events/notifications`; needs scope `events:read`. Transcoded from `/iohr.events.v1.EventsService/ListNotifications` on the `events` backend."""
    return Operation(
        name="events.list_notifications",
        method="GET",
        path="/v1/events/notifications",
        query=(("page_size", page_size), ("page_token", page_token), ("account_id", account_id), ("types", types),),
        scopes=("events:read",),
    )


def get_event_stats(*, account_id: str | None = None, range: str | None = None) -> Operation:
    """`GET /v1/events/stats`; needs scope `events:read`. Transcoded from `/iohr.events.v1.EventsService/GetEventStats` on the `events` backend."""
    return Operation(
        name="events.get_event_stats",
        method="GET",
        path="/v1/events/stats",
        query=(("account_id", account_id), ("range", range),),
        scopes=("events:read",),
    )


def list_event_types(*, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/events/types`; needs scope `events:read`. Transcoded from `/iohr.events.v1.EventsService/ListEventTypes` on the `events` backend."""
    return Operation(
        name="events.list_event_types",
        method="GET",
        path="/v1/events/types",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("events:read",),
    )


def me() -> Operation:
    """`GET /v1/me`; needs scope `identity:read`. A key needs scope `identity:read`."""
    return Operation(
        name="me",
        method="GET",
        path="/v1/me",
        scopes=("identity:read",),
    )


def list_digests(*, language: str | None = None, lang: str | None = None, limit: int | None = None, include_drafts: bool | None = None, before_week: str | None = None, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/radar/digests`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/ListDigests` on the `radar` backend."""
    return Operation(
        name="radar.list_digests",
        method="GET",
        path="/v1/radar/digests",
        query=(("language", language), ("lang", lang), ("limit", limit), ("include_drafts", include_drafts), ("before_week", before_week), ("page_size", page_size), ("page_token", page_token),),
        scopes=("radar:read",),
    )


def get_digest(id: str) -> Operation:
    """`GET /v1/radar/digests/{id}`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/GetDigest` on the `radar` backend."""
    return Operation(
        name="radar.get_digest",
        method="GET",
        path=f"/v1/radar/digests/{codegen.path_segment(id)}",
        scopes=("radar:read",),
    )


def list_items(*, language: str | None = None, limit: int | None = None, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/radar/items`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/ListItems` on the `radar` backend."""
    return Operation(
        name="radar.list_items",
        method="GET",
        path="/v1/radar/items",
        query=(("language", language), ("limit", limit), ("page_size", page_size), ("page_token", page_token),),
        scopes=("radar:read",),
    )


def list_endpoints(*, account_id: str | None = None, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/webhooks/endpoints`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListEndpoints` on the `events` backend."""
    return Operation(
        name="events.list_endpoints",
        method="GET",
        path="/v1/webhooks/endpoints",
        query=(("account_id", account_id), ("page_size", page_size), ("page_token", page_token),),
        scopes=("webhooks:read",),
    )


def get_endpoint(endpoint_id: str) -> Operation:
    """`GET /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/GetEndpoint` on the `events` backend."""
    return Operation(
        name="events.get_endpoint",
        method="GET",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}",
        scopes=("webhooks:read",),
    )


def list_deliveries(endpoint_id: str, *, status: str | None = None, page_token: str | None = None, page_size: int | None = None) -> Operation:
    """`GET /v1/webhooks/endpoints/{endpoint_id}/deliveries`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListDeliveries` on the `events` backend."""
    return Operation(
        name="events.list_deliveries",
        method="GET",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}/deliveries",
        query=(("status", status), ("page_token", page_token), ("page_size", page_size),),
        scopes=("webhooks:read",),
    )


def list_inboxes(*, account_id: str | None = None, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/webhooks/inboxes`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListInboxes` on the `events` backend."""
    return Operation(
        name="events.list_inboxes",
        method="GET",
        path="/v1/webhooks/inboxes",
        query=(("account_id", account_id), ("page_size", page_size), ("page_token", page_token),),
        scopes=("webhooks:read",),
    )


def list_inbox_requests(inbox_id: str, *, page_size: int | None = None, page_token: str | None = None) -> Operation:
    """`GET /v1/webhooks/inboxes/{inbox_id}/requests`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListInboxRequests` on the `events` backend."""
    return Operation(
        name="events.list_inbox_requests",
        method="GET",
        path=f"/v1/webhooks/inboxes/{codegen.path_segment(inbox_id)}/requests",
        query=(("page_size", page_size), ("page_token", page_token),),
        scopes=("webhooks:read",),
    )


def get_delivery_stats(*, account_id: str | None = None, endpoint_id: str | None = None, range: str | None = None) -> Operation:
    """`GET /v1/webhooks/stats`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/GetDeliveryStats` on the `events` backend."""
    return Operation(
        name="events.get_delivery_stats",
        method="GET",
        path="/v1/webhooks/stats",
        query=(("account_id", account_id), ("endpoint_id", endpoint_id), ("range", range),),
        scopes=("webhooks:read",),
    )


def update_connection(org_id: str, connection_id: str, body: UpdateConnectionRequest) -> Operation:
    """`PATCH /v1/accounts/orgs/{org_id}/connections/{connection_id}`; needs scope `connections:write`. Transcoded from `/iohr.connections.v1.ConnectionsService/UpdateConnection` on the `connections` backend."""
    return Operation(
        name="connections.update_connection",
        method="PATCH",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}",
        body=body,
        scopes=("connections:write",),
    )


def update_monitor(org_id: str, monitor_id: str, body: UpdateMonitorRequest) -> Operation:
    """`PATCH /v1/accounts/orgs/{org_id}/monitors/{monitor_id}`; needs scope `connections:write`. Transcoded from `/iohr.connections.v1.ConnectionsService/UpdateMonitor` on the `connections` backend."""
    return Operation(
        name="connections.update_monitor",
        method="PATCH",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/monitors/{codegen.path_segment(monitor_id)}",
        body=body,
        scopes=("connections:write",),
    )


def update_endpoint(endpoint_id: str, body: UpdateEndpointRequest) -> Operation:
    """`PATCH /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/UpdateEndpoint` on the `events` backend."""
    return Operation(
        name="events.update_endpoint",
        method="PATCH",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}",
        body=body,
        scopes=("webhooks:write",),
    )


def create_enrollment(org_id: str, body: CreateEnrollmentRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/agents/enrollments`; needs scope `agents:write`. Transcoded from `/iohr.agents.v1.AgentsService/CreateEnrollment` on the `agents` backend."""
    return Operation(
        name="agents.create_enrollment",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/agents/enrollments",
        body=body,
        scopes=("agents:write",),
    )


def run_check(org_id: str, agent_id: str, body: RunCheckRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/agents/{agent_id}/checks`; needs scope `agents:write`. Transcoded from `/iohr.agents.v1.AgentsService/RunCheck` on the `agents` backend."""
    return Operation(
        name="agents.run_check",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/agents/{codegen.path_segment(agent_id)}/checks",
        body=body,
        scopes=("agents:write",),
    )


def revoke_agent(org_id: str, agent_id: str, body: RevokeAgentRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/agents/{agent_id}/revoke`; needs scope `agents:write`. Transcoded from `/iohr.agents.v1.AgentsService/RevokeAgent` on the `agents` backend."""
    return Operation(
        name="agents.revoke_agent",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/agents/{codegen.path_segment(agent_id)}/revoke",
        body=body,
        scopes=("agents:write",),
    )


def create_connection(org_id: str, body: CreateConnectionRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/connections`; needs scope `connections:write`. Transcoded from `/iohr.connections.v1.ConnectionsService/CreateConnection` on the `connections` backend."""
    return Operation(
        name="connections.create_connection",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections",
        body=body,
        scopes=("connections:write",),
    )


def call_action(org_id: str, connection_id: str, action: str, body: CallActionRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/connections/{connection_id}/actions/{action}`; needs scope `connections:use`. Transcoded from `/iohr.connections.v1.ConnectionsService/CallAction` on the `connections` backend."""
    return Operation(
        name="connections.call_action",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}/actions/{codegen.path_segment(action)}",
        body=body,
        scopes=("connections:use",),
    )


def create_monitor(org_id: str, connection_id: str, body: CreateMonitorRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/connections/{connection_id}/monitors`; needs scope `connections:write`. Transcoded from `/iohr.connections.v1.ConnectionsService/CreateMonitor` on the `connections` backend."""
    return Operation(
        name="connections.create_monitor",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}/monitors",
        body=body,
        scopes=("connections:write",),
    )


def test_connection(org_id: str, connection_id: str) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/connections/{connection_id}/test`; needs scope `connections:write`. Transcoded from `/iohr.connections.v1.ConnectionsService/TestConnection` on the `connections` backend."""
    return Operation(
        name="connections.test_connection",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/connections/{codegen.path_segment(connection_id)}/test",
        scopes=("connections:write",),
    )


def add_domain(org_id: str, body: AddDomainRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/domains`; needs scope `domains:write`. Transcoded from `/iohr.accounts.v1.AccountsService/AddDomain` on the `accounts` backend."""
    return Operation(
        name="accounts.add_domain",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/domains",
        body=body,
        scopes=("domains:write",),
    )


def check_domain(org_id: str, domain: str, body: CheckDomainRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/domains/{domain}/check`; needs scope `domains:write`. Transcoded from `/iohr.accounts.v1.AccountsService/CheckDomain` on the `accounts` backend."""
    return Operation(
        name="accounts.check_domain",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/domains/{codegen.path_segment(domain)}/check",
        body=body,
        scopes=("domains:write",),
    )


def confirm_domain(org_id: str, domain: str, body: ConfirmDomainRequest) -> Operation:
    """`POST /v1/accounts/orgs/{org_id}/domains/{domain}/confirm`; needs scope `domains:write`. Transcoded from `/iohr.accounts.v1.AccountsService/ConfirmDomain` on the `accounts` backend."""
    return Operation(
        name="accounts.confirm_domain",
        method="POST",
        path=f"/v1/accounts/orgs/{codegen.path_segment(org_id)}/domains/{codegen.path_segment(domain)}/confirm",
        body=body,
        scopes=("domains:write",),
    )


def call_tool(name: str, body: CallToolRequest) -> Operation:
    """`POST /v1/connections/tools/{name}`; needs scope `connections:use`. Transcoded from `/iohr.connections.v1.ConnectionsService/CallTool` on the `connections` backend."""
    return Operation(
        name="connections.call_tool",
        method="POST",
        path=f"/v1/connections/tools/{codegen.path_segment(name)}",
        body=body,
        scopes=("connections:use",),
    )


def retry_delivery(delivery_id: str) -> Operation:
    """`POST /v1/webhooks/deliveries/{delivery_id}/retry`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RetryDelivery` on the `events` backend."""
    return Operation(
        name="events.retry_delivery",
        method="POST",
        path=f"/v1/webhooks/deliveries/{codegen.path_segment(delivery_id)}/retry",
        scopes=("webhooks:write",),
    )


def create_endpoint(body: CreateEndpointRequest) -> Operation:
    """`POST /v1/webhooks/endpoints`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/CreateEndpoint` on the `events` backend."""
    return Operation(
        name="events.create_endpoint",
        method="POST",
        path="/v1/webhooks/endpoints",
        body=body,
        scopes=("webhooks:write",),
    )


def recover_endpoint(endpoint_id: str, body: RecoverEndpointRequest) -> Operation:
    """`POST /v1/webhooks/endpoints/{endpoint_id}/recover`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RecoverEndpoint` on the `events` backend."""
    return Operation(
        name="events.recover_endpoint",
        method="POST",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}/recover",
        body=body,
        scopes=("webhooks:write",),
    )


def rotate_secret(endpoint_id: str) -> Operation:
    """`POST /v1/webhooks/endpoints/{endpoint_id}/rotate`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RotateSecret` on the `events` backend."""
    return Operation(
        name="events.rotate_secret",
        method="POST",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}/rotate",
        scopes=("webhooks:write",),
    )


def send_test(endpoint_id: str) -> Operation:
    """`POST /v1/webhooks/endpoints/{endpoint_id}/test`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/SendTest` on the `events` backend."""
    return Operation(
        name="events.send_test",
        method="POST",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}/test",
        scopes=("webhooks:write",),
    )


def create_inbox(body: CreateInboxRequest) -> Operation:
    """`POST /v1/webhooks/inboxes`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/CreateInbox` on the `events` backend."""
    return Operation(
        name="events.create_inbox",
        method="POST",
        path="/v1/webhooks/inboxes",
        body=body,
        scopes=("webhooks:write",),
    )
