// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

/**
 * The query parameters of <code>GET /v1/accounts/units/categories</code>.
 *
 * @param pageSize <code>page_size</code>; <code>null</code> to leave it out
 * @param pageToken <code>page_token</code>; <code>null</code> to leave it out
 */
public record AccountsListUnitCategoriesParams(
        Integer pageSize,
        String pageToken) {

    /**
     * A builder.
     *
     * @return a builder with every field unset
     */
    public static Builder builder() {
        return new Builder();
    }

    /** Builds a <code>AccountsListUnitCategoriesParams</code>. */
    public static final class Builder {
        private Integer pageSize;
        private String pageToken;

        private Builder() {}

        /**
         * Sets <code>pageSize</code>.
         *
         * @param pageSize the value
         * @return this builder
         */
        public Builder pageSize(Integer pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /**
         * Sets <code>pageToken</code>.
         *
         * @param pageToken the value
         * @return this builder
         */
        public Builder pageToken(String pageToken) {
            this.pageToken = pageToken;
            return this;
        }

        /**
         * The value.
         *
         * @return the <code>AccountsListUnitCategoriesParams</code>
         */
        public AccountsListUnitCategoriesParams build() {
            return new AccountsListUnitCategoriesParams(pageSize, pageToken);
        }
    }
}
