// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import hr.inorbit.sdk.Client;
import hr.inorbit.sdk.EventStream;
import hr.inorbit.sdk.Pages;
import hr.inorbit.sdk.Response;
import hr.inorbit.sdk.codegen.Codegen;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;

/**
 * The <code>events</code> operations profile <code>acme-ci</code> may call.
 */
public final class AcmeCiEvents {

    private final Client client;

    AcmeCiEvents(Client client) {
        this.client = Objects.requireNonNull(client, "client");
    }

    /**
     * <code>DELETE /v1/webhooks/endpoints/{endpoint_id}</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/DeleteEndpoint</code> on the <code>events</code> backend.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<DeleteEndpointResponse> deleteEndpoint(String endpointId) {
        return Operations.deleteEndpoint(client, endpointId);
    }

    /**
     * <code>DELETE /v1/webhooks/endpoints/{endpoint_id}</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/DeleteEndpoint</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<DeleteEndpointResponse>> deleteEndpointAsync(String endpointId) {
        return Operations.deleteEndpointAsync(client, endpointId);
    }

    /**
     * <code>DELETE /v1/webhooks/inboxes/{inbox_id}</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/DeleteInbox</code> on the <code>events</code> backend.
     *
     * @param inboxId the <code>inbox_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<DeleteInboxResponse> deleteInbox(String inboxId) {
        return Operations.deleteInbox(client, inboxId);
    }

    /**
     * <code>DELETE /v1/webhooks/inboxes/{inbox_id}</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/DeleteInbox</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param inboxId the <code>inbox_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<DeleteInboxResponse>> deleteInboxAsync(String inboxId) {
        return Operations.deleteInboxAsync(client, inboxId);
    }

    /**
     * <code>GET /v1/events/events</code>; needs scope <code>events:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/StreamEvents</code> on the <code>events</code> backend.
     *
     * @param params the query parameters
     * @return the events, one model each; close it to stop early
     */
    public EventStream<StreamEventsResponse> streamEvents(EventsStreamEventsParams params) {
        return Operations.streamEvents(client, params);
    }

    /**
     * <code>GET /v1/events/events</code>; needs scope <code>events:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/StreamEvents</code> on the <code>events</code> backend.
     *
     * @return the events, one model each; close it to stop early
     */
    public EventStream<StreamEventsResponse> streamEvents() {
        return Operations.streamEvents(client, EventsStreamEventsParams.builder().build());
    }

    /**
     * <code>GET /v1/events/types</code>; needs scope <code>events:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListEventTypes</code> on the <code>events</code> backend.
     *
     * @param params the query parameters
     * @return the answer, typed, and the raw one
     */
    public Response<ListEventTypesResponse> listEventTypes(EventsListEventTypesParams params) {
        return Operations.listEventTypes(client, params);
    }

    /**
     * <code>GET /v1/events/types</code>; needs scope <code>events:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListEventTypes</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param params the query parameters
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListEventTypesResponse>> listEventTypesAsync(EventsListEventTypesParams params) {
        return Operations.listEventTypesAsync(client, params);
    }

    /**
     * <code>GET /v1/events/types</code>; needs scope <code>events:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListEventTypes</code> on the <code>events</code> backend.
     *
     * @return the answer, typed, and the raw one
     */
    public Response<ListEventTypesResponse> listEventTypes() {
        return Operations.listEventTypes(client, EventsListEventTypesParams.builder().build());
    }

    /**
     * <code>GET /v1/events/types</code>; needs scope <code>events:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListEventTypes</code> on the <code>events</code> backend. On the client's executor.
     *
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListEventTypesResponse>> listEventTypesAsync() {
        return Operations.listEventTypesAsync(client, EventsListEventTypesParams.builder().build());
    }

    /**
     * Every item <code>GET /v1/events/types</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @param params the query parameters; the page token is set for each page
     * @return the walk
     */
    public Pages<EventType> allListEventTypes(EventsListEventTypesParams params) {
        return Codegen.pages(token -> {
            var page = Operations.listEventTypes(client, new EventsListEventTypesParams(params.pageSize(), token != null ? token : params.pageToken())).value();
            return new Pages.Page<>(page.types(), page.nextPageToken());
        });
    }

    /**
     * Every item <code>GET /v1/events/types</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @return the walk
     */
    public Pages<EventType> allListEventTypes() {
        return allListEventTypes(EventsListEventTypesParams.builder().build());
    }

    /**
     * <code>GET /v1/webhooks/endpoints</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListEndpoints</code> on the <code>events</code> backend.
     *
     * @param params the query parameters
     * @return the answer, typed, and the raw one
     */
    public Response<ListEndpointsResponse> listEndpoints(EventsListEndpointsParams params) {
        return Operations.listEndpoints(client, params);
    }

    /**
     * <code>GET /v1/webhooks/endpoints</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListEndpoints</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param params the query parameters
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListEndpointsResponse>> listEndpointsAsync(EventsListEndpointsParams params) {
        return Operations.listEndpointsAsync(client, params);
    }

    /**
     * <code>GET /v1/webhooks/endpoints</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListEndpoints</code> on the <code>events</code> backend.
     *
     * @return the answer, typed, and the raw one
     */
    public Response<ListEndpointsResponse> listEndpoints() {
        return Operations.listEndpoints(client, EventsListEndpointsParams.builder().build());
    }

    /**
     * <code>GET /v1/webhooks/endpoints</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListEndpoints</code> on the <code>events</code> backend. On the client's executor.
     *
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListEndpointsResponse>> listEndpointsAsync() {
        return Operations.listEndpointsAsync(client, EventsListEndpointsParams.builder().build());
    }

    /**
     * Every item <code>GET /v1/webhooks/endpoints</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @param params the query parameters; the page token is set for each page
     * @return the walk
     */
    public Pages<Endpoint> allListEndpoints(EventsListEndpointsParams params) {
        return Codegen.pages(token -> {
            var page = Operations.listEndpoints(client, new EventsListEndpointsParams(params.accountId(), params.pageSize(), token != null ? token : params.pageToken())).value();
            return new Pages.Page<>(page.endpoints(), page.nextPageToken());
        });
    }

    /**
     * Every item <code>GET /v1/webhooks/endpoints</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @return the walk
     */
    public Pages<Endpoint> allListEndpoints() {
        return allListEndpoints(EventsListEndpointsParams.builder().build());
    }

    /**
     * <code>GET /v1/webhooks/endpoints/{endpoint_id}</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/GetEndpoint</code> on the <code>events</code> backend.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<Endpoint> getEndpoint(String endpointId) {
        return Operations.getEndpoint(client, endpointId);
    }

    /**
     * <code>GET /v1/webhooks/endpoints/{endpoint_id}</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/GetEndpoint</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<Endpoint>> getEndpointAsync(String endpointId) {
        return Operations.getEndpointAsync(client, endpointId);
    }

    /**
     * <code>GET /v1/webhooks/endpoints/{endpoint_id}/deliveries</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListDeliveries</code> on the <code>events</code> backend.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @param params the query parameters
     * @return the answer, typed, and the raw one
     */
    public Response<ListDeliveriesResponse> listDeliveries(String endpointId, EventsListDeliveriesParams params) {
        return Operations.listDeliveries(client, endpointId, params);
    }

    /**
     * <code>GET /v1/webhooks/endpoints/{endpoint_id}/deliveries</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListDeliveries</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @param params the query parameters
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListDeliveriesResponse>> listDeliveriesAsync(String endpointId, EventsListDeliveriesParams params) {
        return Operations.listDeliveriesAsync(client, endpointId, params);
    }

    /**
     * <code>GET /v1/webhooks/endpoints/{endpoint_id}/deliveries</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListDeliveries</code> on the <code>events</code> backend.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<ListDeliveriesResponse> listDeliveries(String endpointId) {
        return Operations.listDeliveries(client, endpointId, EventsListDeliveriesParams.builder().build());
    }

    /**
     * <code>GET /v1/webhooks/endpoints/{endpoint_id}/deliveries</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListDeliveries</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListDeliveriesResponse>> listDeliveriesAsync(String endpointId) {
        return Operations.listDeliveriesAsync(client, endpointId, EventsListDeliveriesParams.builder().build());
    }

    /**
     * Every item <code>GET /v1/webhooks/endpoints/{endpoint_id}/deliveries</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @param endpointId the <code>endpointId</code> path parameter
     * @param params the query parameters; the page token is set for each page
     * @return the walk
     */
    public Pages<Delivery> allListDeliveries(String endpointId, EventsListDeliveriesParams params) {
        return Codegen.pages(token -> {
            var page = Operations.listDeliveries(client, endpointId, new EventsListDeliveriesParams(params.status(), token != null ? token : params.pageToken(), params.pageSize())).value();
            return new Pages.Page<>(page.deliveries(), page.nextPageToken());
        });
    }

    /**
     * Every item <code>GET /v1/webhooks/endpoints/{endpoint_id}/deliveries</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @param endpointId the <code>endpointId</code> path parameter
     * @return the walk
     */
    public Pages<Delivery> allListDeliveries(String endpointId) {
        return allListDeliveries(endpointId, EventsListDeliveriesParams.builder().build());
    }

    /**
     * <code>GET /v1/webhooks/inboxes</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListInboxes</code> on the <code>events</code> backend.
     *
     * @param params the query parameters
     * @return the answer, typed, and the raw one
     */
    public Response<ListInboxesResponse> listInboxes(EventsListInboxesParams params) {
        return Operations.listInboxes(client, params);
    }

    /**
     * <code>GET /v1/webhooks/inboxes</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListInboxes</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param params the query parameters
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListInboxesResponse>> listInboxesAsync(EventsListInboxesParams params) {
        return Operations.listInboxesAsync(client, params);
    }

    /**
     * <code>GET /v1/webhooks/inboxes</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListInboxes</code> on the <code>events</code> backend.
     *
     * @return the answer, typed, and the raw one
     */
    public Response<ListInboxesResponse> listInboxes() {
        return Operations.listInboxes(client, EventsListInboxesParams.builder().build());
    }

    /**
     * <code>GET /v1/webhooks/inboxes</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListInboxes</code> on the <code>events</code> backend. On the client's executor.
     *
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListInboxesResponse>> listInboxesAsync() {
        return Operations.listInboxesAsync(client, EventsListInboxesParams.builder().build());
    }

    /**
     * Every item <code>GET /v1/webhooks/inboxes</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @param params the query parameters; the page token is set for each page
     * @return the walk
     */
    public Pages<Inbox> allListInboxes(EventsListInboxesParams params) {
        return Codegen.pages(token -> {
            var page = Operations.listInboxes(client, new EventsListInboxesParams(params.accountId(), params.pageSize(), token != null ? token : params.pageToken())).value();
            return new Pages.Page<>(page.inboxes(), page.nextPageToken());
        });
    }

    /**
     * Every item <code>GET /v1/webhooks/inboxes</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @return the walk
     */
    public Pages<Inbox> allListInboxes() {
        return allListInboxes(EventsListInboxesParams.builder().build());
    }

    /**
     * <code>GET /v1/webhooks/inboxes/{inbox_id}/requests</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListInboxRequests</code> on the <code>events</code> backend.
     *
     * @param inboxId the <code>inbox_id</code> path parameter
     * @param params the query parameters
     * @return the answer, typed, and the raw one
     */
    public Response<ListInboxRequestsResponse> listInboxRequests(String inboxId, EventsListInboxRequestsParams params) {
        return Operations.listInboxRequests(client, inboxId, params);
    }

    /**
     * <code>GET /v1/webhooks/inboxes/{inbox_id}/requests</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListInboxRequests</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param inboxId the <code>inbox_id</code> path parameter
     * @param params the query parameters
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListInboxRequestsResponse>> listInboxRequestsAsync(String inboxId, EventsListInboxRequestsParams params) {
        return Operations.listInboxRequestsAsync(client, inboxId, params);
    }

    /**
     * <code>GET /v1/webhooks/inboxes/{inbox_id}/requests</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListInboxRequests</code> on the <code>events</code> backend.
     *
     * @param inboxId the <code>inbox_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<ListInboxRequestsResponse> listInboxRequests(String inboxId) {
        return Operations.listInboxRequests(client, inboxId, EventsListInboxRequestsParams.builder().build());
    }

    /**
     * <code>GET /v1/webhooks/inboxes/{inbox_id}/requests</code>; needs scope <code>webhooks:read</code>. Transcoded from <code>/iohr.events.v1.EventsService/ListInboxRequests</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param inboxId the <code>inbox_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListInboxRequestsResponse>> listInboxRequestsAsync(String inboxId) {
        return Operations.listInboxRequestsAsync(client, inboxId, EventsListInboxRequestsParams.builder().build());
    }

    /**
     * Every item <code>GET /v1/webhooks/inboxes/{inbox_id}/requests</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @param inboxId the <code>inboxId</code> path parameter
     * @param params the query parameters; the page token is set for each page
     * @return the walk
     */
    public Pages<InboxRequest> allListInboxRequests(String inboxId, EventsListInboxRequestsParams params) {
        return Codegen.pages(token -> {
            var page = Operations.listInboxRequests(client, inboxId, new EventsListInboxRequestsParams(params.pageSize(), token != null ? token : params.pageToken())).value();
            return new Pages.Page<>(page.requests(), page.nextPageToken());
        });
    }

    /**
     * Every item <code>GET /v1/webhooks/inboxes/{inbox_id}/requests</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @param inboxId the <code>inboxId</code> path parameter
     * @return the walk
     */
    public Pages<InboxRequest> allListInboxRequests(String inboxId) {
        return allListInboxRequests(inboxId, EventsListInboxRequestsParams.builder().build());
    }

    /**
     * <code>PATCH /v1/webhooks/endpoints/{endpoint_id}</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/UpdateEndpoint</code> on the <code>events</code> backend.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @param body the request body
     * @return the answer, typed, and the raw one
     */
    public Response<Endpoint> updateEndpoint(String endpointId, UpdateEndpointRequest body) {
        return Operations.updateEndpoint(client, endpointId, body);
    }

    /**
     * <code>PATCH /v1/webhooks/endpoints/{endpoint_id}</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/UpdateEndpoint</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @param body the request body
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<Endpoint>> updateEndpointAsync(String endpointId, UpdateEndpointRequest body) {
        return Operations.updateEndpointAsync(client, endpointId, body);
    }

    /**
     * <code>POST /v1/webhooks/deliveries/{delivery_id}/retry</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/RetryDelivery</code> on the <code>events</code> backend.
     *
     * @param deliveryId the <code>delivery_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<RetryDeliveryResponse> retryDelivery(String deliveryId) {
        return Operations.retryDelivery(client, deliveryId);
    }

    /**
     * <code>POST /v1/webhooks/deliveries/{delivery_id}/retry</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/RetryDelivery</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param deliveryId the <code>delivery_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<RetryDeliveryResponse>> retryDeliveryAsync(String deliveryId) {
        return Operations.retryDeliveryAsync(client, deliveryId);
    }

    /**
     * <code>POST /v1/webhooks/endpoints</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/CreateEndpoint</code> on the <code>events</code> backend.
     *
     * @param body the request body
     * @return the answer, typed, and the raw one
     */
    public Response<CreateEndpointResponse> createEndpoint(CreateEndpointRequest body) {
        return Operations.createEndpoint(client, body);
    }

    /**
     * <code>POST /v1/webhooks/endpoints</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/CreateEndpoint</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param body the request body
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<CreateEndpointResponse>> createEndpointAsync(CreateEndpointRequest body) {
        return Operations.createEndpointAsync(client, body);
    }

    /**
     * <code>POST /v1/webhooks/endpoints/{endpoint_id}/rotate</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/RotateSecret</code> on the <code>events</code> backend.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<RotateSecretResponse> rotateSecret(String endpointId) {
        return Operations.rotateSecret(client, endpointId);
    }

    /**
     * <code>POST /v1/webhooks/endpoints/{endpoint_id}/rotate</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/RotateSecret</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<RotateSecretResponse>> rotateSecretAsync(String endpointId) {
        return Operations.rotateSecretAsync(client, endpointId);
    }

    /**
     * <code>POST /v1/webhooks/endpoints/{endpoint_id}/test</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/SendTest</code> on the <code>events</code> backend.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<SendTestResponse> sendTest(String endpointId) {
        return Operations.sendTest(client, endpointId);
    }

    /**
     * <code>POST /v1/webhooks/endpoints/{endpoint_id}/test</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/SendTest</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param endpointId the <code>endpoint_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<SendTestResponse>> sendTestAsync(String endpointId) {
        return Operations.sendTestAsync(client, endpointId);
    }

    /**
     * <code>POST /v1/webhooks/inboxes</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/CreateInbox</code> on the <code>events</code> backend.
     *
     * @param body the request body
     * @return the answer, typed, and the raw one
     */
    public Response<CreateInboxResponse> createInbox(CreateInboxRequest body) {
        return Operations.createInbox(client, body);
    }

    /**
     * <code>POST /v1/webhooks/inboxes</code>; needs scope <code>webhooks:write</code>. Transcoded from <code>/iohr.events.v1.EventsService/CreateInbox</code> on the <code>events</code> backend. On the client's executor.
     *
     * @param body the request body
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<CreateInboxResponse>> createInboxAsync(CreateInboxRequest body) {
        return Operations.createInboxAsync(client, body);
    }
}
