// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import hr.inorbit.sdk.Client;
import hr.inorbit.sdk.Response;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;

/**
 * Profile <code>acme-ci</code>: the operations its cut holds. <code>fromEnv()</code> reads <code>INORBIT_ACME_CI_TOKEN</code>, or <code>INORBIT_ACME_CI_KEY_ID</code>, <code>INORBIT_ACME_CI_KEY_SECRET</code> and <code>INORBIT_ACME_CI_SCOPES</code>, and nothing else.
 */
public final class AcmeCi {

    /** The profile's name. */
    public static final String PROFILE = "acme-ci";

    private final Client client;
    private final AcmeCiAccounts accounts;
    private final AcmeCiEvents events;
    private final AcmeCiRadar radar;

    /**
     * The profile on a client built for its credential.
     *
     * @param client the client
     */
    public AcmeCi(Client client) {
        this.client = Objects.requireNonNull(client, "client");
        this.accounts = new AcmeCiAccounts(client);
        this.events = new AcmeCiEvents(client);
        this.radar = new AcmeCiRadar(client);
    }

    /**
     * The profile with its credential from the environment.
     *
     * @return the profile
     * @throws hr.inorbit.sdk.errors.ConfigException naming the variables to set when no credential is there
     */
    public static AcmeCi fromEnv() {
        return new AcmeCi(Client.fromEnv("ACME_CI"));
    }

    /**
     * The profile from code, the environment, the <code>iohr</code> config file and login, and the defaults (docs/config.md).
     *
     * @return the profile
     * @throws hr.inorbit.sdk.errors.ConfigException listing every problem found, each with its setting and source
     */
    public static AcmeCi load() {
        return new AcmeCi(Client.builder().profileType("acme-ci").load());
    }

    /**
     * The client the profile calls with.
     *
     * @return the client
     */
    public Client client() {
        return client;
    }

    /**
     * The <code>accounts</code> operations.
     *
     * @return the handle
     */
    public AcmeCiAccounts accounts() {
        return accounts;
    }

    /**
     * The <code>events</code> operations.
     *
     * @return the handle
     */
    public AcmeCiEvents events() {
        return events;
    }

    /**
     * The <code>radar</code> operations.
     *
     * @return the handle
     */
    public AcmeCiRadar radar() {
        return radar;
    }

    /**
     * <code>GET /v1/me</code>; needs scope <code>identity:read</code>. A key needs scope <code>identity:read</code>.
     *
     * @return the answer, typed, and the raw one
     */
    public Response<Me> me() {
        return Operations.me(client);
    }

    /**
     * <code>GET /v1/me</code>; needs scope <code>identity:read</code>. A key needs scope <code>identity:read</code>. On the client's executor.
     *
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<Me>> meAsync() {
        return Operations.meAsync(client);
    }
}
