// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import hr.inorbit.sdk.Client;
import hr.inorbit.sdk.Response;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;

/**
 * The <code>accounts</code> operations profile <code>acme-ci</code> may call.
 */
public final class AcmeCiAccounts {

    private final Client client;

    AcmeCiAccounts(Client client) {
        this.client = Objects.requireNonNull(client, "client");
    }

    /**
     * <code>GET /v1/accounts/me</code>; needs scope <code>account:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetMe</code> on the <code>accounts</code> backend.
     *
     * @return the answer, typed, and the raw one
     */
    public Response<GetMeResponse> getMe() {
        return Operations.getMe(client);
    }

    /**
     * <code>GET /v1/accounts/me</code>; needs scope <code>account:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetMe</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<GetMeResponse>> getMeAsync() {
        return Operations.getMeAsync(client);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/units</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUnits</code> on the <code>accounts</code> backend.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<GetUnitsResponse> getUnits(String orgId) {
        return Operations.getUnits(client, orgId);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/units</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUnits</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<GetUnitsResponse>> getUnitsAsync(String orgId) {
        return Operations.getUnitsAsync(client, orgId);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/usage</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUsage</code> on the <code>accounts</code> backend.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @param params the query parameters
     * @return the answer, typed, and the raw one
     */
    public Response<GetUsageResponse> getUsage(String orgId, AccountsGetUsageParams params) {
        return Operations.getUsage(client, orgId, params);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/usage</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUsage</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @param params the query parameters
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<GetUsageResponse>> getUsageAsync(String orgId, AccountsGetUsageParams params) {
        return Operations.getUsageAsync(client, orgId, params);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/usage</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUsage</code> on the <code>accounts</code> backend.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<GetUsageResponse> getUsage(String orgId) {
        return Operations.getUsage(client, orgId, AccountsGetUsageParams.builder().build());
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/usage</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUsage</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<GetUsageResponse>> getUsageAsync(String orgId) {
        return Operations.getUsageAsync(client, orgId, AccountsGetUsageParams.builder().build());
    }

    /**
     * <code>GET /v1/accounts/units/categories</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/ListUnitCategories</code> on the <code>accounts</code> backend.
     *
     * @return the answer, typed, and the raw one
     */
    public Response<ListUnitCategoriesResponse> listUnitCategories() {
        return Operations.listUnitCategories(client);
    }

    /**
     * <code>GET /v1/accounts/units/categories</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/ListUnitCategories</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListUnitCategoriesResponse>> listUnitCategoriesAsync() {
        return Operations.listUnitCategoriesAsync(client);
    }
}
