// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.CreateEndpointResponse</code>
 *
 * @param endpoint the <code>endpoint</code> field; <code>null</code> when unset, and then left out on the wire
 * @param secret the <code>secret</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record CreateEndpointResponse(
        @JsonProperty("endpoint") Endpoint endpoint,
        @JsonProperty("secret") String secret) {}
