// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.CreateInboxResponse</code>
 *
 * @param inbox the <code>inbox</code> field; <code>null</code> when unset, and then left out on the wire
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record CreateInboxResponse(
        @JsonProperty("inbox") Inbox inbox) {}
