// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * <code>iohr.events.v1.DeleteInboxResponse</code>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DeleteInboxResponse() {}
