// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.radar.v1.DrillCode</code>
 *
 * @param output the <code>output</code> field
 * @param solution the <code>solution</code> field
 * @param starter the <code>starter</code> field
 * @param stub the <code>stub</code> field
 * @param tests the <code>tests</code> field
 * @param toolchain the <code>toolchain</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DrillCode(
        @JsonProperty("output") String output,
        @JsonProperty("solution") String solution,
        @JsonProperty("starter") String starter,
        @JsonProperty("stub") boolean stub,
        @JsonProperty("tests") String tests,
        @JsonProperty("toolchain") String toolchain) {}
