// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

/**
 * The query parameters of <code>GET /v1/events/events</code>.
 *
 * @param types <code>types</code>; <code>null</code> to leave it out
 * @param accountId <code>account_id</code>; <code>null</code> to leave it out
 */
public record EventsStreamEventsParams(
        String types,
        String accountId) {

    /**
     * A builder.
     *
     * @return a builder with every field unset
     */
    public static Builder builder() {
        return new Builder();
    }

    /** Builds a <code>EventsStreamEventsParams</code>. */
    public static final class Builder {
        private String types;
        private String accountId;

        private Builder() {}

        /**
         * Sets <code>types</code>.
         *
         * @param types the value
         * @return this builder
         */
        public Builder types(String types) {
            this.types = types;
            return this;
        }

        /**
         * Sets <code>accountId</code>.
         *
         * @param accountId the value
         * @return this builder
         */
        public Builder accountId(String accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * The value.
         *
         * @return the <code>EventsStreamEventsParams</code>
         */
        public EventsStreamEventsParams build() {
            return new EventsStreamEventsParams(types, accountId);
        }
    }
}
