// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.EventType</code>
 *
 * @param description the <code>description</code> field
 * @param schema the <code>schema</code> field
 * @param type the <code>type</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record EventType(
        @JsonProperty("description") String description,
        @JsonProperty("schema") String schema,
        @JsonProperty("type") String type) {}
