// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.radar.v1.Item</code>
 *
 * @param id the <code>id</code> field
 * @param language the <code>language</code> field
 * @param publishedAt the <code>published_at</code> field
 * @param source the <code>source</code> field
 * @param summary the <code>summary</code> field
 * @param title the <code>title</code> field
 * @param url the <code>url</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Item(
        @JsonProperty("id") @JsonFormat(shape = JsonFormat.Shape.STRING) long id,
        @JsonProperty("language") String language,
        @JsonProperty("published_at") String publishedAt,
        @JsonProperty("source") String source,
        @JsonProperty("summary") String summary,
        @JsonProperty("title") String title,
        @JsonProperty("url") String url) {}
