// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.accounts.v1.ListUnitCategoriesResponse</code>
 *
 * @param categories the <code>categories</code> field
 * @param nextPageToken the <code>next_page_token</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListUnitCategoriesResponse(
        @JsonProperty("categories") List<UnitCategory> categories,
        @JsonProperty("next_page_token") String nextPageToken) {}
