// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.radar.v1.ListDigestsResponse</code>
 *
 * @param digests the <code>digests</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListDigestsResponse(
        @JsonProperty("digests") List<Digest> digests) {}
