// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.events.v1.ListInboxRequestsResponse</code>
 *
 * @param inbox the <code>inbox</code> field; <code>null</code> when the answer leaves it out
 * @param requests the <code>requests</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListInboxRequestsResponse(
        @JsonProperty("inbox") Inbox inbox,
        @JsonProperty("requests") List<InboxRequest> requests) {}
