// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.events.v1.ListEventTypesResponse</code>
 *
 * @param types the <code>types</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListEventTypesResponse(
        @JsonProperty("types") List<EventType> types) {}
