// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.RotateSecretResponse</code>
 *
 * @param previousExpiresAt the <code>previous_expires_at</code> field
 * @param secret the <code>secret</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record RotateSecretResponse(
        @JsonProperty("previous_expires_at") String previousExpiresAt,
        @JsonProperty("secret") String secret) {}
