// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.SendTestResponse</code>
 *
 * @param delivery the <code>delivery</code> field; <code>null</code> when the answer leaves it out
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record SendTestResponse(
        @JsonProperty("delivery") Delivery delivery) {}
