// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * <code>iohr.events.v1.StreamEventsResponse</code>
 *
 * @param accountId the <code>account_id</code> field
 * @param data the <code>data</code> field
 * @param id the <code>id</code> field
 * @param occurredAt the <code>occurred_at</code> field
 * @param type the <code>type</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record StreamEventsResponse(
        @JsonProperty("account_id") String accountId,
        @JsonProperty("data") Map<String, String> data,
        @JsonProperty("id") String id,
        @JsonProperty("occurred_at") String occurredAt,
        @JsonProperty("type") String type) {}
