//! Swift golden tests: each case renders to exactly `tests/golden/<case>/expected/swift/`.
//! `IOHR_UPDATE_GOLDEN=1` rewrites the expected files; review the diff.
//! `compile_swift.rs` builds what they hold.

#![allow(
    clippy::unwrap_used,
    reason = "a fixture that does not load fails the test"
)]

mod support;

use iohr_codegen::{Language, Options};

use support::{CASES, check, render, text};

#[test]
fn every_case_matches_its_golden_files() {
    for case in CASES {
        check(case, Language::Swift, &Options::default());
    }
}

#[test]
fn rendering_is_deterministic() {
    let (_, a) = render("two-profiles", Language::Swift, &Options::default());
    let (_, b) = render("two-profiles", Language::Swift, &Options::default());
    let a: Vec<_> = a.iter().collect();
    let b: Vec<_> = b.iter().collect();
    assert_eq!(a, b);
}

#[test]
fn an_operation_is_constrained_to_the_profiles_whose_cut_holds_it() {
    let (_, files) = render("two-profiles", Language::Swift, &Options::default());
    let ops = text(&files, "Operations.swift");
    assert!(
        ops.contains("extension AccountsHandle where P: AllowsGetUsage {"),
        "{ops}"
    );
    assert!(ops.contains("public func getUsage(orgId: String"), "{ops}");
    let profiles = text(&files, "Profiles.swift");
    let acme = profiles.split("public enum AcmeCi").nth(1).unwrap();
    let acme = acme.split("public enum").next().unwrap();
    assert!(acme.contains("AllowsGetUsage"), "{acme}");
    assert!(
        acme.contains("public static let env = \"ACME_CI\""),
        "{acme}"
    );
    let personal = profiles.split("public enum Personal").nth(1).unwrap();
    assert!(!personal.contains("AllowsGetUsage"), "{personal}");
    assert!(
        ops.starts_with("// Generated by iohr sdk generate"),
        "{ops}"
    );
    assert!(ops.contains("import InOrbit\n"), "{ops}");
}

#[test]
fn the_runtime_surface_extends_the_runtime_profile() {
    let options = Options {
        in_package: true,
        ..Options::default()
    };
    let (_, files) = render("public", Language::Swift, &options);
    let profiles = text(&files, "Profiles.swift");
    assert!(profiles.contains("extension InOrbit.Public:"), "{profiles}");
    assert!(!profiles.contains("public enum Public"), "{profiles}");
    let ops = text(&files, "Operations.swift");
    assert!(!ops.contains("import InOrbit\n"), "{ops}");
    let (_, files) = render("write-scopes", Language::Swift, &Options::default());
    let ops = text(&files, "Operations.swift");
    assert!(
        ops.contains("op.body = try InOrbit.Codegen.json(body)"),
        "{ops}"
    );
    assert!(ops.contains("method: .post"), "{ops}");
}

#[test]
fn runtime_names_the_module() {
    let options = Options {
        runtime: Some("InOrbitFork".into()),
        ..Options::default()
    };
    let (_, files) = render("two-profiles", Language::Swift, &options);
    let ops = text(&files, "Operations.swift");
    assert!(ops.contains("import InOrbitFork\n"), "{ops}");
    assert!(ops.contains("InOrbitFork.Client"), "{ops}");
}
