//! Go golden tests: each case renders to exactly `tests/golden/<case>/expected/go/`,
//! for the import path `example.com/app/iohr`. `IOHR_UPDATE_GOLDEN=1` rewrites the
//! expected files; review the diff. `compile_go.rs` builds what they hold.

#![allow(
    clippy::unwrap_used,
    reason = "a fixture that does not load fails the test"
)]

mod support;

use iohr_codegen::{Language, Options};

use support::{CASES, check, render, text};

fn options() -> Options {
    Options {
        package: Some("example.com/app/iohr".into()),
        ..Options::default()
    }
}

#[test]
fn every_case_matches_its_golden_files() {
    for case in CASES {
        check(case, Language::Go, &options());
    }
}

#[test]
fn a_profile_package_holds_only_its_operations() {
    let (_, files) = render("two-profiles", Language::Go, &options());
    let acme = text(&files, "acmeci/client.go");
    assert!(acme.contains("func (h Accounts) GetUsage("), "{acme}");
    assert!(
        acme.contains("inorbit.FromEnv(\"ACME_CI\", opts...)"),
        "{acme}"
    );
    let personal = text(&files, "personal/client.go");
    assert!(!personal.contains("GetUsage("), "{personal}");
    assert!(personal.starts_with("// Code generated by iohr sdk generate for cuts "));
    assert!(personal.lines().next().unwrap().ends_with("; DO NOT EDIT."));
}

#[test]
fn int64_fields_use_the_runtime_type_and_writes_send_their_body() {
    let (_, files) = render("public", Language::Go, &options());
    let models = text(&files, "models/models.go");
    assert!(models.contains("inorbit.Int64"), "{models}");
    let (_, files) = render("write-scopes", Language::Go, &options());
    let ops = text(&files, "internal/ops/ops.go");
    assert!(ops.contains("body models.CreateEndpointRequest"), "{ops}");
    assert!(ops.contains("Method: \"POST\""), "{ops}");
}

#[test]
fn a_go_surface_needs_an_import_path() {
    let api = support::load("public");
    let err = iohr_codegen::render(Language::Go, &api, &Options::default()).unwrap_err();
    assert!(err.to_string().contains("--package"), "{err}");
}

#[test]
fn rendering_is_deterministic() {
    let (_, a) = render("two-profiles", Language::Go, &options());
    let (_, b) = render("two-profiles", Language::Go, &options());
    assert_eq!(a, b);
}
