//! C# golden tests: each case renders to exactly `tests/golden/<case>/expected/csharp/`.
//! `IOHR_UPDATE_GOLDEN=1` rewrites the expected files; review the diff.
//! `compile_csharp.rs` builds what they hold.

#![allow(
    clippy::unwrap_used,
    reason = "a fixture that does not load fails the test"
)]

mod support;

use iohr_codegen::{Language, Options};

use support::{CASES, check, render, text};

#[test]
fn every_case_matches_its_golden_files() {
    for case in CASES {
        check(case, Language::CSharp, &Options::default());
    }
}

#[test]
fn rendering_is_deterministic() {
    let (_, a) = render("two-profiles", Language::CSharp, &Options::default());
    let (_, b) = render("two-profiles", Language::CSharp, &Options::default());
    let a: Vec<_> = a.iter().collect();
    let b: Vec<_> = b.iter().collect();
    assert_eq!(a, b);
}

#[test]
fn an_operation_is_constrained_to_the_profiles_whose_cut_holds_it() {
    let (_, files) = render("two-profiles", Language::CSharp, &Options::default());
    let ops = text(&files, "Operations.cs");
    assert!(
        ops.contains("GetUsageAsync<TProfile>(this AccountsHandle<TProfile> accounts"),
        "{ops}"
    );
    assert!(ops.contains("where TProfile : IGetUsage"), "{ops}");
    let profiles = text(&files, "Profiles.cs");
    let acme = profiles.split("public sealed class AcmeCi").nth(1).unwrap();
    let acme = acme.split("public sealed class").next().unwrap();
    assert!(acme.contains("IGetUsage"), "{acme}");
    let personal = profiles
        .split("public sealed class Personal")
        .nth(1)
        .unwrap();
    assert!(!personal.contains("IGetUsage"), "{personal}");
    assert!(acme.contains("Env => \"ACME_CI\""), "{acme}");
}

#[test]
fn the_runtime_surface_extends_the_runtime_profile() {
    let options = Options {
        in_package: true,
        ..Options::default()
    };
    let (_, files) = render("public", Language::CSharp, &options);
    let profiles = text(&files, "Profiles.cs");
    assert!(profiles.contains("namespace InOrbit.Sdk.Api"), "{profiles}");
    assert!(
        profiles.contains("public sealed partial class PublicProfile"),
        "{profiles}"
    );
    let (_, files) = render("write-scopes", Language::CSharp, &Options::default());
    let ops = text(&files, "Operations.cs");
    assert!(ops.contains("Codegen.WithJson(operation, body)"), "{ops}");
    assert!(ops.contains("Method.Post"), "{ops}");
    let models = text(&files, "Models.cs");
    assert!(models.starts_with("// <auto-generated>"), "{models}");
    assert!(models.contains("#nullable enable"), "{models}");
}

#[test]
fn package_names_the_namespace() {
    let options = Options {
        package: Some("Acme.Api".into()),
        ..Options::default()
    };
    let (_, files) = render("two-profiles", Language::CSharp, &options);
    assert!(text(&files, "Models.cs").contains("namespace Acme.Api"));
}
