// Code generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; DO NOT EDIT.

// Package personal is the InOrbit API surface for profile personal: only the operations its cut holds, so a call it may not make does not build. FromEnv reads INORBIT_PERSONAL_TOKEN, or INORBIT_PERSONAL_KEY_ID, INORBIT_PERSONAL_KEY_SECRET and INORBIT_PERSONAL_SCOPES, and nothing else.
package personal

import (
	"context"

	"example.com/app/iohr/internal/ops"
	"example.com/app/iohr/models"
	inorbit "github.com/inorbithr/sdk/go"
	"github.com/inorbithr/sdk/go/codegen"
)

// The surface was generated for the runtime's contract 1: a runtime with another contract fails to build here, so run iohr sdk generate again.
const _ = codegen.V1

// Profile is the profile's name.
const Profile = "personal"

// Client calls the operations profile personal may call.
type Client struct {
	c *inorbit.Client
}

// New returns the profile's surface on c, a client built for its credential.
func New(c *inorbit.Client) *Client {
	return &Client{c: c}
}

// FromEnv returns the profile's surface with its credential from the environment; opts apply after it.
func FromEnv(opts ...inorbit.Option) (*Client, error) {
	c, err := inorbit.FromEnv("PERSONAL", opts...)
	if err != nil {
		return nil, err
	}
	return New(c), nil
}

// Runtime returns the client underneath, for a raw call with Send.
func (p *Client) Runtime() *inorbit.Client {
	return p.c
}

// Me calls GET /v1/me; needs scope identity:read. A key needs scope `identity:read`.
func (p *Client) Me(ctx context.Context) (*inorbit.Response[models.Me], error) {
	return ops.Me(ctx, p.c)
}

// Radar returns the radar operations the profile may call.
func (p *Client) Radar() Radar {
	return Radar{c: p.c}
}

// Radar holds the radar operations profile personal may call.
type Radar struct {
	c *inorbit.Client
}

// ListDigests calls GET /v1/radar/digests; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/ListDigests` on the `radar` backend.
func (h Radar) ListDigests(ctx context.Context, params *models.RadarListDigestsParams) (*inorbit.Response[models.ListDigestsResponse], error) {
	return ops.ListDigests(ctx, h.c, params)
}

// GetDigest calls GET /v1/radar/digests/{id}; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/GetDigest` on the `radar` backend.
func (h Radar) GetDigest(ctx context.Context, id string) (*inorbit.Response[models.GetDigestResponse], error) {
	return ops.GetDigest(ctx, h.c, id)
}

// ListItems calls GET /v1/radar/items; needs scope radar:read. Transcoded from `/iohr.radar.v1.RadarService/ListItems` on the `radar` backend.
func (h Radar) ListItems(ctx context.Context, params *models.RadarListItemsParams) (*inorbit.Response[models.ListItemsResponse], error) {
	return ops.ListItems(ctx, h.c, params)
}
