// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
// swiftlint:disable all

import Foundation
import InOrbit

/// A surface generated for another runtime contract fails to compile here: run `iohr sdk generate` again.
private enum SurfaceContract {
    static let version: InOrbit.Codegen.Version1.Type = InOrbit.Codegen.Version1.self
}

/// A profile whose cut holds `DELETE /v1/webhooks/endpoints/{endpoint_id}`.
public protocol AllowsDeleteEndpoint: InOrbit.Profile {}

/// A profile whose cut holds `DELETE /v1/webhooks/inboxes/{inbox_id}`.
public protocol AllowsDeleteInbox: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/accounts/me`.
public protocol AllowsGetMe: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/accounts/orgs/{org_id}/units`.
public protocol AllowsGetUnits: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/accounts/orgs/{org_id}/usage`.
public protocol AllowsGetUsage: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/accounts/units/categories`.
public protocol AllowsListUnitCategories: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/events/events`.
public protocol AllowsStreamEvents: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/events/types`.
public protocol AllowsListEventTypes: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/me`.
public protocol AllowsMe: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/radar/digests`.
public protocol AllowsListDigests: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/radar/digests/{id}`.
public protocol AllowsGetDigest: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/radar/items`.
public protocol AllowsListItems: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/webhooks/endpoints`.
public protocol AllowsListEndpoints: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/webhooks/endpoints/{endpoint_id}`.
public protocol AllowsGetEndpoint: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/webhooks/endpoints/{endpoint_id}/deliveries`.
public protocol AllowsListDeliveries: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/webhooks/inboxes`.
public protocol AllowsListInboxes: InOrbit.Profile {}

/// A profile whose cut holds `GET /v1/webhooks/inboxes/{inbox_id}/requests`.
public protocol AllowsListInboxRequests: InOrbit.Profile {}

/// A profile whose cut holds `PATCH /v1/webhooks/endpoints/{endpoint_id}`.
public protocol AllowsUpdateEndpoint: InOrbit.Profile {}

/// A profile whose cut holds `POST /v1/webhooks/deliveries/{delivery_id}/retry`.
public protocol AllowsRetryDelivery: InOrbit.Profile {}

/// A profile whose cut holds `POST /v1/webhooks/endpoints`.
public protocol AllowsCreateEndpoint: InOrbit.Profile {}

/// A profile whose cut holds `POST /v1/webhooks/endpoints/{endpoint_id}/rotate`.
public protocol AllowsRotateSecret: InOrbit.Profile {}

/// A profile whose cut holds `POST /v1/webhooks/endpoints/{endpoint_id}/test`.
public protocol AllowsSendTest: InOrbit.Profile {}

/// A profile whose cut holds `POST /v1/webhooks/inboxes`.
public protocol AllowsCreateInbox: InOrbit.Profile {}

/// A profile whose cut holds an operation of `accounts`.
public protocol AllowsAccountsArea: InOrbit.Profile {}

/// A profile whose cut holds an operation of `events`.
public protocol AllowsEventsArea: InOrbit.Profile {}

/// A profile whose cut holds an operation of `radar`.
public protocol AllowsRadarArea: InOrbit.Profile {}

/// The query parameters of `GET /v1/accounts/orgs/{org_id}/usage`.
public struct AccountsGetUsageParams: Sendable {
    public var from: String?
    public var to: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        from: String? = nil,
        to: String? = nil
    ) {
        self.from = from
        self.to = to
    }
}

/// The query parameters of `GET /v1/accounts/units/categories`.
public struct AccountsListUnitCategoriesParams: Sendable {
    public var pageSize: Int32?
    public var pageToken: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        pageSize: Int32? = nil,
        pageToken: String? = nil
    ) {
        self.pageSize = pageSize
        self.pageToken = pageToken
    }
}

/// The query parameters of `GET /v1/events/events`.
public struct EventsStreamEventsParams: Sendable {
    public var types: String?
    public var accountId: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        types: String? = nil,
        accountId: String? = nil
    ) {
        self.types = types
        self.accountId = accountId
    }
}

/// The query parameters of `GET /v1/events/types`.
public struct EventsListEventTypesParams: Sendable {
    public var pageSize: Int32?
    public var pageToken: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        pageSize: Int32? = nil,
        pageToken: String? = nil
    ) {
        self.pageSize = pageSize
        self.pageToken = pageToken
    }
}

/// The query parameters of `GET /v1/radar/digests`.
public struct RadarListDigestsParams: Sendable {
    public var language: String?
    public var lang: String?
    public var limit: Int32?
    public var includeDrafts: Bool?
    public var beforeWeek: String?
    public var pageSize: Int32?
    public var pageToken: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        language: String? = nil,
        lang: String? = nil,
        limit: Int32? = nil,
        includeDrafts: Bool? = nil,
        beforeWeek: String? = nil,
        pageSize: Int32? = nil,
        pageToken: String? = nil
    ) {
        self.language = language
        self.lang = lang
        self.limit = limit
        self.includeDrafts = includeDrafts
        self.beforeWeek = beforeWeek
        self.pageSize = pageSize
        self.pageToken = pageToken
    }
}

/// The query parameters of `GET /v1/radar/items`.
public struct RadarListItemsParams: Sendable {
    public var language: String?
    public var limit: Int32?
    public var pageSize: Int32?
    public var pageToken: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        language: String? = nil,
        limit: Int32? = nil,
        pageSize: Int32? = nil,
        pageToken: String? = nil
    ) {
        self.language = language
        self.limit = limit
        self.pageSize = pageSize
        self.pageToken = pageToken
    }
}

/// The query parameters of `GET /v1/webhooks/endpoints`.
public struct EventsListEndpointsParams: Sendable {
    public var accountId: String?
    public var pageSize: Int32?
    public var pageToken: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        accountId: String? = nil,
        pageSize: Int32? = nil,
        pageToken: String? = nil
    ) {
        self.accountId = accountId
        self.pageSize = pageSize
        self.pageToken = pageToken
    }
}

/// The query parameters of `GET /v1/webhooks/endpoints/{endpoint_id}/deliveries`.
public struct EventsListDeliveriesParams: Sendable {
    public var status: String?
    public var pageToken: String?
    public var pageSize: Int32?

    /// The parameters; what is left `nil` is not sent.
    public init(
        status: String? = nil,
        pageToken: String? = nil,
        pageSize: Int32? = nil
    ) {
        self.status = status
        self.pageToken = pageToken
        self.pageSize = pageSize
    }
}

/// The query parameters of `GET /v1/webhooks/inboxes`.
public struct EventsListInboxesParams: Sendable {
    public var accountId: String?
    public var pageSize: Int32?
    public var pageToken: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        accountId: String? = nil,
        pageSize: Int32? = nil,
        pageToken: String? = nil
    ) {
        self.accountId = accountId
        self.pageSize = pageSize
        self.pageToken = pageToken
    }
}

/// The query parameters of `GET /v1/webhooks/inboxes/{inbox_id}/requests`.
public struct EventsListInboxRequestsParams: Sendable {
    public var pageSize: Int32?
    public var pageToken: String?

    /// The parameters; what is left `nil` is not sent.
    public init(
        pageSize: Int32? = nil,
        pageToken: String? = nil
    ) {
        self.pageSize = pageSize
        self.pageToken = pageToken
    }
}

/// The `accounts` operations, on a profile's client.
public struct AccountsHandle<P: InOrbit.Profile>: Sendable {
    let client: InOrbit.Client<P>
}

extension InOrbit.Client where P: AllowsAccountsArea {
    /// The `accounts` operations of the profile's cut.
    public var accounts: AccountsHandle<P> {
        AccountsHandle(client: self)
    }
}

/// The `events` operations, on a profile's client.
public struct EventsHandle<P: InOrbit.Profile>: Sendable {
    let client: InOrbit.Client<P>
}

extension InOrbit.Client where P: AllowsEventsArea {
    /// The `events` operations of the profile's cut.
    public var events: EventsHandle<P> {
        EventsHandle(client: self)
    }
}

/// The `radar` operations, on a profile's client.
public struct RadarHandle<P: InOrbit.Profile>: Sendable {
    let client: InOrbit.Client<P>
}

extension InOrbit.Client where P: AllowsRadarArea {
    /// The `radar` operations of the profile's cut.
    public var radar: RadarHandle<P> {
        RadarHandle(client: self)
    }
}

extension InOrbit.Client where P: AllowsMe {
    /// `GET /v1/me`; needs scope `identity:read`. A key needs scope `identity:read`.
    @discardableResult
    public func me(options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<Me> {
        let op = InOrbit.Codegen.Operation(
            name: "me",
            method: .get,
            path: "/v1/me",
            template: "/v1/me",
            scopes: ["identity:read"]
        )
        return try await self.request(op, as: Me.self, options: options)
    }
}

extension AccountsHandle where P: AllowsGetMe {
    /// `GET /v1/accounts/me`; needs scope `account:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetMe` on the `accounts` backend.
    @discardableResult
    public func getMe(options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<GetMeResponse> {
        let op = InOrbit.Codegen.Operation(
            name: "accounts.get_me",
            method: .get,
            path: "/v1/accounts/me",
            template: "/v1/accounts/me",
            scopes: ["account:read"]
        )
        return try await client.request(op, as: GetMeResponse.self, options: options)
    }
}

extension AccountsHandle where P: AllowsGetUnits {
    /// `GET /v1/accounts/orgs/{org_id}/units`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetUnits` on the `accounts` backend.
    @discardableResult
    public func getUnits(orgId: String, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<GetUnitsResponse> {
        let op = InOrbit.Codegen.Operation(
            name: "accounts.get_units",
            method: .get,
            path: "/v1/accounts/orgs/\(InOrbit.Codegen.pathSegment(orgId))/units",
            template: "/v1/accounts/orgs/{org_id}/units",
            scopes: ["usage:read"]
        )
        return try await client.request(op, as: GetUnitsResponse.self, options: options)
    }
}

extension AccountsHandle where P: AllowsGetUsage {
    /// `GET /v1/accounts/orgs/{org_id}/usage`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetUsage` on the `accounts` backend.
    @discardableResult
    public func getUsage(orgId: String, _ query: AccountsGetUsageParams = AccountsGetUsageParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<GetUsageResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "accounts.get_usage",
            method: .get,
            path: "/v1/accounts/orgs/\(InOrbit.Codegen.pathSegment(orgId))/usage",
            template: "/v1/accounts/orgs/{org_id}/usage",
            scopes: ["usage:read"]
        )
        op.query = [
            ("from", InOrbit.Codegen.queryValues(query.from)),
            ("to", InOrbit.Codegen.queryValues(query.to)),
        ]
        return try await client.request(op, as: GetUsageResponse.self, options: options)
    }
}

extension AccountsHandle where P: AllowsListUnitCategories {
    /// `GET /v1/accounts/units/categories`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/ListUnitCategories` on the `accounts` backend.
    @discardableResult
    public func listUnitCategories(_ query: AccountsListUnitCategoriesParams = AccountsListUnitCategoriesParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<ListUnitCategoriesResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "accounts.list_unit_categories",
            method: .get,
            path: "/v1/accounts/units/categories",
            template: "/v1/accounts/units/categories",
            scopes: ["usage:read"]
        )
        op.query = [
            ("page_size", InOrbit.Codegen.queryValues(query.pageSize)),
            ("page_token", InOrbit.Codegen.queryValues(query.pageToken)),
        ]
        return try await client.request(op, as: ListUnitCategoriesResponse.self, options: options)
    }

    /// Every item `GET /v1/accounts/units/categories` answers, page after page, following `next_page_token` until the last page; for `for try await`. It throws the first error, and fetches nothing more once the loop stops.
    public func allListUnitCategories(_ query: AccountsListUnitCategoriesParams = AccountsListUnitCategoriesParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<UnitCategory, any Error> {
        InOrbit.Codegen.pages { token in
            var page = query
            if let token { page.pageToken = token }
            let value = try await self.listUnitCategories(page, options: options).value
            return (value.categories, value.nextPageToken)
        }
    }
}

extension EventsHandle where P: AllowsDeleteEndpoint {
    /// `DELETE /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/DeleteEndpoint` on the `events` backend.
    @discardableResult
    public func deleteEndpoint(endpointId: String, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<DeleteEndpointResponse> {
        let op = InOrbit.Codegen.Operation(
            name: "events.delete_endpoint",
            method: .delete,
            path: "/v1/webhooks/endpoints/\(InOrbit.Codegen.pathSegment(endpointId))",
            template: "/v1/webhooks/endpoints/{endpoint_id}",
            scopes: ["webhooks:write"]
        )
        return try await client.request(op, as: DeleteEndpointResponse.self, options: options)
    }
}

extension EventsHandle where P: AllowsDeleteInbox {
    /// `DELETE /v1/webhooks/inboxes/{inbox_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/DeleteInbox` on the `events` backend.
    @discardableResult
    public func deleteInbox(inboxId: String, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<DeleteInboxResponse> {
        let op = InOrbit.Codegen.Operation(
            name: "events.delete_inbox",
            method: .delete,
            path: "/v1/webhooks/inboxes/\(InOrbit.Codegen.pathSegment(inboxId))",
            template: "/v1/webhooks/inboxes/{inbox_id}",
            scopes: ["webhooks:write"]
        )
        return try await client.request(op, as: DeleteInboxResponse.self, options: options)
    }
}

extension EventsHandle where P: AllowsStreamEvents {
    /// `GET /v1/events/events`; needs scope `events:read`. Transcoded from `/iohr.events.v1.EventsService/StreamEvents` on the `events` backend.
    /// A stream: each event as it happens, until the server ends it; it opens on the first step of `for try await`.
    public func streamEvents(_ query: EventsStreamEventsParams = EventsStreamEventsParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<StreamEventsResponse, any Error> {
        var op = InOrbit.Codegen.Operation(
            name: "events.stream_events",
            method: .get,
            path: "/v1/events/events",
            template: "/v1/events/events",
            scopes: ["events:read"]
        )
        op.query = [
            ("types", InOrbit.Codegen.queryValues(query.types)),
            ("account_id", InOrbit.Codegen.queryValues(query.accountId)),
        ]
        op.rpc = "iohr.events.v1.EventsService/StreamEvents"
        return client.stream(op, as: StreamEventsResponse.self, options: options)
    }
}

extension EventsHandle where P: AllowsListEventTypes {
    /// `GET /v1/events/types`; needs scope `events:read`. Transcoded from `/iohr.events.v1.EventsService/ListEventTypes` on the `events` backend.
    @discardableResult
    public func listEventTypes(_ query: EventsListEventTypesParams = EventsListEventTypesParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<ListEventTypesResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.list_event_types",
            method: .get,
            path: "/v1/events/types",
            template: "/v1/events/types",
            scopes: ["events:read"]
        )
        op.query = [
            ("page_size", InOrbit.Codegen.queryValues(query.pageSize)),
            ("page_token", InOrbit.Codegen.queryValues(query.pageToken)),
        ]
        return try await client.request(op, as: ListEventTypesResponse.self, options: options)
    }

    /// Every item `GET /v1/events/types` answers, page after page, following `next_page_token` until the last page; for `for try await`. It throws the first error, and fetches nothing more once the loop stops.
    public func allListEventTypes(_ query: EventsListEventTypesParams = EventsListEventTypesParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<EventType, any Error> {
        InOrbit.Codegen.pages { token in
            var page = query
            if let token { page.pageToken = token }
            let value = try await self.listEventTypes(page, options: options).value
            return (value.types, value.nextPageToken)
        }
    }
}

extension EventsHandle where P: AllowsListEndpoints {
    /// `GET /v1/webhooks/endpoints`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListEndpoints` on the `events` backend.
    @discardableResult
    public func listEndpoints(_ query: EventsListEndpointsParams = EventsListEndpointsParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<ListEndpointsResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.list_endpoints",
            method: .get,
            path: "/v1/webhooks/endpoints",
            template: "/v1/webhooks/endpoints",
            scopes: ["webhooks:read"]
        )
        op.query = [
            ("account_id", InOrbit.Codegen.queryValues(query.accountId)),
            ("page_size", InOrbit.Codegen.queryValues(query.pageSize)),
            ("page_token", InOrbit.Codegen.queryValues(query.pageToken)),
        ]
        return try await client.request(op, as: ListEndpointsResponse.self, options: options)
    }

    /// Every item `GET /v1/webhooks/endpoints` answers, page after page, following `next_page_token` until the last page; for `for try await`. It throws the first error, and fetches nothing more once the loop stops.
    public func allListEndpoints(_ query: EventsListEndpointsParams = EventsListEndpointsParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<Endpoint, any Error> {
        InOrbit.Codegen.pages { token in
            var page = query
            if let token { page.pageToken = token }
            let value = try await self.listEndpoints(page, options: options).value
            return (value.endpoints, value.nextPageToken)
        }
    }
}

extension EventsHandle where P: AllowsGetEndpoint {
    /// `GET /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/GetEndpoint` on the `events` backend.
    @discardableResult
    public func getEndpoint(endpointId: String, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<Endpoint> {
        let op = InOrbit.Codegen.Operation(
            name: "events.get_endpoint",
            method: .get,
            path: "/v1/webhooks/endpoints/\(InOrbit.Codegen.pathSegment(endpointId))",
            template: "/v1/webhooks/endpoints/{endpoint_id}",
            scopes: ["webhooks:read"]
        )
        return try await client.request(op, as: Endpoint.self, options: options)
    }
}

extension EventsHandle where P: AllowsListDeliveries {
    /// `GET /v1/webhooks/endpoints/{endpoint_id}/deliveries`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListDeliveries` on the `events` backend.
    @discardableResult
    public func listDeliveries(endpointId: String, _ query: EventsListDeliveriesParams = EventsListDeliveriesParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<ListDeliveriesResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.list_deliveries",
            method: .get,
            path: "/v1/webhooks/endpoints/\(InOrbit.Codegen.pathSegment(endpointId))/deliveries",
            template: "/v1/webhooks/endpoints/{endpoint_id}/deliveries",
            scopes: ["webhooks:read"]
        )
        op.query = [
            ("status", InOrbit.Codegen.queryValues(query.status)),
            ("page_token", InOrbit.Codegen.queryValues(query.pageToken)),
            ("page_size", InOrbit.Codegen.queryValues(query.pageSize)),
        ]
        return try await client.request(op, as: ListDeliveriesResponse.self, options: options)
    }

    /// Every item `GET /v1/webhooks/endpoints/{endpoint_id}/deliveries` answers, page after page, following `next_page_token` until the last page; for `for try await`. It throws the first error, and fetches nothing more once the loop stops.
    public func allListDeliveries(endpointId: String, _ query: EventsListDeliveriesParams = EventsListDeliveriesParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<Delivery, any Error> {
        InOrbit.Codegen.pages { token in
            var page = query
            if let token { page.pageToken = token }
            let value = try await self.listDeliveries(endpointId: endpointId, page, options: options).value
            return (value.deliveries, value.nextPageToken)
        }
    }
}

extension EventsHandle where P: AllowsListInboxes {
    /// `GET /v1/webhooks/inboxes`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListInboxes` on the `events` backend.
    @discardableResult
    public func listInboxes(_ query: EventsListInboxesParams = EventsListInboxesParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<ListInboxesResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.list_inboxes",
            method: .get,
            path: "/v1/webhooks/inboxes",
            template: "/v1/webhooks/inboxes",
            scopes: ["webhooks:read"]
        )
        op.query = [
            ("account_id", InOrbit.Codegen.queryValues(query.accountId)),
            ("page_size", InOrbit.Codegen.queryValues(query.pageSize)),
            ("page_token", InOrbit.Codegen.queryValues(query.pageToken)),
        ]
        return try await client.request(op, as: ListInboxesResponse.self, options: options)
    }

    /// Every item `GET /v1/webhooks/inboxes` answers, page after page, following `next_page_token` until the last page; for `for try await`. It throws the first error, and fetches nothing more once the loop stops.
    public func allListInboxes(_ query: EventsListInboxesParams = EventsListInboxesParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<Inbox, any Error> {
        InOrbit.Codegen.pages { token in
            var page = query
            if let token { page.pageToken = token }
            let value = try await self.listInboxes(page, options: options).value
            return (value.inboxes, value.nextPageToken)
        }
    }
}

extension EventsHandle where P: AllowsListInboxRequests {
    /// `GET /v1/webhooks/inboxes/{inbox_id}/requests`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListInboxRequests` on the `events` backend.
    @discardableResult
    public func listInboxRequests(inboxId: String, _ query: EventsListInboxRequestsParams = EventsListInboxRequestsParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<ListInboxRequestsResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.list_inbox_requests",
            method: .get,
            path: "/v1/webhooks/inboxes/\(InOrbit.Codegen.pathSegment(inboxId))/requests",
            template: "/v1/webhooks/inboxes/{inbox_id}/requests",
            scopes: ["webhooks:read"]
        )
        op.query = [
            ("page_size", InOrbit.Codegen.queryValues(query.pageSize)),
            ("page_token", InOrbit.Codegen.queryValues(query.pageToken)),
        ]
        return try await client.request(op, as: ListInboxRequestsResponse.self, options: options)
    }

    /// Every item `GET /v1/webhooks/inboxes/{inbox_id}/requests` answers, page after page, following `next_page_token` until the last page; for `for try await`. It throws the first error, and fetches nothing more once the loop stops.
    public func allListInboxRequests(inboxId: String, _ query: EventsListInboxRequestsParams = EventsListInboxRequestsParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<InboxRequest, any Error> {
        InOrbit.Codegen.pages { token in
            var page = query
            if let token { page.pageToken = token }
            let value = try await self.listInboxRequests(inboxId: inboxId, page, options: options).value
            return (value.requests, value.nextPageToken)
        }
    }
}

extension EventsHandle where P: AllowsUpdateEndpoint {
    /// `PATCH /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/UpdateEndpoint` on the `events` backend.
    @discardableResult
    public func updateEndpoint(endpointId: String, body: UpdateEndpointRequest, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<Endpoint> {
        var op = InOrbit.Codegen.Operation(
            name: "events.update_endpoint",
            method: .patch,
            path: "/v1/webhooks/endpoints/\(InOrbit.Codegen.pathSegment(endpointId))",
            template: "/v1/webhooks/endpoints/{endpoint_id}",
            scopes: ["webhooks:write"]
        )
        op.body = try InOrbit.Codegen.json(body)
        return try await client.request(op, as: Endpoint.self, options: options)
    }
}

extension EventsHandle where P: AllowsRetryDelivery {
    /// `POST /v1/webhooks/deliveries/{delivery_id}/retry`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RetryDelivery` on the `events` backend.
    @discardableResult
    public func retryDelivery(deliveryId: String, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<RetryDeliveryResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.retry_delivery",
            method: .post,
            path: "/v1/webhooks/deliveries/\(InOrbit.Codegen.pathSegment(deliveryId))/retry",
            template: "/v1/webhooks/deliveries/{delivery_id}/retry",
            scopes: ["webhooks:write"]
        )
        op.takesIdempotencyKey = true
        return try await client.request(op, as: RetryDeliveryResponse.self, options: options)
    }
}

extension EventsHandle where P: AllowsCreateEndpoint {
    /// `POST /v1/webhooks/endpoints`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/CreateEndpoint` on the `events` backend.
    @discardableResult
    public func createEndpoint(body: CreateEndpointRequest, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<CreateEndpointResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.create_endpoint",
            method: .post,
            path: "/v1/webhooks/endpoints",
            template: "/v1/webhooks/endpoints",
            scopes: ["webhooks:write"]
        )
        op.takesIdempotencyKey = true
        op.body = try InOrbit.Codegen.json(body)
        return try await client.request(op, as: CreateEndpointResponse.self, options: options)
    }
}

extension EventsHandle where P: AllowsRotateSecret {
    /// `POST /v1/webhooks/endpoints/{endpoint_id}/rotate`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RotateSecret` on the `events` backend.
    @discardableResult
    public func rotateSecret(endpointId: String, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<RotateSecretResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.rotate_secret",
            method: .post,
            path: "/v1/webhooks/endpoints/\(InOrbit.Codegen.pathSegment(endpointId))/rotate",
            template: "/v1/webhooks/endpoints/{endpoint_id}/rotate",
            scopes: ["webhooks:write"]
        )
        op.takesIdempotencyKey = true
        return try await client.request(op, as: RotateSecretResponse.self, options: options)
    }
}

extension EventsHandle where P: AllowsSendTest {
    /// `POST /v1/webhooks/endpoints/{endpoint_id}/test`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/SendTest` on the `events` backend.
    @discardableResult
    public func sendTest(endpointId: String, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<SendTestResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.send_test",
            method: .post,
            path: "/v1/webhooks/endpoints/\(InOrbit.Codegen.pathSegment(endpointId))/test",
            template: "/v1/webhooks/endpoints/{endpoint_id}/test",
            scopes: ["webhooks:write"]
        )
        op.takesIdempotencyKey = true
        return try await client.request(op, as: SendTestResponse.self, options: options)
    }
}

extension EventsHandle where P: AllowsCreateInbox {
    /// `POST /v1/webhooks/inboxes`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/CreateInbox` on the `events` backend.
    @discardableResult
    public func createInbox(body: CreateInboxRequest, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<CreateInboxResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "events.create_inbox",
            method: .post,
            path: "/v1/webhooks/inboxes",
            template: "/v1/webhooks/inboxes",
            scopes: ["webhooks:write"]
        )
        op.takesIdempotencyKey = true
        op.body = try InOrbit.Codegen.json(body)
        return try await client.request(op, as: CreateInboxResponse.self, options: options)
    }
}

extension RadarHandle where P: AllowsListDigests {
    /// `GET /v1/radar/digests`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/ListDigests` on the `radar` backend.
    @discardableResult
    public func listDigests(_ query: RadarListDigestsParams = RadarListDigestsParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<ListDigestsResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "radar.list_digests",
            method: .get,
            path: "/v1/radar/digests",
            template: "/v1/radar/digests",
            scopes: ["radar:read"]
        )
        op.query = [
            ("language", InOrbit.Codegen.queryValues(query.language)),
            ("lang", InOrbit.Codegen.queryValues(query.lang)),
            ("limit", InOrbit.Codegen.queryValues(query.limit)),
            ("include_drafts", InOrbit.Codegen.queryValues(query.includeDrafts)),
            ("before_week", InOrbit.Codegen.queryValues(query.beforeWeek)),
            ("page_size", InOrbit.Codegen.queryValues(query.pageSize)),
            ("page_token", InOrbit.Codegen.queryValues(query.pageToken)),
        ]
        return try await client.request(op, as: ListDigestsResponse.self, options: options)
    }

    /// Every item `GET /v1/radar/digests` answers, page after page, following `next_page_token` until the last page; for `for try await`. It throws the first error, and fetches nothing more once the loop stops.
    public func allListDigests(_ query: RadarListDigestsParams = RadarListDigestsParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<Digest, any Error> {
        InOrbit.Codegen.pages { token in
            var page = query
            if let token { page.pageToken = token }
            let value = try await self.listDigests(page, options: options).value
            return (value.digests, value.nextPageToken)
        }
    }
}

extension RadarHandle where P: AllowsGetDigest {
    /// `GET /v1/radar/digests/{id}`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/GetDigest` on the `radar` backend.
    @discardableResult
    public func getDigest(id: String, options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<GetDigestResponse> {
        let op = InOrbit.Codegen.Operation(
            name: "radar.get_digest",
            method: .get,
            path: "/v1/radar/digests/\(InOrbit.Codegen.pathSegment(id))",
            template: "/v1/radar/digests/{id}",
            scopes: ["radar:read"]
        )
        return try await client.request(op, as: GetDigestResponse.self, options: options)
    }
}

extension RadarHandle where P: AllowsListItems {
    /// `GET /v1/radar/items`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/ListItems` on the `radar` backend.
    @discardableResult
    public func listItems(_ query: RadarListItemsParams = RadarListItemsParams(), options: InOrbit.CallOptions = .init()) async throws -> InOrbit.Response<ListItemsResponse> {
        var op = InOrbit.Codegen.Operation(
            name: "radar.list_items",
            method: .get,
            path: "/v1/radar/items",
            template: "/v1/radar/items",
            scopes: ["radar:read"]
        )
        op.query = [
            ("language", InOrbit.Codegen.queryValues(query.language)),
            ("limit", InOrbit.Codegen.queryValues(query.limit)),
            ("page_size", InOrbit.Codegen.queryValues(query.pageSize)),
            ("page_token", InOrbit.Codegen.queryValues(query.pageToken)),
        ]
        return try await client.request(op, as: ListItemsResponse.self, options: options)
    }

    /// Every item `GET /v1/radar/items` answers, page after page, following `next_page_token` until the last page; for `for try await`. It throws the first error, and fetches nothing more once the loop stops.
    public func allListItems(_ query: RadarListItemsParams = RadarListItemsParams(), options: InOrbit.CallOptions = .init()) -> AsyncThrowingStream<Item, any Error> {
        InOrbit.Codegen.pages { token in
            var page = query
            if let token { page.pageToken = token }
            let value = try await self.listItems(page, options: options).value
            return (value.items, value.nextPageToken)
        }
    }
}
