# Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
"""The InOrbit API surface for `hooks` (API 0.1.0).

Generated by `iohr sdk generate`: the models and the operations these profiles may call,
on the `inorbithr` runtime. Regenerate it, never edit it; `iohr sdk check` says when the
API's cut has moved.
"""

from __future__ import annotations

from inorbithr.runtime import codegen

from .models import (
    CreateEndpointRequest,
    CreateEndpointResponse,
    CreateInboxRequest,
    CreateInboxResponse,
    DeleteEndpointResponse,
    DeleteInboxResponse,
    Delivery,
    Endpoint,
    Inbox,
    Problem,
    RetryDeliveryResponse,
    RotateSecretResponse,
    SendTestResponse,
    UpdateEndpointRequest,
)
from .profiles import (
    AsyncHooks,
    Hooks,
)

# A surface generated for another runtime contract refuses to import.
codegen.check(1)

__all__ = [
    "AsyncHooks",
    "CreateEndpointRequest",
    "CreateEndpointResponse",
    "CreateInboxRequest",
    "CreateInboxResponse",
    "DeleteEndpointResponse",
    "DeleteInboxResponse",
    "Delivery",
    "Endpoint",
    "Hooks",
    "Inbox",
    "Problem",
    "RetryDeliveryResponse",
    "RotateSecretResponse",
    "SendTestResponse",
    "UpdateEndpointRequest",
]
