# Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
"""Each operation of this surface as the runtime's `Operation`, built from its arguments."""

from __future__ import annotations

from inorbithr.runtime import (
    Operation,
    codegen,
)

from .models import (
    CreateEndpointRequest,
    CreateInboxRequest,
    UpdateEndpointRequest,
)


def delete_endpoint(endpoint_id: str) -> Operation:
    """`DELETE /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/DeleteEndpoint` on the `events` backend."""
    return Operation(
        name="events.delete_endpoint",
        method="DELETE",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}",
        scopes=("webhooks:write",),
    )


def delete_inbox(inbox_id: str) -> Operation:
    """`DELETE /v1/webhooks/inboxes/{inbox_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/DeleteInbox` on the `events` backend."""
    return Operation(
        name="events.delete_inbox",
        method="DELETE",
        path=f"/v1/webhooks/inboxes/{codegen.path_segment(inbox_id)}",
        scopes=("webhooks:write",),
    )


def update_endpoint(endpoint_id: str, body: UpdateEndpointRequest) -> Operation:
    """`PATCH /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/UpdateEndpoint` on the `events` backend."""
    return Operation(
        name="events.update_endpoint",
        method="PATCH",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}",
        body=body,
        scopes=("webhooks:write",),
    )


def retry_delivery(delivery_id: str) -> Operation:
    """`POST /v1/webhooks/deliveries/{delivery_id}/retry`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RetryDelivery` on the `events` backend."""
    return Operation(
        name="events.retry_delivery",
        method="POST",
        path=f"/v1/webhooks/deliveries/{codegen.path_segment(delivery_id)}/retry",
        scopes=("webhooks:write",),
    )


def create_endpoint(body: CreateEndpointRequest) -> Operation:
    """`POST /v1/webhooks/endpoints`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/CreateEndpoint` on the `events` backend."""
    return Operation(
        name="events.create_endpoint",
        method="POST",
        path="/v1/webhooks/endpoints",
        body=body,
        scopes=("webhooks:write",),
    )


def rotate_secret(endpoint_id: str) -> Operation:
    """`POST /v1/webhooks/endpoints/{endpoint_id}/rotate`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RotateSecret` on the `events` backend."""
    return Operation(
        name="events.rotate_secret",
        method="POST",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}/rotate",
        scopes=("webhooks:write",),
    )


def send_test(endpoint_id: str) -> Operation:
    """`POST /v1/webhooks/endpoints/{endpoint_id}/test`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/SendTest` on the `events` backend."""
    return Operation(
        name="events.send_test",
        method="POST",
        path=f"/v1/webhooks/endpoints/{codegen.path_segment(endpoint_id)}/test",
        scopes=("webhooks:write",),
    )


def create_inbox(body: CreateInboxRequest) -> Operation:
    """`POST /v1/webhooks/inboxes`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/CreateInbox` on the `events` backend."""
    return Operation(
        name="events.create_inbox",
        method="POST",
        path="/v1/webhooks/inboxes",
        body=body,
        scopes=("webhooks:write",),
    )
