// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

/**
 * The query parameters of <code>GET /v1/accounts/orgs/{org_id}/usage</code>.
 *
 * @param from <code>from</code>; <code>null</code> to leave it out
 * @param to <code>to</code>; <code>null</code> to leave it out
 */
public record AccountsGetUsageParams(
        String from,
        String to) {

    /**
     * A builder.
     *
     * @return a builder with every field unset
     */
    public static Builder builder() {
        return new Builder();
    }

    /** Builds a <code>AccountsGetUsageParams</code>. */
    public static final class Builder {
        private String from;
        private String to;

        private Builder() {}

        /**
         * Sets <code>from</code>.
         *
         * @param from the value
         * @return this builder
         */
        public Builder from(String from) {
            this.from = from;
            return this;
        }

        /**
         * Sets <code>to</code>.
         *
         * @param to the value
         * @return this builder
         */
        public Builder to(String to) {
            this.to = to;
            return this;
        }

        /**
         * The value.
         *
         * @return the <code>AccountsGetUsageParams</code>
         */
        public AccountsGetUsageParams build() {
            return new AccountsGetUsageParams(from, to);
        }
    }
}
