// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.EventType</code>
 *
 * @param description the <code>description</code> field
 * @param schema the <code>schema</code> field
 * @param type the <code>type</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record EventType(
        @JsonProperty("description") String description,
        @JsonProperty("schema") String schema,
        @JsonProperty("type") String type) {}
