// Generated by iohr sdk generate for cuts public=sha256:e502c6b35bceaecb889f2f935b273cb83635905cb866029d851731910e3cb948; do not edit.
package iohr;

/**
 * The query parameters of <code>GET /v1/webhooks/inboxes</code>.
 *
 * @param accountId <code>account_id</code>; <code>null</code> to leave it out
 */
public record EventsListInboxesParams(
        String accountId) {

    /**
     * A builder.
     *
     * @return a builder with every field unset
     */
    public static Builder builder() {
        return new Builder();
    }

    /** Builds a <code>EventsListInboxesParams</code>. */
    public static final class Builder {
        private String accountId;

        private Builder() {}

        /**
         * Sets <code>accountId</code>.
         *
         * @param accountId the value
         * @return this builder
         */
        public Builder accountId(String accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * The value.
         *
         * @return the <code>EventsListInboxesParams</code>
         */
        public EventsListInboxesParams build() {
            return new EventsListInboxesParams(accountId);
        }
    }
}
