// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.radar.v1.Example</code>
 *
 * @param source the <code>source</code> field
 * @param stderr the <code>stderr</code> field
 * @param stdout the <code>stdout</code> field
 * @param stub the <code>stub</code> field
 * @param tests the <code>tests</code> field
 * @param toolchain the <code>toolchain</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Example(
        @JsonProperty("source") String source,
        @JsonProperty("stderr") String stderr,
        @JsonProperty("stdout") String stdout,
        @JsonProperty("stub") boolean stub,
        @JsonProperty("tests") String tests,
        @JsonProperty("toolchain") String toolchain) {}
