// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.radar.v1.GetDigestResponse</code>
 *
 * @param digest the <code>digest</code> field; <code>null</code> when unset, and then left out on the wire
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetDigestResponse(
        @JsonProperty("digest") Digest digest) {}
