// Generated by iohr sdk generate for cuts public=sha256:e502c6b35bceaecb889f2f935b273cb83635905cb866029d851731910e3cb948; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.radar.v1.GetDigestResponse</code>
 *
 * @param digest the <code>digest</code> field; <code>null</code> when the answer leaves it out
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetDigestResponse(
        @JsonProperty("digest") Digest digest) {}
