// Generated by iohr sdk generate for cuts public=sha256:e502c6b35bceaecb889f2f935b273cb83635905cb866029d851731910e3cb948; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.accounts.v1.GetUnitsResponse</code>
 *
 * @param accountId the <code>account_id</code> field
 * @param allowance the <code>allowance</code> field
 * @param days the <code>days</code> field
 * @param granted the <code>granted</code> field
 * @param month the <code>month</code> field
 * @param plan the <code>plan</code> field; <code>null</code> when the answer leaves it out
 * @param remaining the <code>remaining</code> field
 * @param resetsAt the <code>resets_at</code> field
 * @param usage the <code>usage</code> field
 * @param used the <code>used</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetUnitsResponse(
        @JsonProperty("account_id") String accountId,
        @JsonProperty("allowance") @JsonFormat(shape = JsonFormat.Shape.STRING) long allowance,
        @JsonProperty("days") List<UnitDay> days,
        @JsonProperty("granted") @JsonFormat(shape = JsonFormat.Shape.STRING) long granted,
        @JsonProperty("month") String month,
        @JsonProperty("plan") Plan plan,
        @JsonProperty("remaining") @JsonFormat(shape = JsonFormat.Shape.STRING) long remaining,
        @JsonProperty("resets_at") String resetsAt,
        @JsonProperty("usage") List<UnitUsage> usage,
        @JsonProperty("used") @JsonFormat(shape = JsonFormat.Shape.STRING) long used) {}
