// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.events.v1.Inbox</code>
 *
 * @param createdAt the <code>created_at</code> field
 * @param expiresAt the <code>expires_at</code> field
 * @param id the <code>id</code> field
 * @param url the <code>url</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Inbox(
        @JsonProperty("created_at") String createdAt,
        @JsonProperty("expires_at") String expiresAt,
        @JsonProperty("id") String id,
        @JsonProperty("url") String url) {}
