// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.events.v1.ListDeliveriesResponse</code>
 *
 * @param deliveries the <code>deliveries</code> field
 * @param nextPageToken the <code>next_page_token</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListDeliveriesResponse(
        @JsonProperty("deliveries") List<Delivery> deliveries,
        @JsonProperty("next_page_token") String nextPageToken) {}
