// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.radar.v1.ListDigestsResponse</code>
 *
 * @param digests the <code>digests</code> field
 * @param nextPageToken the <code>next_page_token</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListDigestsResponse(
        @JsonProperty("digests") List<Digest> digests,
        @JsonProperty("next_page_token") String nextPageToken) {}
