// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>iohr.events.v1.ListInboxRequestsResponse</code>
 *
 * @param inbox the <code>inbox</code> field; <code>null</code> when unset, and then left out on the wire
 * @param nextPageToken the <code>next_page_token</code> field
 * @param requests the <code>requests</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListInboxRequestsResponse(
        @JsonProperty("inbox") Inbox inbox,
        @JsonProperty("next_page_token") String nextPageToken,
        @JsonProperty("requests") List<InboxRequest> requests) {}
