// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * <code>GET /v1/me</code> body.
 *
 * @param clientId The OAuth client the call came through, if any.; <code>null</code> when unset, and then left out on the wire
 * @param email E-mail address, when the token carries one (a person's ID token does).; <code>null</code> when unset, and then left out on the wire
 * @param key the <code>key</code> field; <code>null</code> when unset, and then left out on the wire
 * @param kind <code>person</code>, <code>client</code> or <code>service</code>.
 * @param name Display name, when the token carries one.; <code>null</code> when unset, and then left out on the wire
 * @param org Organisation, when minted.; <code>null</code> when unset, and then left out on the wire
 * @param role Role, when the consent step stamped one.; <code>null</code> when unset, and then left out on the wire
 * @param scopes Granted scopes.
 * @param subject The <code>sub</code> claim.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Me(
        @JsonProperty("client_id") String clientId,
        @JsonProperty("email") String email,
        @JsonProperty("key") Key key,
        @JsonProperty("kind") String kind,
        @JsonProperty("name") String name,
        @JsonProperty("org") String org,
        @JsonProperty("role") String role,
        @JsonProperty("scopes") List<String> scopes,
        @JsonProperty("subject") String subject) {}
