// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
/**
 * The InOrbit API surface for <code>public</code> (API 0.1.0): the models and the operations these profiles may
 * call, on the <code>hr.inorbit.sdk</code> runtime. Generated by <code>iohr sdk generate</code>; regenerate it, never
 * edit it. <code>iohr sdk check</code> says when the API's cut has moved.
 */
package iohr;
