// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import hr.inorbit.sdk.errors.Code;
import hr.inorbit.sdk.errors.Detail;
import java.util.List;

/**
 * <code>{"code","error","details","request_id"}</code>: the REST body and the SSE <code>error</code> payload.
 *
 * @param code The slug.
 * @param details Typed details.
 * @param error The sentence.
 * @param requestId The request's id, the <code>x-request-id</code> the answer carries: name it when asking about a call. Empty on a socket or MQTT frame, whose own id names the call.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Problem(
        @JsonProperty("code") Code code,
        @JsonProperty("details") List<Detail> details,
        @JsonProperty("error") String error,
        @JsonProperty("request_id") String requestId) {}
