// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import hr.inorbit.sdk.Client;
import hr.inorbit.sdk.Pages;
import hr.inorbit.sdk.Response;
import hr.inorbit.sdk.codegen.Codegen;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;

/**
 * The <code>accounts</code> operations profile <code>public</code> may call.
 */
public final class PublicAccounts {

    private final Client client;

    PublicAccounts(Client client) {
        this.client = Objects.requireNonNull(client, "client");
    }

    /**
     * <code>GET /v1/accounts/me</code>; needs scope <code>account:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetMe</code> on the <code>accounts</code> backend.
     *
     * @return the answer, typed, and the raw one
     */
    public Response<GetMeResponse> getMe() {
        return Operations.getMe(client);
    }

    /**
     * <code>GET /v1/accounts/me</code>; needs scope <code>account:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetMe</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<GetMeResponse>> getMeAsync() {
        return Operations.getMeAsync(client);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/units</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUnits</code> on the <code>accounts</code> backend.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<GetUnitsResponse> getUnits(String orgId) {
        return Operations.getUnits(client, orgId);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/units</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUnits</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<GetUnitsResponse>> getUnitsAsync(String orgId) {
        return Operations.getUnitsAsync(client, orgId);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/usage</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUsage</code> on the <code>accounts</code> backend.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @param params the query parameters
     * @return the answer, typed, and the raw one
     */
    public Response<GetUsageResponse> getUsage(String orgId, AccountsGetUsageParams params) {
        return Operations.getUsage(client, orgId, params);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/usage</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUsage</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @param params the query parameters
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<GetUsageResponse>> getUsageAsync(String orgId, AccountsGetUsageParams params) {
        return Operations.getUsageAsync(client, orgId, params);
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/usage</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUsage</code> on the <code>accounts</code> backend.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @return the answer, typed, and the raw one
     */
    public Response<GetUsageResponse> getUsage(String orgId) {
        return Operations.getUsage(client, orgId, AccountsGetUsageParams.builder().build());
    }

    /**
     * <code>GET /v1/accounts/orgs/{org_id}/usage</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/GetUsage</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @param orgId the <code>org_id</code> path parameter
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<GetUsageResponse>> getUsageAsync(String orgId) {
        return Operations.getUsageAsync(client, orgId, AccountsGetUsageParams.builder().build());
    }

    /**
     * <code>GET /v1/accounts/units/categories</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/ListUnitCategories</code> on the <code>accounts</code> backend.
     *
     * @param params the query parameters
     * @return the answer, typed, and the raw one
     */
    public Response<ListUnitCategoriesResponse> listUnitCategories(AccountsListUnitCategoriesParams params) {
        return Operations.listUnitCategories(client, params);
    }

    /**
     * <code>GET /v1/accounts/units/categories</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/ListUnitCategories</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @param params the query parameters
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListUnitCategoriesResponse>> listUnitCategoriesAsync(AccountsListUnitCategoriesParams params) {
        return Operations.listUnitCategoriesAsync(client, params);
    }

    /**
     * <code>GET /v1/accounts/units/categories</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/ListUnitCategories</code> on the <code>accounts</code> backend.
     *
     * @return the answer, typed, and the raw one
     */
    public Response<ListUnitCategoriesResponse> listUnitCategories() {
        return Operations.listUnitCategories(client, AccountsListUnitCategoriesParams.builder().build());
    }

    /**
     * <code>GET /v1/accounts/units/categories</code>; needs scope <code>usage:read</code>. Transcoded from <code>/iohr.accounts.v1.AccountsService/ListUnitCategories</code> on the <code>accounts</code> backend. On the client's executor.
     *
     * @return the answer, when it arrives
     */
    public CompletableFuture<Response<ListUnitCategoriesResponse>> listUnitCategoriesAsync() {
        return Operations.listUnitCategoriesAsync(client, AccountsListUnitCategoriesParams.builder().build());
    }

    /**
     * Every item <code>GET /v1/accounts/units/categories</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @param params the query parameters; the page token is set for each page
     * @return the walk
     */
    public Pages<UnitCategory> allListUnitCategories(AccountsListUnitCategoriesParams params) {
        return Codegen.pages(token -> {
            var page = Operations.listUnitCategories(client, new AccountsListUnitCategoriesParams(params.pageSize(), token != null ? token : params.pageToken())).value();
            return new Pages.Page<>(page.categories(), page.nextPageToken());
        });
    }

    /**
     * Every item <code>GET /v1/accounts/units/categories</code> answers, page after page, following <code>next_page_token</code> until the last page; see {@link Pages}.
     *
     * @return the walk
     */
    public Pages<UnitCategory> allListUnitCategories() {
        return allListUnitCategories(AccountsListUnitCategoriesParams.builder().build());
    }
}
