// Generated by iohr sdk generate for cuts public=sha256:e502c6b35bceaecb889f2f935b273cb83635905cb866029d851731910e3cb948; do not edit.
package iohr;

/**
 * The query parameters of <code>GET /v1/radar/digests</code>.
 *
 * @param language <code>language</code>; <code>null</code> to leave it out
 * @param lang <code>lang</code>; <code>null</code> to leave it out
 * @param limit <code>limit</code>; <code>null</code> to leave it out
 * @param includeDrafts <code>include_drafts</code>; <code>null</code> to leave it out
 * @param beforeWeek <code>before_week</code>; <code>null</code> to leave it out
 */
public record RadarListDigestsParams(
        String language,
        String lang,
        Integer limit,
        Boolean includeDrafts,
        String beforeWeek) {

    /**
     * A builder.
     *
     * @return a builder with every field unset
     */
    public static Builder builder() {
        return new Builder();
    }

    /** Builds a <code>RadarListDigestsParams</code>. */
    public static final class Builder {
        private String language;
        private String lang;
        private Integer limit;
        private Boolean includeDrafts;
        private String beforeWeek;

        private Builder() {}

        /**
         * Sets <code>language</code>.
         *
         * @param language the value
         * @return this builder
         */
        public Builder language(String language) {
            this.language = language;
            return this;
        }

        /**
         * Sets <code>lang</code>.
         *
         * @param lang the value
         * @return this builder
         */
        public Builder lang(String lang) {
            this.lang = lang;
            return this;
        }

        /**
         * Sets <code>limit</code>.
         *
         * @param limit the value
         * @return this builder
         */
        public Builder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Sets <code>includeDrafts</code>.
         *
         * @param includeDrafts the value
         * @return this builder
         */
        public Builder includeDrafts(Boolean includeDrafts) {
            this.includeDrafts = includeDrafts;
            return this;
        }

        /**
         * Sets <code>beforeWeek</code>.
         *
         * @param beforeWeek the value
         * @return this builder
         */
        public Builder beforeWeek(String beforeWeek) {
            this.beforeWeek = beforeWeek;
            return this;
        }

        /**
         * The value.
         *
         * @return the <code>RadarListDigestsParams</code>
         */
        public RadarListDigestsParams build() {
            return new RadarListDigestsParams(language, lang, limit, includeDrafts, beforeWeek);
        }
    }
}
