// Generated by iohr sdk generate for cuts public=sha256:e502c6b35bceaecb889f2f935b273cb83635905cb866029d851731910e3cb948; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.accounts.v1.UnitCategory</code>
 *
 * @param description the <code>description</code> field
 * @param name the <code>name</code> field
 * @param unitsPer1kTokens the <code>units_per_1k_tokens</code> field
 * @param unitsPerCall the <code>units_per_call</code> field
 * @param updatedAt the <code>updated_at</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record UnitCategory(
        @JsonProperty("description") String description,
        @JsonProperty("name") String name,
        @JsonProperty("units_per_1k_tokens") @JsonFormat(shape = JsonFormat.Shape.STRING) long unitsPer1kTokens,
        @JsonProperty("units_per_call") @JsonFormat(shape = JsonFormat.Shape.STRING) long unitsPerCall,
        @JsonProperty("updated_at") String updatedAt) {}
