// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
package iohr;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * <code>iohr.accounts.v1.UnitDay</code>
 *
 * @param day the <code>day</code> field
 * @param units the <code>units</code> field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record UnitDay(
        @JsonProperty("day") String day,
        @JsonProperty("units") @JsonFormat(shape = JsonFormat.Shape.STRING) long units) {}
