[package]
name = "iohr-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
iohr = { path = "../crates/iohr" }
iohr-auth = { path = "../crates/iohr-auth" }
libfuzzer-sys = "0.4"
time = "0.3"

[[bin]]
name = "config"
path = "fuzz_targets/config.rs"
test = false
doc = false
bench = false

[[bin]]
name = "problem"
path = "fuzz_targets/problem.rs"
test = false
doc = false
bench = false

[[bin]]
name = "claims"
path = "fuzz_targets/claims.rs"
test = false
doc = false
bench = false
