// Generated by iohr sdk generate for cuts public=sha256:508bfc8766999d3d343f8489611d00e92a102e43994a2961c77e65d2f5473c91; do not edit.
import { type CallOptions, Client, codegen, type LoadClientOptions, type Response } from "@inorbithr/sdk";
import { type CreateEndpointRequest, type CreateEndpointResponse, type CreateInboxRequest, type CreateInboxResponse, type DeleteEndpointResponse, type DeleteInboxResponse, type Delivery, type Digest, type Endpoint, type EventType, type GetDigestResponse, type GetMeResponse, type GetUnitsResponse, type GetUsageResponse, type Inbox, type InboxRequest, type Item, type ListDeliveriesResponse, type ListDigestsResponse, type ListEndpointsResponse, type ListEventTypesResponse, type ListInboxRequestsResponse, type ListInboxesResponse, type ListItemsResponse, type ListUnitCategoriesResponse, type Me, type RetryDeliveryResponse, type RotateSecretResponse, type SendTestResponse, type StreamEventsResponse, type UnitCategory, type UpdateEndpointRequest } from "./models.js";
import * as ops from "./operations.js";
import { type AccountsGetUsageParams, type AccountsListUnitCategoriesParams, type EventsListDeliveriesParams, type EventsListEndpointsParams, type EventsListEventTypesParams, type EventsListInboxRequestsParams, type EventsListInboxesParams, type EventsStreamEventsParams, type RadarListDigestsParams, type RadarListItemsParams } from "./operations.js";

/**
 * Profile `public`: the operations its cut holds. `fromEnv()` reads `INORBIT_TOKEN`, or `INORBIT_KEY_ID`, `INORBIT_KEY_SECRET` and `INORBIT_SCOPES`.
 */
export class Public {
  /** The profile's name. */
  static readonly profile = "public";
  /** The `accounts` operations. */
  readonly accounts: PublicAccounts;
  /** The `events` operations. */
  readonly events: PublicEvents;
  /** The `radar` operations. */
  readonly radar: PublicRadar;

  /** A profile on a client built for its credential. */
  constructor(readonly client: Client) {
    this.accounts = new PublicAccounts(client);
    this.events = new PublicEvents(client);
    this.radar = new PublicRadar(client);
  }

  /** The profile with its credential from the environment. */
  static fromEnv(): Public {
    return new Public(Client.fromEnv());
  }

  /** The profile configured from code, the environment, the config file and the `iohr` login (`Client.load`). */
  static load(options: LoadClientOptions = {}): Public {
    return new Public(Client.load(options));
  }

  /** `GET /v1/me`; needs scope `identity:read`. A key needs scope `identity:read`. */
  me(options?: CallOptions): Promise<Response<Me>> {
    return ops.me(this.client, options);
  }
}

/** The `accounts` operations profile `public` may call. */
export class PublicAccounts {
  /** The handle on a profile's client. */
  constructor(private readonly client: Client) {}

  /** `GET /v1/accounts/me`; needs scope `account:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetMe` on the `accounts` backend. */
  getMe(options?: CallOptions): Promise<Response<GetMeResponse>> {
    return ops.getMe(this.client, options);
  }

  /** `GET /v1/accounts/orgs/{org_id}/units`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetUnits` on the `accounts` backend. */
  getUnits(orgId: string, options?: CallOptions): Promise<Response<GetUnitsResponse>> {
    return ops.getUnits(this.client, orgId, options);
  }

  /** `GET /v1/accounts/orgs/{org_id}/usage`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/GetUsage` on the `accounts` backend. */
  getUsage(orgId: string, params: AccountsGetUsageParams = {}, options?: CallOptions): Promise<Response<GetUsageResponse>> {
    return ops.getUsage(this.client, orgId, params, options);
  }

  /** `GET /v1/accounts/units/categories`; needs scope `usage:read`. Transcoded from `/iohr.accounts.v1.AccountsService/ListUnitCategories` on the `accounts` backend. */
  listUnitCategories(params: AccountsListUnitCategoriesParams = {}, options?: CallOptions): Promise<Response<ListUnitCategoriesResponse>> {
    return ops.listUnitCategories(this.client, params, options);
  }

  /**
   * Every item `GET /v1/accounts/units/categories` answers, page after page, following `next_page_token` until the last page.
   * Throws the first error; stops when the loop breaks or `options.signal` aborts.
   */
  async *allListUnitCategories(params: AccountsListUnitCategoriesParams = {}, options?: CallOptions): AsyncGenerator<UnitCategory, void, undefined> {
    yield* codegen.pages(async (token) => {
      const { value } = await ops.listUnitCategories(this.client, token === undefined ? params : { ...params, page_token: token }, options);
      return [value.categories ?? [], value.next_page_token ?? ""] as const;
    }, options?.signal);
  }
}

/** The `events` operations profile `public` may call. */
export class PublicEvents {
  /** The handle on a profile's client. */
  constructor(private readonly client: Client) {}

  /** `DELETE /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/DeleteEndpoint` on the `events` backend. */
  deleteEndpoint(endpointId: string, options?: CallOptions): Promise<Response<DeleteEndpointResponse>> {
    return ops.deleteEndpoint(this.client, endpointId, options);
  }

  /** `DELETE /v1/webhooks/inboxes/{inbox_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/DeleteInbox` on the `events` backend. */
  deleteInbox(inboxId: string, options?: CallOptions): Promise<Response<DeleteInboxResponse>> {
    return ops.deleteInbox(this.client, inboxId, options);
  }

  /** `GET /v1/events/events`; needs scope `events:read`. Transcoded from `/iohr.events.v1.EventsService/StreamEvents` on the `events` backend. */
  streamEvents(params: EventsStreamEventsParams = {}, options?: CallOptions): AsyncGenerator<StreamEventsResponse, void, undefined> {
    return ops.streamEvents(this.client, params, options);
  }

  /** `GET /v1/events/types`; needs scope `events:read`. Transcoded from `/iohr.events.v1.EventsService/ListEventTypes` on the `events` backend. */
  listEventTypes(params: EventsListEventTypesParams = {}, options?: CallOptions): Promise<Response<ListEventTypesResponse>> {
    return ops.listEventTypes(this.client, params, options);
  }

  /**
   * Every item `GET /v1/events/types` answers, page after page, following `next_page_token` until the last page.
   * Throws the first error; stops when the loop breaks or `options.signal` aborts.
   */
  async *allListEventTypes(params: EventsListEventTypesParams = {}, options?: CallOptions): AsyncGenerator<EventType, void, undefined> {
    yield* codegen.pages(async (token) => {
      const { value } = await ops.listEventTypes(this.client, token === undefined ? params : { ...params, page_token: token }, options);
      return [value.types ?? [], value.next_page_token ?? ""] as const;
    }, options?.signal);
  }

  /** `GET /v1/webhooks/endpoints`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListEndpoints` on the `events` backend. */
  listEndpoints(params: EventsListEndpointsParams = {}, options?: CallOptions): Promise<Response<ListEndpointsResponse>> {
    return ops.listEndpoints(this.client, params, options);
  }

  /**
   * Every item `GET /v1/webhooks/endpoints` answers, page after page, following `next_page_token` until the last page.
   * Throws the first error; stops when the loop breaks or `options.signal` aborts.
   */
  async *allListEndpoints(params: EventsListEndpointsParams = {}, options?: CallOptions): AsyncGenerator<Endpoint, void, undefined> {
    yield* codegen.pages(async (token) => {
      const { value } = await ops.listEndpoints(this.client, token === undefined ? params : { ...params, page_token: token }, options);
      return [value.endpoints ?? [], value.next_page_token ?? ""] as const;
    }, options?.signal);
  }

  /** `GET /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/GetEndpoint` on the `events` backend. */
  getEndpoint(endpointId: string, options?: CallOptions): Promise<Response<Endpoint>> {
    return ops.getEndpoint(this.client, endpointId, options);
  }

  /** `GET /v1/webhooks/endpoints/{endpoint_id}/deliveries`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListDeliveries` on the `events` backend. */
  listDeliveries(endpointId: string, params: EventsListDeliveriesParams = {}, options?: CallOptions): Promise<Response<ListDeliveriesResponse>> {
    return ops.listDeliveries(this.client, endpointId, params, options);
  }

  /**
   * Every item `GET /v1/webhooks/endpoints/{endpoint_id}/deliveries` answers, page after page, following `next_page_token` until the last page.
   * Throws the first error; stops when the loop breaks or `options.signal` aborts.
   */
  async *allListDeliveries(endpointId: string, params: EventsListDeliveriesParams = {}, options?: CallOptions): AsyncGenerator<Delivery, void, undefined> {
    yield* codegen.pages(async (token) => {
      const { value } = await ops.listDeliveries(this.client, endpointId, token === undefined ? params : { ...params, page_token: token }, options);
      return [value.deliveries ?? [], value.next_page_token ?? ""] as const;
    }, options?.signal);
  }

  /** `GET /v1/webhooks/inboxes`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListInboxes` on the `events` backend. */
  listInboxes(params: EventsListInboxesParams = {}, options?: CallOptions): Promise<Response<ListInboxesResponse>> {
    return ops.listInboxes(this.client, params, options);
  }

  /**
   * Every item `GET /v1/webhooks/inboxes` answers, page after page, following `next_page_token` until the last page.
   * Throws the first error; stops when the loop breaks or `options.signal` aborts.
   */
  async *allListInboxes(params: EventsListInboxesParams = {}, options?: CallOptions): AsyncGenerator<Inbox, void, undefined> {
    yield* codegen.pages(async (token) => {
      const { value } = await ops.listInboxes(this.client, token === undefined ? params : { ...params, page_token: token }, options);
      return [value.inboxes ?? [], value.next_page_token ?? ""] as const;
    }, options?.signal);
  }

  /** `GET /v1/webhooks/inboxes/{inbox_id}/requests`; needs scope `webhooks:read`. Transcoded from `/iohr.events.v1.EventsService/ListInboxRequests` on the `events` backend. */
  listInboxRequests(inboxId: string, params: EventsListInboxRequestsParams = {}, options?: CallOptions): Promise<Response<ListInboxRequestsResponse>> {
    return ops.listInboxRequests(this.client, inboxId, params, options);
  }

  /**
   * Every item `GET /v1/webhooks/inboxes/{inbox_id}/requests` answers, page after page, following `next_page_token` until the last page.
   * Throws the first error; stops when the loop breaks or `options.signal` aborts.
   */
  async *allListInboxRequests(inboxId: string, params: EventsListInboxRequestsParams = {}, options?: CallOptions): AsyncGenerator<InboxRequest, void, undefined> {
    yield* codegen.pages(async (token) => {
      const { value } = await ops.listInboxRequests(this.client, inboxId, token === undefined ? params : { ...params, page_token: token }, options);
      return [value.requests ?? [], value.next_page_token ?? ""] as const;
    }, options?.signal);
  }

  /** `PATCH /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/UpdateEndpoint` on the `events` backend. */
  updateEndpoint(endpointId: string, body: UpdateEndpointRequest, options?: CallOptions): Promise<Response<Endpoint>> {
    return ops.updateEndpoint(this.client, endpointId, body, options);
  }

  /** `POST /v1/webhooks/deliveries/{delivery_id}/retry`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RetryDelivery` on the `events` backend. */
  retryDelivery(deliveryId: string, options?: CallOptions): Promise<Response<RetryDeliveryResponse>> {
    return ops.retryDelivery(this.client, deliveryId, options);
  }

  /** `POST /v1/webhooks/endpoints`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/CreateEndpoint` on the `events` backend. */
  createEndpoint(body: CreateEndpointRequest, options?: CallOptions): Promise<Response<CreateEndpointResponse>> {
    return ops.createEndpoint(this.client, body, options);
  }

  /** `POST /v1/webhooks/endpoints/{endpoint_id}/rotate`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/RotateSecret` on the `events` backend. */
  rotateSecret(endpointId: string, options?: CallOptions): Promise<Response<RotateSecretResponse>> {
    return ops.rotateSecret(this.client, endpointId, options);
  }

  /** `POST /v1/webhooks/endpoints/{endpoint_id}/test`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/SendTest` on the `events` backend. */
  sendTest(endpointId: string, options?: CallOptions): Promise<Response<SendTestResponse>> {
    return ops.sendTest(this.client, endpointId, options);
  }

  /** `POST /v1/webhooks/inboxes`; needs scope `webhooks:write`. Transcoded from `/iohr.events.v1.EventsService/CreateInbox` on the `events` backend. */
  createInbox(body: CreateInboxRequest, options?: CallOptions): Promise<Response<CreateInboxResponse>> {
    return ops.createInbox(this.client, body, options);
  }
}

/** The `radar` operations profile `public` may call. */
export class PublicRadar {
  /** The handle on a profile's client. */
  constructor(private readonly client: Client) {}

  /** `GET /v1/radar/digests`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/ListDigests` on the `radar` backend. */
  listDigests(params: RadarListDigestsParams = {}, options?: CallOptions): Promise<Response<ListDigestsResponse>> {
    return ops.listDigests(this.client, params, options);
  }

  /**
   * Every item `GET /v1/radar/digests` answers, page after page, following `next_page_token` until the last page.
   * Throws the first error; stops when the loop breaks or `options.signal` aborts.
   */
  async *allListDigests(params: RadarListDigestsParams = {}, options?: CallOptions): AsyncGenerator<Digest, void, undefined> {
    yield* codegen.pages(async (token) => {
      const { value } = await ops.listDigests(this.client, token === undefined ? params : { ...params, page_token: token }, options);
      return [value.digests ?? [], value.next_page_token ?? ""] as const;
    }, options?.signal);
  }

  /** `GET /v1/radar/digests/{id}`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/GetDigest` on the `radar` backend. */
  getDigest(id: string, options?: CallOptions): Promise<Response<GetDigestResponse>> {
    return ops.getDigest(this.client, id, options);
  }

  /** `GET /v1/radar/items`; needs scope `radar:read`. Transcoded from `/iohr.radar.v1.RadarService/ListItems` on the `radar` backend. */
  listItems(params: RadarListItemsParams = {}, options?: CallOptions): Promise<Response<ListItemsResponse>> {
    return ops.listItems(this.client, params, options);
  }

  /**
   * Every item `GET /v1/radar/items` answers, page after page, following `next_page_token` until the last page.
   * Throws the first error; stops when the loop breaks or `options.signal` aborts.
   */
  async *allListItems(params: RadarListItemsParams = {}, options?: CallOptions): AsyncGenerator<Item, void, undefined> {
    yield* codegen.pages(async (token) => {
      const { value } = await ops.listItems(this.client, token === undefined ? params : { ...params, page_token: token }, options);
      return [value.items ?? [], value.next_page_token ?? ""] as const;
    }, options?.signal);
  }
}
