// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
//! The InOrbit API surface for `hooks` (API 0.1.0).
//!
//! Generated by `iohr sdk generate`: the models and the operations these profiles
//! may call, on the `inorbithr` runtime. Regenerate it, never edit it; `iohr sdk check`
//! says when the API's cut has moved.
#![allow(
    clippy::all,
    clippy::pedantic,
    dead_code,
    unused_imports,
    unreachable_pub,
    missing_docs,
    missing_debug_implementations
)]

#[rustfmt::skip]
pub mod models;
#[rustfmt::skip]
pub mod ops;
#[rustfmt::skip]
pub mod profiles;
#[rustfmt::skip]
pub mod surface;

pub use models::*;
pub use profiles::*;
pub use surface::*;

/// What a program using this surface imports.
pub mod prelude {
    pub use super::profiles::*;
    pub use super::surface::Surface;
    pub use inorbithr::prelude::*;
}

const _: () = assert!(
    inorbithr::__codegen::VERSION == 1,
    "this surface was generated for another inorbithr runtime; run `iohr sdk generate` again",
);
