// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.

///`iohr.events.v1.CreateEndpointRequest`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, PartialEq)]
pub struct CreateEndpointRequest {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub account_id: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub description: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub event_types: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub url: ::std::option::Option<::std::string::String>,
}
///`iohr.events.v1.CreateEndpointResponse`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct CreateEndpointResponse {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub endpoint: ::std::option::Option<Endpoint>,
    pub secret: ::std::string::String,
}
///`iohr.events.v1.CreateInboxRequest`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, PartialEq)]
pub struct CreateInboxRequest {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub account_id: ::std::option::Option<::std::string::String>,
}
///`iohr.events.v1.CreateInboxResponse`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, PartialEq)]
pub struct CreateInboxResponse {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub inbox: ::std::option::Option<Inbox>,
}
///`iohr.events.v1.DeleteEndpointResponse`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(transparent)]
pub struct DeleteEndpointResponse(
    pub ::serde_json::Map<::std::string::String, ::serde_json::Value>,
);
impl ::std::ops::Deref for DeleteEndpointResponse {
    type Target = ::serde_json::Map<::std::string::String, ::serde_json::Value>;
    fn deref(&self) -> &::serde_json::Map<::std::string::String, ::serde_json::Value> {
        &self.0
    }
}
impl ::std::convert::From<DeleteEndpointResponse>
for ::serde_json::Map<::std::string::String, ::serde_json::Value> {
    fn from(value: DeleteEndpointResponse) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Map<::std::string::String, ::serde_json::Value>>
for DeleteEndpointResponse {
    fn from(
        value: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    ) -> Self {
        Self(value)
    }
}
///`iohr.events.v1.DeleteInboxResponse`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
#[serde(transparent)]
pub struct DeleteInboxResponse(
    pub ::serde_json::Map<::std::string::String, ::serde_json::Value>,
);
impl ::std::ops::Deref for DeleteInboxResponse {
    type Target = ::serde_json::Map<::std::string::String, ::serde_json::Value>;
    fn deref(&self) -> &::serde_json::Map<::std::string::String, ::serde_json::Value> {
        &self.0
    }
}
impl ::std::convert::From<DeleteInboxResponse>
for ::serde_json::Map<::std::string::String, ::serde_json::Value> {
    fn from(value: DeleteInboxResponse) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Map<::std::string::String, ::serde_json::Value>>
for DeleteInboxResponse {
    fn from(
        value: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    ) -> Self {
        Self(value)
    }
}
///`iohr.events.v1.Delivery`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct Delivery {
    pub attempts: i32,
    pub created_at: ::std::string::String,
    pub endpoint_id: ::std::string::String,
    pub event_id: ::std::string::String,
    pub event_type: ::std::string::String,
    pub id: ::std::string::String,
    pub last_error: ::std::string::String,
    pub last_latency_ms: i32,
    pub last_status_code: i32,
    pub next_attempt_at: ::std::string::String,
    pub status: ::std::string::String,
    pub updated_at: ::std::string::String,
}
///`iohr.events.v1.Endpoint`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct Endpoint {
    pub created_at: ::std::string::String,
    pub description: ::std::string::String,
    pub disabled_reason: ::std::string::String,
    pub enabled: bool,
    pub event_types: ::std::vec::Vec<::std::string::String>,
    pub failed_24h: i32,
    pub id: ::std::string::String,
    pub last_delivery_at: ::std::string::String,
    pub last_delivery_status: ::std::string::String,
    pub secret_rotated_at: ::std::string::String,
    pub succeeded_24h: i32,
    pub url: ::std::string::String,
}
///`iohr.events.v1.Inbox`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct Inbox {
    pub created_at: ::std::string::String,
    pub expires_at: ::std::string::String,
    pub id: ::std::string::String,
    pub url: ::std::string::String,
}
///`{"code","error","details","request_id"}`: the REST body and the SSE `error` payload.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct Problem {
    ///The slug.
    pub code: inorbithr::Code,
    ///Typed details.
    pub details: ::std::vec::Vec<inorbithr::Detail>,
    ///The sentence.
    pub error: ::std::string::String,
    /**The request's id, the `x-request-id` the answer carries: name it when
asking about a call. Empty on a socket or MQTT frame, whose own id
names the call.*/
    pub request_id: ::std::string::String,
}
///`iohr.events.v1.RetryDeliveryResponse`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, PartialEq)]
pub struct RetryDeliveryResponse {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub delivery: ::std::option::Option<Delivery>,
}
///`iohr.events.v1.RotateSecretResponse`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
pub struct RotateSecretResponse {
    pub previous_expires_at: ::std::string::String,
    pub secret: ::std::string::String,
}
///`iohr.events.v1.SendTestResponse`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, PartialEq)]
pub struct SendTestResponse {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub delivery: ::std::option::Option<Delivery>,
}
///`iohr.events.v1.UpdateEndpointRequest`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default, PartialEq)]
pub struct UpdateEndpointRequest {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub description: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub enabled: ::std::option::Option<bool>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub endpoint_id: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub event_types: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub url: ::std::option::Option<::std::string::String>,
}
/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
