// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
//! One marker trait per operation, implemented for the profiles whose cut holds it.
//! An operation's method is bounded by its marker, so calling it on a profile that
//! may not is a compile error, not a 403.
/// `DELETE /v1/webhooks/endpoints/{endpoint_id}`
pub trait DeleteEndpoint: inorbithr::Profile {}
impl DeleteEndpoint for super::profiles::Hooks {}
/// `DELETE /v1/webhooks/inboxes/{inbox_id}`
pub trait DeleteInbox: inorbithr::Profile {}
impl DeleteInbox for super::profiles::Hooks {}
/// `PATCH /v1/webhooks/endpoints/{endpoint_id}`
pub trait UpdateEndpoint: inorbithr::Profile {}
impl UpdateEndpoint for super::profiles::Hooks {}
/// `POST /v1/webhooks/deliveries/{delivery_id}/retry`
pub trait RetryDelivery: inorbithr::Profile {}
impl RetryDelivery for super::profiles::Hooks {}
/// `POST /v1/webhooks/endpoints`
pub trait CreateEndpoint: inorbithr::Profile {}
impl CreateEndpoint for super::profiles::Hooks {}
/// `POST /v1/webhooks/endpoints/{endpoint_id}/rotate`
pub trait RotateSecret: inorbithr::Profile {}
impl RotateSecret for super::profiles::Hooks {}
/// `POST /v1/webhooks/endpoints/{endpoint_id}/test`
pub trait SendTest: inorbithr::Profile {}
impl SendTest for super::profiles::Hooks {}
/// `POST /v1/webhooks/inboxes`
pub trait CreateInbox: inorbithr::Profile {}
impl CreateInbox for super::profiles::Hooks {}
