// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
//! The profiles this surface was generated for: one zero-sized type each, the type
//! parameter of `Client`. A profile's client reads `INORBIT_<NAME>_*` and calls only
//! the operations its cut holds.
/// Profile `hooks`: `Client::<Hooks>::from_env()` reads `INORBIT_HOOKS_TOKEN`, or
/// `INORBIT_HOOKS_KEY_ID`, `INORBIT_HOOKS_KEY_SECRET` and `INORBIT_HOOKS_SCOPES`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Hooks;
impl inorbithr::Profile for Hooks {
    const NAME: &'static str = "hooks";
}
