// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
//! The profiles this surface was generated for: one zero-sized type each, the type
//! parameter of `Client`. A profile's client reads `INORBIT_<NAME>_*` and calls only
//! the operations its cut holds.
/// Profile `hooks`: `Client::<Hooks>::from_env()` reads `INORBIT_HOOKS_TOKEN`, or
/// `INORBIT_HOOKS_KEY_ID`, `INORBIT_HOOKS_KEY_SECRET` and `INORBIT_HOOKS_SCOPES`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Hooks;
impl inorbithr::Profile for Hooks {
    const NAME: &'static str = "hooks";
}
