// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
//! The operations, grouped by area. [`Surface`] is implemented for `Client<P>` for the
//! profiles of this surface; each operation is callable only where its marker in
//! [`ops`](super::ops) is implemented.
use std::future::Future;
use inorbithr::__codegen::path_segment;
use inorbithr::{Client, Error, Method, Operation, Profile, Response};
use super::models::*;
use super::ops;
/// The operations, as methods on [`Client`].
pub trait Surface<P: Profile> {
    /// The `events` operations.
    fn events(&self) -> Events<'_, P>;
}
impl<P: Profile> Surface<P> for Client<P> {
    fn events(&self) -> Events<'_, P> {
        Events(self)
    }
}
/// The `events` operations of a client.
#[derive(Debug, Clone, Copy)]
pub struct Events<'a, P: Profile>(&'a Client<P>);
impl<P: ops::DeleteEndpoint> Events<'_, P> {
    /// `DELETE /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`.
    pub async fn delete_endpoint(
        &self,
        endpoint_id: &str,
    ) -> Result<Response<DeleteEndpointResponse>, Error> {
        let op = Operation::new(
                Method::Delete,
                format!("/v1/webhooks/endpoints/{}", path_segment(endpoint_id)),
            )
            .named("events.delete_endpoint")
            .scopes(&["webhooks:write"]);
        self.0.request(op).await
    }
}
impl<P: ops::DeleteInbox> Events<'_, P> {
    /// `DELETE /v1/webhooks/inboxes/{inbox_id}`; needs scope `webhooks:write`.
    pub async fn delete_inbox(
        &self,
        inbox_id: &str,
    ) -> Result<Response<DeleteInboxResponse>, Error> {
        let op = Operation::new(
                Method::Delete,
                format!("/v1/webhooks/inboxes/{}", path_segment(inbox_id)),
            )
            .named("events.delete_inbox")
            .scopes(&["webhooks:write"]);
        self.0.request(op).await
    }
}
impl<P: ops::UpdateEndpoint> Events<'_, P> {
    /// `PATCH /v1/webhooks/endpoints/{endpoint_id}`; needs scope `webhooks:write`.
    pub async fn update_endpoint(
        &self,
        endpoint_id: &str,
        body: &UpdateEndpointRequest,
    ) -> Result<Response<Endpoint>, Error> {
        let op = Operation::new(
                Method::Patch,
                format!("/v1/webhooks/endpoints/{}", path_segment(endpoint_id)),
            )
            .named("events.update_endpoint")
            .scopes(&["webhooks:write"])
            .json(body)?;
        self.0.request(op).await
    }
}
impl<P: ops::RetryDelivery> Events<'_, P> {
    /// `POST /v1/webhooks/deliveries/{delivery_id}/retry`; needs scope `webhooks:write`.
    pub async fn retry_delivery(
        &self,
        delivery_id: &str,
    ) -> Result<Response<RetryDeliveryResponse>, Error> {
        let op = Operation::new(
                Method::Post,
                format!("/v1/webhooks/deliveries/{}/retry", path_segment(delivery_id)),
            )
            .named("events.retry_delivery")
            .scopes(&["webhooks:write"]);
        self.0.request(op).await
    }
}
impl<P: ops::CreateEndpoint> Events<'_, P> {
    /// `POST /v1/webhooks/endpoints`; needs scope `webhooks:write`.
    pub async fn create_endpoint(
        &self,
        body: &CreateEndpointRequest,
    ) -> Result<Response<CreateEndpointResponse>, Error> {
        let op = Operation::new(Method::Post, "/v1/webhooks/endpoints")
            .named("events.create_endpoint")
            .scopes(&["webhooks:write"])
            .json(body)?;
        self.0.request(op).await
    }
}
impl<P: ops::RotateSecret> Events<'_, P> {
    /// `POST /v1/webhooks/endpoints/{endpoint_id}/rotate`; needs scope `webhooks:write`.
    pub async fn rotate_secret(
        &self,
        endpoint_id: &str,
    ) -> Result<Response<RotateSecretResponse>, Error> {
        let op = Operation::new(
                Method::Post,
                format!("/v1/webhooks/endpoints/{}/rotate", path_segment(endpoint_id)),
            )
            .named("events.rotate_secret")
            .scopes(&["webhooks:write"]);
        self.0.request(op).await
    }
}
impl<P: ops::SendTest> Events<'_, P> {
    /// `POST /v1/webhooks/endpoints/{endpoint_id}/test`; needs scope `webhooks:write`.
    pub async fn send_test(
        &self,
        endpoint_id: &str,
    ) -> Result<Response<SendTestResponse>, Error> {
        let op = Operation::new(
                Method::Post,
                format!("/v1/webhooks/endpoints/{}/test", path_segment(endpoint_id)),
            )
            .named("events.send_test")
            .scopes(&["webhooks:write"]);
        self.0.request(op).await
    }
}
impl<P: ops::CreateInbox> Events<'_, P> {
    /// `POST /v1/webhooks/inboxes`; needs scope `webhooks:write`.
    pub async fn create_inbox(
        &self,
        body: &CreateInboxRequest,
    ) -> Result<Response<CreateInboxResponse>, Error> {
        let op = Operation::new(Method::Post, "/v1/webhooks/inboxes")
            .named("events.create_inbox")
            .scopes(&["webhooks:write"])
            .json(body)?;
        self.0.request(op).await
    }
}
