// <auto-generated>
// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
// </auto-generated>

#nullable enable

namespace InOrbit.Generated
{
    /// <summary>A profile whose cut holds <c>DELETE /v1/webhooks/endpoints/{endpoint_id}</c>.</summary>
    public interface IDeleteEndpoint : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>DELETE /v1/webhooks/inboxes/{inbox_id}</c>.</summary>
    public interface IDeleteInbox : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/accounts/me</c>.</summary>
    public interface IGetMe : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/accounts/orgs/{org_id}/units</c>.</summary>
    public interface IGetUnits : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/accounts/orgs/{org_id}/usage</c>.</summary>
    public interface IGetUsage : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/accounts/units/categories</c>.</summary>
    public interface IListUnitCategories : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/events/types</c>.</summary>
    public interface IListEventTypes : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/me</c>.</summary>
    public interface IMe : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/radar/digests</c>.</summary>
    public interface IListDigests : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/radar/digests/{id}</c>.</summary>
    public interface IGetDigest : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/radar/items</c>.</summary>
    public interface IListItems : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/webhooks/endpoints</c>.</summary>
    public interface IListEndpoints : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/webhooks/endpoints/{endpoint_id}</c>.</summary>
    public interface IGetEndpoint : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/webhooks/endpoints/{endpoint_id}/deliveries</c>.</summary>
    public interface IListDeliveries : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/webhooks/inboxes</c>.</summary>
    public interface IListInboxes : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>GET /v1/webhooks/inboxes/{inbox_id}/requests</c>.</summary>
    public interface IListInboxRequests : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>PATCH /v1/webhooks/endpoints/{endpoint_id}</c>.</summary>
    public interface IUpdateEndpoint : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>POST /v1/webhooks/deliveries/{delivery_id}/retry</c>.</summary>
    public interface IRetryDelivery : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>POST /v1/webhooks/endpoints</c>.</summary>
    public interface ICreateEndpoint : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>POST /v1/webhooks/endpoints/{endpoint_id}/rotate</c>.</summary>
    public interface IRotateSecret : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>POST /v1/webhooks/endpoints/{endpoint_id}/test</c>.</summary>
    public interface ISendTest : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds <c>POST /v1/webhooks/inboxes</c>.</summary>
    public interface ICreateInbox : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds an operation of <c>accounts</c>.</summary>
    public interface IAccountsArea : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds an operation of <c>events</c>.</summary>
    public interface IEventsArea : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>A profile whose cut holds an operation of <c>radar</c>.</summary>
    public interface IRadarArea : global::InOrbit.Sdk.IProfile
    {
    }

    /// <summary>Profile <c>acme-ci</c>: the operations its cut holds. <c>Client.FromEnv</c> reads <c>INORBIT_ACME_CI_TOKEN</c>, or <c>INORBIT_ACME_CI_KEY_ID</c>, <c>INORBIT_ACME_CI_KEY_SECRET</c> and <c>INORBIT_ACME_CI_SCOPES</c>, and nothing else.</summary>
    public sealed class AcmeCi
        : global::InOrbit.Sdk.IProfile,
          IDeleteEndpoint,
          IDeleteInbox,
          IGetMe,
          IGetUnits,
          IGetUsage,
          IListUnitCategories,
          IListEventTypes,
          IMe,
          IListDigests,
          IGetDigest,
          IListItems,
          IListEndpoints,
          IGetEndpoint,
          IListDeliveries,
          IListInboxes,
          IListInboxRequests,
          IUpdateEndpoint,
          IRetryDelivery,
          ICreateEndpoint,
          IRotateSecret,
          ISendTest,
          ICreateInbox,
          IAccountsArea,
          IEventsArea,
          IRadarArea
    {
        private AcmeCi()
        {
        }

        /// <inheritdoc/>
        public static string Name => "acme-ci";

        /// <inheritdoc/>
        public static string Env => "ACME_CI";
    }

    /// <summary>Profile <c>personal</c>: the operations its cut holds. <c>Client.FromEnv</c> reads <c>INORBIT_PERSONAL_TOKEN</c>, or <c>INORBIT_PERSONAL_KEY_ID</c>, <c>INORBIT_PERSONAL_KEY_SECRET</c> and <c>INORBIT_PERSONAL_SCOPES</c>, and nothing else.</summary>
    public sealed class Personal
        : global::InOrbit.Sdk.IProfile,
          IMe,
          IListDigests,
          IGetDigest,
          IListItems,
          IRadarArea
    {
        private Personal()
        {
        }

        /// <inheritdoc/>
        public static string Name => "personal";

        /// <inheritdoc/>
        public static string Env => "PERSONAL";
    }
}
