// <auto-generated>
// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
// </auto-generated>

#nullable enable

namespace InOrbit.Generated
{
    /// <summary><c>iohr.events.v1.CreateEndpointRequest</c></summary>
    public sealed record CreateEndpointRequest
    {
        /// <summary>The <c>account_id</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("account_id")]
        public string AccountId { get; init; } = "";

        /// <summary>The <c>description</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; init; } = "";

        /// <summary>The <c>event_types</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("event_types")]
        public global::System.Collections.Generic.IReadOnlyList<string> EventTypes { get; init; } = [];

        /// <summary>The <c>url</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; init; } = "";
    }

    /// <summary><c>iohr.events.v1.CreateEndpointResponse</c></summary>
    public sealed record CreateEndpointResponse
    {
        /// <summary>The <c>endpoint</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("endpoint")]
        public Endpoint? Endpoint { get; init; }

        /// <summary>The <c>secret</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("secret")]
        public string Secret { get; init; } = "";
    }

    /// <summary><c>iohr.events.v1.CreateInboxRequest</c></summary>
    public sealed record CreateInboxRequest
    {
        /// <summary>The <c>account_id</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("account_id")]
        public string AccountId { get; init; } = "";
    }

    /// <summary><c>iohr.events.v1.CreateInboxResponse</c></summary>
    public sealed record CreateInboxResponse
    {
        /// <summary>The <c>inbox</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("inbox")]
        public Inbox? Inbox { get; init; }
    }

    /// <summary><c>iohr.events.v1.DeleteEndpointResponse</c></summary>
    public sealed record DeleteEndpointResponse;

    /// <summary><c>iohr.events.v1.DeleteInboxResponse</c></summary>
    public sealed record DeleteInboxResponse;

    /// <summary><c>iohr.events.v1.Delivery</c></summary>
    public sealed record Delivery
    {
        /// <summary>The <c>attempts</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("attempts")]
        public int Attempts { get; init; }

        /// <summary>The <c>created_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = "";

        /// <summary>The <c>endpoint_id</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("endpoint_id")]
        public string EndpointId { get; init; } = "";

        /// <summary>The <c>event_id</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("event_id")]
        public string EventId { get; init; } = "";

        /// <summary>The <c>event_type</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("event_type")]
        public string EventType { get; init; } = "";

        /// <summary>The <c>id</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; init; } = "";

        /// <summary>The <c>last_error</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("last_error")]
        public string LastError { get; init; } = "";

        /// <summary>The <c>last_latency_ms</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("last_latency_ms")]
        public int LastLatencyMs { get; init; }

        /// <summary>The <c>last_status_code</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("last_status_code")]
        public int LastStatusCode { get; init; }

        /// <summary>The <c>next_attempt_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("next_attempt_at")]
        public string NextAttemptAt { get; init; } = "";

        /// <summary>The <c>status</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("status")]
        public string Status { get; init; } = "";

        /// <summary>The <c>updated_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public string UpdatedAt { get; init; } = "";
    }

    /// <summary><c>iohr.events.v1.Endpoint</c></summary>
    public sealed record Endpoint
    {
        /// <summary>The <c>created_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = "";

        /// <summary>The <c>description</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; init; } = "";

        /// <summary>The <c>disabled_reason</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("disabled_reason")]
        public string DisabledReason { get; init; } = "";

        /// <summary>The <c>enabled</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("enabled")]
        public bool Enabled { get; init; }

        /// <summary>The <c>event_types</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("event_types")]
        public global::System.Collections.Generic.IReadOnlyList<string> EventTypes { get; init; } = [];

        /// <summary>The <c>failed_24h</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("failed_24h")]
        public int Failed24h { get; init; }

        /// <summary>The <c>id</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; init; } = "";

        /// <summary>The <c>last_delivery_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("last_delivery_at")]
        public string LastDeliveryAt { get; init; } = "";

        /// <summary>The <c>last_delivery_status</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("last_delivery_status")]
        public string LastDeliveryStatus { get; init; } = "";

        /// <summary>The <c>secret_rotated_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("secret_rotated_at")]
        public string SecretRotatedAt { get; init; } = "";

        /// <summary>The <c>succeeded_24h</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("succeeded_24h")]
        public int Succeeded24h { get; init; }

        /// <summary>The <c>url</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; init; } = "";
    }

    /// <summary><c>iohr.events.v1.Inbox</c></summary>
    public sealed record Inbox
    {
        /// <summary>The <c>created_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public string CreatedAt { get; init; } = "";

        /// <summary>The <c>expires_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("expires_at")]
        public string ExpiresAt { get; init; } = "";

        /// <summary>The <c>id</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; init; } = "";

        /// <summary>The <c>url</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; init; } = "";
    }

    /// <summary><c>{"code","error","details"}</c>: the REST body and the SSE <c>error</c> payload.</summary>
    public sealed record Problem
    {
        /// <summary>The slug.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("code")]
        public global::InOrbit.Sdk.Code Code { get; init; }

        /// <summary>Typed details.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("details")]
        public global::System.Collections.Generic.IReadOnlyList<global::InOrbit.Sdk.Detail> Details { get; init; } = [];

        /// <summary>The sentence.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("error")]
        public string Error { get; init; } = "";
    }

    /// <summary><c>iohr.events.v1.RetryDeliveryResponse</c></summary>
    public sealed record RetryDeliveryResponse
    {
        /// <summary>The <c>delivery</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("delivery")]
        public Delivery? Delivery { get; init; }
    }

    /// <summary><c>iohr.events.v1.RotateSecretResponse</c></summary>
    public sealed record RotateSecretResponse
    {
        /// <summary>The <c>previous_expires_at</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("previous_expires_at")]
        public string PreviousExpiresAt { get; init; } = "";

        /// <summary>The <c>secret</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("secret")]
        public string Secret { get; init; } = "";
    }

    /// <summary><c>iohr.events.v1.SendTestResponse</c></summary>
    public sealed record SendTestResponse
    {
        /// <summary>The <c>delivery</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("delivery")]
        public Delivery? Delivery { get; init; }
    }

    /// <summary><c>iohr.events.v1.UpdateEndpointRequest</c></summary>
    public sealed record UpdateEndpointRequest
    {
        /// <summary>The <c>description</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; init; } = "";

        /// <summary>The <c>enabled</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("enabled")]
        public bool Enabled { get; init; }

        /// <summary>The <c>endpoint_id</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("endpoint_id")]
        public string EndpointId { get; init; } = "";

        /// <summary>The <c>event_types</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("event_types")]
        public global::System.Collections.Generic.IReadOnlyList<string> EventTypes { get; init; } = [];

        /// <summary>The <c>url</c> field.</summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; init; } = "";
    }
}
