// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
// swiftlint:disable all

import Foundation
import InOrbit

/// `iohr.events.v1.CreateEndpointRequest`
public struct CreateEndpointRequest: Codable, Sendable {
    public var accountId: String?
    public var description: String?
    public var eventTypes: [String]?
    public var url: String?

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        accountId: String? = nil,
        description: String? = nil,
        eventTypes: [String]? = nil,
        url: String? = nil
    ) {
        self.accountId = accountId
        self.description = description
        self.eventTypes = eventTypes
        self.url = url
    }

    enum CodingKeys: String, CodingKey {
        case accountId = "account_id"
        case description = "description"
        case eventTypes = "event_types"
        case url = "url"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.accountId = try c.decodeIfPresent(String.self, forKey: .accountId)
        self.description = try c.decodeIfPresent(String.self, forKey: .description)
        self.eventTypes = try c.decodeIfPresent([String].self, forKey: .eventTypes)
        self.url = try c.decodeIfPresent(String.self, forKey: .url)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encodeIfPresent(self.accountId, forKey: .accountId)
        try c.encodeIfPresent(self.description, forKey: .description)
        try c.encodeIfPresent(self.eventTypes, forKey: .eventTypes)
        try c.encodeIfPresent(self.url, forKey: .url)
    }
}

/// `iohr.events.v1.CreateEndpointResponse`
public struct CreateEndpointResponse: Codable, Sendable {
    public var endpoint: Endpoint?
    public var secret: String

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        endpoint: Endpoint? = nil,
        secret: String
    ) {
        self.endpoint = endpoint
        self.secret = secret
    }

    enum CodingKeys: String, CodingKey {
        case endpoint = "endpoint"
        case secret = "secret"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.endpoint = try c.decodeIfPresent(Endpoint.self, forKey: .endpoint)
        self.secret = try c.decode(String.self, forKey: .secret)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encodeIfPresent(self.endpoint, forKey: .endpoint)
        try c.encode(self.secret, forKey: .secret)
    }
}

/// `iohr.events.v1.CreateInboxRequest`
public struct CreateInboxRequest: Codable, Sendable {
    public var accountId: String?

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        accountId: String? = nil
    ) {
        self.accountId = accountId
    }

    enum CodingKeys: String, CodingKey {
        case accountId = "account_id"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.accountId = try c.decodeIfPresent(String.self, forKey: .accountId)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encodeIfPresent(self.accountId, forKey: .accountId)
    }
}

/// `iohr.events.v1.CreateInboxResponse`
public struct CreateInboxResponse: Codable, Sendable {
    public var inbox: Inbox?

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        inbox: Inbox? = nil
    ) {
        self.inbox = inbox
    }

    enum CodingKeys: String, CodingKey {
        case inbox = "inbox"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.inbox = try c.decodeIfPresent(Inbox.self, forKey: .inbox)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encodeIfPresent(self.inbox, forKey: .inbox)
    }
}

/// `iohr.events.v1.DeleteEndpointResponse`
public struct DeleteEndpointResponse: Codable, Sendable {
    /// An empty value.
    public init() {}
}

/// `iohr.events.v1.DeleteInboxResponse`
public struct DeleteInboxResponse: Codable, Sendable {
    /// An empty value.
    public init() {}
}

/// `iohr.events.v1.Delivery`
public struct Delivery: Codable, Sendable {
    public var attempts: Int32
    public var createdAt: String
    public var endpointId: String
    public var eventId: String
    public var eventType: String
    public var id: String
    public var lastError: String
    public var lastLatencyMs: Int32
    public var lastStatusCode: Int32
    public var nextAttemptAt: String
    public var status: String
    public var updatedAt: String

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        attempts: Int32,
        createdAt: String,
        endpointId: String,
        eventId: String,
        eventType: String,
        id: String,
        lastError: String,
        lastLatencyMs: Int32,
        lastStatusCode: Int32,
        nextAttemptAt: String,
        status: String,
        updatedAt: String
    ) {
        self.attempts = attempts
        self.createdAt = createdAt
        self.endpointId = endpointId
        self.eventId = eventId
        self.eventType = eventType
        self.id = id
        self.lastError = lastError
        self.lastLatencyMs = lastLatencyMs
        self.lastStatusCode = lastStatusCode
        self.nextAttemptAt = nextAttemptAt
        self.status = status
        self.updatedAt = updatedAt
    }

    enum CodingKeys: String, CodingKey {
        case attempts = "attempts"
        case createdAt = "created_at"
        case endpointId = "endpoint_id"
        case eventId = "event_id"
        case eventType = "event_type"
        case id = "id"
        case lastError = "last_error"
        case lastLatencyMs = "last_latency_ms"
        case lastStatusCode = "last_status_code"
        case nextAttemptAt = "next_attempt_at"
        case status = "status"
        case updatedAt = "updated_at"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.attempts = try c.decode(Int32.self, forKey: .attempts)
        self.createdAt = try c.decode(String.self, forKey: .createdAt)
        self.endpointId = try c.decode(String.self, forKey: .endpointId)
        self.eventId = try c.decode(String.self, forKey: .eventId)
        self.eventType = try c.decode(String.self, forKey: .eventType)
        self.id = try c.decode(String.self, forKey: .id)
        self.lastError = try c.decode(String.self, forKey: .lastError)
        self.lastLatencyMs = try c.decode(Int32.self, forKey: .lastLatencyMs)
        self.lastStatusCode = try c.decode(Int32.self, forKey: .lastStatusCode)
        self.nextAttemptAt = try c.decode(String.self, forKey: .nextAttemptAt)
        self.status = try c.decode(String.self, forKey: .status)
        self.updatedAt = try c.decode(String.self, forKey: .updatedAt)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(self.attempts, forKey: .attempts)
        try c.encode(self.createdAt, forKey: .createdAt)
        try c.encode(self.endpointId, forKey: .endpointId)
        try c.encode(self.eventId, forKey: .eventId)
        try c.encode(self.eventType, forKey: .eventType)
        try c.encode(self.id, forKey: .id)
        try c.encode(self.lastError, forKey: .lastError)
        try c.encode(self.lastLatencyMs, forKey: .lastLatencyMs)
        try c.encode(self.lastStatusCode, forKey: .lastStatusCode)
        try c.encode(self.nextAttemptAt, forKey: .nextAttemptAt)
        try c.encode(self.status, forKey: .status)
        try c.encode(self.updatedAt, forKey: .updatedAt)
    }
}

/// `iohr.events.v1.Endpoint`
public struct Endpoint: Codable, Sendable {
    public var createdAt: String
    public var description: String
    public var disabledReason: String
    public var enabled: Bool
    public var eventTypes: [String]
    public var failed24h: Int32
    public var id: String
    public var lastDeliveryAt: String
    public var lastDeliveryStatus: String
    public var secretRotatedAt: String
    public var succeeded24h: Int32
    public var url: String

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        createdAt: String,
        description: String,
        disabledReason: String,
        enabled: Bool,
        eventTypes: [String],
        failed24h: Int32,
        id: String,
        lastDeliveryAt: String,
        lastDeliveryStatus: String,
        secretRotatedAt: String,
        succeeded24h: Int32,
        url: String
    ) {
        self.createdAt = createdAt
        self.description = description
        self.disabledReason = disabledReason
        self.enabled = enabled
        self.eventTypes = eventTypes
        self.failed24h = failed24h
        self.id = id
        self.lastDeliveryAt = lastDeliveryAt
        self.lastDeliveryStatus = lastDeliveryStatus
        self.secretRotatedAt = secretRotatedAt
        self.succeeded24h = succeeded24h
        self.url = url
    }

    enum CodingKeys: String, CodingKey {
        case createdAt = "created_at"
        case description = "description"
        case disabledReason = "disabled_reason"
        case enabled = "enabled"
        case eventTypes = "event_types"
        case failed24h = "failed_24h"
        case id = "id"
        case lastDeliveryAt = "last_delivery_at"
        case lastDeliveryStatus = "last_delivery_status"
        case secretRotatedAt = "secret_rotated_at"
        case succeeded24h = "succeeded_24h"
        case url = "url"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.createdAt = try c.decode(String.self, forKey: .createdAt)
        self.description = try c.decode(String.self, forKey: .description)
        self.disabledReason = try c.decode(String.self, forKey: .disabledReason)
        self.enabled = try c.decode(Bool.self, forKey: .enabled)
        self.eventTypes = try c.decode([String].self, forKey: .eventTypes)
        self.failed24h = try c.decode(Int32.self, forKey: .failed24h)
        self.id = try c.decode(String.self, forKey: .id)
        self.lastDeliveryAt = try c.decode(String.self, forKey: .lastDeliveryAt)
        self.lastDeliveryStatus = try c.decode(String.self, forKey: .lastDeliveryStatus)
        self.secretRotatedAt = try c.decode(String.self, forKey: .secretRotatedAt)
        self.succeeded24h = try c.decode(Int32.self, forKey: .succeeded24h)
        self.url = try c.decode(String.self, forKey: .url)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(self.createdAt, forKey: .createdAt)
        try c.encode(self.description, forKey: .description)
        try c.encode(self.disabledReason, forKey: .disabledReason)
        try c.encode(self.enabled, forKey: .enabled)
        try c.encode(self.eventTypes, forKey: .eventTypes)
        try c.encode(self.failed24h, forKey: .failed24h)
        try c.encode(self.id, forKey: .id)
        try c.encode(self.lastDeliveryAt, forKey: .lastDeliveryAt)
        try c.encode(self.lastDeliveryStatus, forKey: .lastDeliveryStatus)
        try c.encode(self.secretRotatedAt, forKey: .secretRotatedAt)
        try c.encode(self.succeeded24h, forKey: .succeeded24h)
        try c.encode(self.url, forKey: .url)
    }
}

/// `iohr.events.v1.Inbox`
public struct Inbox: Codable, Sendable {
    public var createdAt: String
    public var expiresAt: String
    public var id: String
    public var url: String

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        createdAt: String,
        expiresAt: String,
        id: String,
        url: String
    ) {
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.id = id
        self.url = url
    }

    enum CodingKeys: String, CodingKey {
        case createdAt = "created_at"
        case expiresAt = "expires_at"
        case id = "id"
        case url = "url"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.createdAt = try c.decode(String.self, forKey: .createdAt)
        self.expiresAt = try c.decode(String.self, forKey: .expiresAt)
        self.id = try c.decode(String.self, forKey: .id)
        self.url = try c.decode(String.self, forKey: .url)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(self.createdAt, forKey: .createdAt)
        try c.encode(self.expiresAt, forKey: .expiresAt)
        try c.encode(self.id, forKey: .id)
        try c.encode(self.url, forKey: .url)
    }
}

/// `{"code","error","details","request_id"}`: the REST body and the SSE `error` payload.
public struct Problem: Codable, Sendable {
    /// The slug.
    public var code: InOrbit.Code
    /// Typed details.
    public var details: [InOrbit.Detail]
    /// The sentence.
    public var error: String
    /// The request's id, the `x-request-id` the answer carries: name it when asking about a call. Empty on a socket or MQTT frame, whose own id names the call.
    public var requestId: String

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        code: InOrbit.Code,
        details: [InOrbit.Detail],
        error: String,
        requestId: String
    ) {
        self.code = code
        self.details = details
        self.error = error
        self.requestId = requestId
    }

    enum CodingKeys: String, CodingKey {
        case code = "code"
        case details = "details"
        case error = "error"
        case requestId = "request_id"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.code = try c.decode(InOrbit.Code.self, forKey: .code)
        self.details = try c.decode([InOrbit.Detail].self, forKey: .details)
        self.error = try c.decode(String.self, forKey: .error)
        self.requestId = try c.decode(String.self, forKey: .requestId)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(self.code, forKey: .code)
        try c.encode(self.details, forKey: .details)
        try c.encode(self.error, forKey: .error)
        try c.encode(self.requestId, forKey: .requestId)
    }
}

/// `iohr.events.v1.RetryDeliveryResponse`
public struct RetryDeliveryResponse: Codable, Sendable {
    public var delivery: Delivery?

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        delivery: Delivery? = nil
    ) {
        self.delivery = delivery
    }

    enum CodingKeys: String, CodingKey {
        case delivery = "delivery"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.delivery = try c.decodeIfPresent(Delivery.self, forKey: .delivery)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encodeIfPresent(self.delivery, forKey: .delivery)
    }
}

/// `iohr.events.v1.RotateSecretResponse`
public struct RotateSecretResponse: Codable, Sendable {
    public var previousExpiresAt: String
    public var secret: String

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        previousExpiresAt: String,
        secret: String
    ) {
        self.previousExpiresAt = previousExpiresAt
        self.secret = secret
    }

    enum CodingKeys: String, CodingKey {
        case previousExpiresAt = "previous_expires_at"
        case secret = "secret"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.previousExpiresAt = try c.decode(String.self, forKey: .previousExpiresAt)
        self.secret = try c.decode(String.self, forKey: .secret)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(self.previousExpiresAt, forKey: .previousExpiresAt)
        try c.encode(self.secret, forKey: .secret)
    }
}

/// `iohr.events.v1.SendTestResponse`
public struct SendTestResponse: Codable, Sendable {
    public var delivery: Delivery?

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        delivery: Delivery? = nil
    ) {
        self.delivery = delivery
    }

    enum CodingKeys: String, CodingKey {
        case delivery = "delivery"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.delivery = try c.decodeIfPresent(Delivery.self, forKey: .delivery)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encodeIfPresent(self.delivery, forKey: .delivery)
    }
}

/// `iohr.events.v1.UpdateEndpointRequest`
public struct UpdateEndpointRequest: Codable, Sendable {
    public var description: String?
    public var enabled: Bool?
    public var endpointId: String?
    public var eventTypes: [String]?
    public var url: String?

    /// A value with every field given; what is left `nil` is left out of a request.
    public init(
        description: String? = nil,
        enabled: Bool? = nil,
        endpointId: String? = nil,
        eventTypes: [String]? = nil,
        url: String? = nil
    ) {
        self.description = description
        self.enabled = enabled
        self.endpointId = endpointId
        self.eventTypes = eventTypes
        self.url = url
    }

    enum CodingKeys: String, CodingKey {
        case description = "description"
        case enabled = "enabled"
        case endpointId = "endpoint_id"
        case eventTypes = "event_types"
        case url = "url"
    }

    public init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.description = try c.decodeIfPresent(String.self, forKey: .description)
        self.enabled = try c.decodeIfPresent(Bool.self, forKey: .enabled)
        self.endpointId = try c.decodeIfPresent(String.self, forKey: .endpointId)
        self.eventTypes = try c.decodeIfPresent([String].self, forKey: .eventTypes)
        self.url = try c.decodeIfPresent(String.self, forKey: .url)
    }

    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encodeIfPresent(self.description, forKey: .description)
        try c.encodeIfPresent(self.enabled, forKey: .enabled)
        try c.encodeIfPresent(self.endpointId, forKey: .endpointId)
        try c.encodeIfPresent(self.eventTypes, forKey: .eventTypes)
        try c.encodeIfPresent(self.url, forKey: .url)
    }
}
