//! The C# target: models as records, one marker interface per operation, and one class
//! per profile implementing the markers its cut holds. Operations are extension methods
//! on the runtime's `Client<TProfile>` (flat ones) or on a handle per tag, each
//! constrained to its marker (`where TProfile : IListDigests`), so a call the profile may
//! not make does not compile, as in Rust.
//!
//! Every file is marked `<auto-generated>` (analyzers and `dotnet format` leave it alone)
//! and turns nullable annotations on. 64-bit integers are `long`, read from and written
//! as decimal strings through `JsonNumberHandling`; string enums keep a value this
//! version does not know.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use heck::{ToLowerCamelCase as _, ToUpperCamelCase as _};
use iohr_openapi::{Api, Method};

use crate::context::{self, Naming, Op, Segment, Surface};
use crate::files::Files;
use crate::ir::{self, Field, Model, Shape, Type};
use crate::language::{Language, Options};
use crate::target::{RenderError, Target};

/// The C# target.
#[derive(Debug, Clone, Copy, Default)]
pub struct CSharpTarget;

/// The namespace the runtime's own public surface is generated into.
const IN_PACKAGE_NAMESPACE: &str = "InOrbit.Sdk.Api";
/// The namespace of a developer's surface when `--package` does not name one.
const DEFAULT_NAMESPACE: &str = "InOrbit.Generated";
/// The runtime's profile for the public cut, which the runtime's own surface extends.
const PUBLIC_PROFILE: &str = "PublicProfile";

/// How C# spells names: `PascalCase` types, members and methods, `camelCase`
/// parameters, a reserved word escaped with `@`.
struct CsNaming;

impl Naming for CsNaming {
    const RESERVED: &'static [&'static str] = &[
        "abstract",
        "as",
        "base",
        "bool",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "checked",
        "class",
        "const",
        "continue",
        "decimal",
        "default",
        "delegate",
        "do",
        "double",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "false",
        "finally",
        "fixed",
        "float",
        "for",
        "foreach",
        "goto",
        "if",
        "implicit",
        "in",
        "int",
        "interface",
        "internal",
        "is",
        "lock",
        "long",
        "namespace",
        "new",
        "null",
        "object",
        "operator",
        "out",
        "override",
        "params",
        "private",
        "protected",
        "public",
        "readonly",
        "ref",
        "return",
        "sbyte",
        "sealed",
        "short",
        "sizeof",
        "stackalloc",
        "static",
        "string",
        "struct",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "uint",
        "ulong",
        "unchecked",
        "unsafe",
        "ushort",
        "using",
        "virtual",
        "void",
        "volatile",
        "while",
    ];

    fn escape(&self, ident: String) -> String {
        if Self::RESERVED.contains(&ident.as_str()) {
            format!("@{ident}")
        } else {
            ident
        }
    }

    fn method_name(&self, snake: &str) -> String {
        snake.to_upper_camel_case()
    }

    /// A parameter's name; a model's property is [`property`].
    fn field_name(&self, wire: &str) -> String {
        self.escape(wire.to_lower_camel_case())
    }
}

/// A property's name: `PascalCase`, never the name of the type that holds it.
fn property(wire: &str, holder: &str) -> String {
    let mut name = wire.to_upper_camel_case();
    if name.is_empty() || name.starts_with(|c: char| c.is_ascii_digit()) {
        name.insert(0, 'V');
    }
    if name == holder {
        name.push_str("Value");
    }
    name
}

impl Target for CSharpTarget {
    const LANG: Language = Language::CSharp;

    fn render(&self, api: &Api, options: &Options) -> Result<Files, RenderError> {
        let ctx = Ctx {
            runtime: format!("global::{}", options.runtime_for(Self::LANG)),
            namespace: options.package.clone().unwrap_or_else(|| {
                if options.in_package {
                    IN_PACKAGE_NAMESPACE.to_owned()
                } else {
                    DEFAULT_NAMESPACE.to_owned()
                }
            }),
            in_package: options.in_package,
        };
        let surface = context::surface(api);
        let models = context::models(api);
        let mut files = Files::new();
        for note in &surface.notes {
            files.note(note.clone());
        }
        let header = header(&surface.header);
        files.insert(
            "Models.cs",
            format!("{header}{}", render_models(&models, &ctx)),
        );
        files.insert(
            "Profiles.cs",
            format!("{header}{}", render_profiles(&surface, &ctx)),
        );
        files.insert(
            "Operations.cs",
            format!("{header}{}", render_operations(&surface, &ctx)),
        );
        Ok(files)
    }
}

/// What every file needs to know.
struct Ctx {
    /// `global::InOrbit.Sdk`.
    runtime: String,
    /// The surface's namespace.
    namespace: String,
    /// Whether this is the runtime's own public surface.
    in_package: bool,
}

fn header(line: &str) -> String {
    format!("// <auto-generated>\n// {line}\n// </auto-generated>\n\n#nullable enable\n")
}

/// Text for an XML doc comment: escaped, on one line, `code` spans as `<c>code</c>`.
fn xml(text: &str) -> String {
    let escaped = text
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('\n', " ");
    let mut out = String::with_capacity(escaped.len());
    let mut parts = escaped.split('`');
    if let Some(first) = parts.next() {
        out.push_str(first);
    }
    let rest: Vec<&str> = parts.collect();
    // An unpaired backtick stays as it is.
    let pairs = rest.len() / 2 * 2;
    for (i, part) in rest.iter().enumerate() {
        if i >= pairs {
            out.push('`');
            out.push_str(part);
        } else if i % 2 == 0 {
            let _ = write!(out, "<c>{part}</c>");
        } else {
            out.push_str(part);
        }
    }
    out
}

/// A `<summary>` line; `markup` is already XML.
fn summary(markup: &str, indent: &str) -> String {
    format!("{indent}/// <summary>{markup}</summary>\n")
}

/// The C# type of `ty`, and whether it is a value type.
fn cs_type(ty: &Type, ctx: &Ctx, models: &[Model]) -> (String, bool) {
    match ty {
        Type::Ref { name } if ir::RUNTIME_TYPES.contains(&name.as_str()) => {
            let value_type = name == "Code";
            (format!("{}.{name}", ctx.runtime), value_type)
        }
        Type::Ref { name } => {
            let value_type = models.iter().any(|m| {
                &m.name == name
                    && matches!(
                        m.shape,
                        Shape::Enum { .. } | Shape::Union { .. } | Shape::Alias { .. }
                    )
            });
            (name.clone(), value_type)
        }
        Type::String | Type::Enum { .. } => ("string".into(), false),
        Type::Integer { bits: 32 } => ("int".into(), true),
        Type::Int64 | Type::Integer { .. } => ("long".into(), true),
        Type::Number => ("double".into(), true),
        Type::Bool => ("bool".into(), true),
        Type::Array { item } => (
            format!(
                "global::System.Collections.Generic.IReadOnlyList<{}>",
                cs_type(item, ctx, models).0
            ),
            false,
        ),
        Type::Map { value } => (
            format!(
                "global::System.Collections.Generic.IReadOnlyDictionary<string, {}>",
                cs_type(value, ctx, models).0
            ),
            false,
        ),
        _ => ("global::System.Text.Json.JsonElement".into(), true),
    }
}

/// Whether a value of `ty` holds a decimal-string 64-bit integer.
fn holds_int64(ty: &Type) -> bool {
    match ty {
        Type::Int64 => true,
        Type::Array { item } => holds_int64(item),
        Type::Map { value } => holds_int64(value),
        _ => false,
    }
}

/// A property's declaration: its type, nullable unless the answer always carries a
/// value type, and an initializer that keeps a non-nullable reference non-null.
fn declaration(f: &Field, ctx: &Ctx, models: &[Model]) -> (String, String) {
    let (ty, value_type) = cs_type(&f.ty, ctx, models);
    let reference_ok = matches!(
        f.ty,
        Type::String | Type::Enum { .. } | Type::Array { .. } | Type::Map { .. }
    );
    if f.required && !f.nullable && (value_type || reference_ok) {
        let init = match &f.ty {
            Type::String | Type::Enum { .. } => " = \"\";".to_owned(),
            Type::Array { .. } => " = [];".to_owned(),
            Type::Map { value } => format!(
                " = new global::System.Collections.Generic.Dictionary<string, {}>();",
                cs_type(value, ctx, models).0
            ),
            _ => String::new(),
        };
        (ty, init)
    } else {
        (format!("{ty}?"), String::new())
    }
}

fn render_models(models: &[Model], ctx: &Ctx) -> String {
    let mut out = format!("\nnamespace {}\n{{\n", ctx.namespace);
    let mut first = true;
    for m in models.iter().filter(|m| !m.runtime) {
        if !first {
            out.push('\n');
        }
        first = false;
        let doc = if m.doc.is_empty() {
            format!("The <c>{}</c> model.", m.name)
        } else {
            xml(&m.doc)
        };
        out.push_str(&summary(&doc, "    "));
        match &m.shape {
            Shape::Object { fields } if fields.is_empty() => {
                let _ = writeln!(out, "    public sealed record {};", m.name);
            }
            Shape::Object { fields } => {
                let _ = writeln!(out, "    public sealed record {}\n    {{", m.name);
                for (i, f) in fields.iter().enumerate() {
                    if i > 0 {
                        out.push('\n');
                    }
                    let doc = if f.doc.is_empty() {
                        format!("The <c>{}</c> field.", f.name)
                    } else {
                        xml(&f.doc)
                    };
                    out.push_str(&summary(&doc, "        "));
                    let _ = writeln!(
                        out,
                        "        [global::System.Text.Json.Serialization.JsonPropertyName(\"{}\")]",
                        f.name
                    );
                    if holds_int64(&f.ty) {
                        out.push_str("        [global::System.Text.Json.Serialization.JsonNumberHandling(global::System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString | global::System.Text.Json.Serialization.JsonNumberHandling.WriteAsString)]\n");
                    }
                    let (ty, init) = declaration(f, ctx, models);
                    let _ = writeln!(
                        out,
                        "        public {ty} {} {{ get; init; }}{init}",
                        property(&f.name, &m.name)
                    );
                }
                out.push_str("    }\n");
            }
            Shape::Enum { values } => out.push_str(&string_value(&m.name, values, ctx)),
            Shape::Union { .. } | Shape::Alias { .. } => out.push_str(&raw_json(&m.name, ctx)),
        }
    }
    out.push_str("}\n");
    out
}

/// A string enum that keeps a value this version does not know.
fn string_value(name: &str, values: &[String], ctx: &Ctx) -> String {
    let rt = &ctx.runtime;
    let mut out = format!(
        "    [global::System.Text.Json.Serialization.JsonConverter(typeof({rt}.StringValueConverter<{name}>))]\n    public readonly record struct {name}(string Value) : {rt}.IStringValue<{name}>\n    {{\n"
    );
    let mut seen = BTreeSet::new();
    for v in values {
        let mut member = property(v, name);
        while !seen.insert(member.clone()) {
            member.push('_');
        }
        let _ = writeln!(
            out,
            "        /// <summary><c>{}</c>.</summary>\n        public static {name} {member} {{ get; }} = new(\"{v}\");\n",
            xml(v)
        );
    }
    let _ = write!(
        out,
        "        static {name} {rt}.IStringValue<{name}>.From(string value) => new(value);\n\n        /// <inheritdoc/>\n        public override string ToString() => Value;\n    }}\n"
    );
    out
}

/// A union or an alias, kept as the JSON it holds.
fn raw_json(name: &str, ctx: &Ctx) -> String {
    let rt = &ctx.runtime;
    format!(
        "    [global::System.Text.Json.Serialization.JsonConverter(typeof({rt}.RawJsonConverter<{name}>))]\n    public readonly record struct {name}(global::System.Text.Json.JsonElement Value) : {rt}.IRawJson<{name}>\n    {{\n        static {name} {rt}.IRawJson<{name}>.From(global::System.Text.Json.JsonElement value) => new(value);\n    }}\n"
    )
}

/// The interface a profile implements when its cut holds any operation of `tag`.
fn area(tag: &str) -> String {
    format!("I{}Area", tag.to_upper_camel_case())
}

/// The marker of an operation.
fn marker(op_marker: &str) -> String {
    format!("I{op_marker}")
}

/// A profile's type name in this surface.
fn profile_type(p: &context::Profile, ctx: &Ctx) -> String {
    if ctx.in_package && p.is_public {
        PUBLIC_PROFILE.to_owned()
    } else {
        CsNaming.type_name(&p.name)
    }
}

fn render_profiles(surface: &Surface, ctx: &Ctx) -> String {
    let rt = &ctx.runtime;
    let mut blocks: Vec<String> = Vec::new();
    for m in &surface.markers {
        blocks.push(format!(
            "    /// <summary>A profile whose cut holds <c>{}</c>.</summary>\n    public interface {} : {rt}.IProfile\n    {{\n    }}",
            m.line,
            marker(&m.name)
        ));
    }
    for h in &surface.handles {
        blocks.push(format!(
            "    /// <summary>A profile whose cut holds an operation of <c>{}</c>.</summary>\n    public interface {} : {rt}.IProfile\n    {{\n    }}",
            h.tag,
            area(&h.tag)
        ));
    }
    if !ctx.in_package {
        for p in &surface.profiles {
            let ty = profile_type(p, ctx);
            let env_doc = if p.is_public {
                "<c>Client.FromEnv</c> reads <c>INORBIT_TOKEN</c>, or <c>INORBIT_KEY_ID</c>, <c>INORBIT_KEY_SECRET</c> and <c>INORBIT_SCOPES</c>".to_owned()
            } else {
                format!(
                    "<c>Client.FromEnv</c> reads <c>INORBIT_{e}_TOKEN</c>, or <c>INORBIT_{e}_KEY_ID</c>, <c>INORBIT_{e}_KEY_SECRET</c> and <c>INORBIT_{e}_SCOPES</c>, and nothing else",
                    e = p.env
                )
            };
            blocks.push(format!(
                "    /// <summary>Profile <c>{}</c>: the operations its cut holds. {env_doc}.</summary>\n    public sealed class {ty}{}\n    {{\n        private {ty}()\n        {{\n        }}\n\n        /// <inheritdoc/>\n        public static string Name => \"{}\";\n\n        /// <inheritdoc/>\n        public static string Env => \"{}\";\n    }}",
                p.name,
                bases(&implemented(surface, p, ctx)),
                p.name,
                if p.is_public { "" } else { p.env.as_str() }
            ));
        }
    }
    let mut out = format!(
        "\nnamespace {}\n{{\n{}\n",
        ctx.namespace,
        blocks.join("\n\n")
    );
    out.push_str("}\n");
    if ctx.in_package {
        // The runtime declares the public profile; its markers are this surface's.
        for p in surface.profiles.iter().filter(|p| p.is_public) {
            let qualified: Vec<String> = implemented(surface, p, ctx)
                .into_iter()
                .skip(1)
                .map(|i| format!("global::{}.{i}", ctx.namespace))
                .collect();
            if qualified.is_empty() {
                continue;
            }
            let _ = write!(
                out,
                "\nnamespace {rt_ns}\n{{\n    public sealed partial class {PUBLIC_PROFILE}{}\n    {{\n    }}\n}}\n",
                bases(&qualified),
                rt_ns = rt.trim_start_matches("global::")
            );
        }
    }
    out
}

/// The interfaces profile `p` implements: the runtime's profile, the markers and the areas
/// its cut holds, one per line.
fn implemented(surface: &Surface, p: &context::Profile, ctx: &Ctx) -> Vec<String> {
    let mut list = vec![format!("{}.IProfile", ctx.runtime)];
    list.extend(
        surface
            .markers
            .iter()
            .filter(|m| m.profiles.contains(&p.name))
            .map(|m| marker(&m.name)),
    );
    list.extend(
        surface
            .handles
            .iter()
            .filter(|h| h.ops.iter().any(|o| o.profiles.contains(&p.name)))
            .map(|h| area(&h.tag)),
    );
    list
}

/// A base list, one interface per line under the declaration.
fn bases(list: &[String]) -> String {
    format!("\n        : {}", list.join(",\n          "))
}

fn method(m: Method) -> &'static str {
    match m {
        Method::Get => "Get",
        Method::Post => "Post",
        Method::Put => "Put",
        Method::Patch => "Patch",
        Method::Delete => "Delete",
        Method::Head => "Head",
    }
}

fn scopes_note(op: &Op) -> String {
    if op.scopes.is_empty() {
        return String::new();
    }
    let list: Vec<String> = op.scopes.iter().map(|s| format!("<c>{s}</c>")).collect();
    format!(
        "; needs scope{} {}",
        if op.scopes.len() > 1 { "s" } else { "" },
        list.join(", ")
    )
}

fn render_operations(surface: &Surface, ctx: &Ctx) -> String {
    let rt = &ctx.runtime;
    let mut out = format!(
        "\nnamespace {ns}\n{{\n    /// <summary>A surface generated for another runtime version fails to compile here: run <c>iohr sdk generate</c> again.</summary>\n    internal static class SurfaceVersion\n    {{\n        /// <summary>The runtime contract this surface was generated for; dividing by zero stops the build when it differs.</summary>\n        internal const int Value = 1 / ({rt}.Codegen.Version == 1 ? 1 : 0);\n    }}\n",
        ns = ctx.namespace
    );
    // Query parameter records.
    for op in all_ops(surface) {
        if let Some(t) = &op.params_type {
            out.push_str(&params_record(t, op, ctx));
        }
    }
    // The client's own extensions: the flat operations and a handle per tag.
    out.push_str(
        "\n    /// <summary>The operations of this surface on a client, and its handle per area.</summary>\n    public static class Surface\n    {\n",
    );
    let mut first = true;
    for h in &surface.handles {
        if !first {
            out.push('\n');
        }
        first = false;
        let handle = handle_type(&h.tag);
        let _ = writeln!(
            out,
            "        /// <summary>The <c>{tag}</c> operations of the profile's cut.</summary>\n        /// <typeparam name=\"TProfile\">The client's profile.</typeparam>\n        /// <param name=\"client\">The client.</param>\n        /// <returns>The handle.</returns>\n        public static {handle}<TProfile> {name}<TProfile>(this {rt}.Client<TProfile> client)\n            where TProfile : {area} => new(client);",
            tag = h.tag,
            name = CsNaming.method_name(&h.tag),
            area = area(&h.tag)
        );
    }
    for op in &surface.flat {
        if !first {
            out.push('\n');
        }
        first = false;
        out.push_str(&operation(
            op,
            "client",
            &format!("{rt}.Client<TProfile>"),
            "client",
            ctx,
        ));
    }
    out.push_str("    }\n");
    for h in &surface.handles {
        let handle = handle_type(&h.tag);
        let _ = write!(
            out,
            "\n    /// <summary>The <c>{tag}</c> operations, on a profile's client.</summary>\n    /// <typeparam name=\"TProfile\">The client's profile.</typeparam>\n    public readonly struct {handle}<TProfile>\n        where TProfile : {rt}.IProfile\n    {{\n        internal {handle}({rt}.Client<TProfile> client)\n        {{\n            Client = client;\n        }}\n\n        internal {rt}.Client<TProfile> Client {{ get; }}\n    }}\n\n    /// <summary>The <c>{tag}</c> operations, each for the profiles whose cut holds it.</summary>\n    public static class {name}Operations\n    {{\n",
            tag = h.tag,
            name = h.tag.to_upper_camel_case()
        );
        for (i, op) in h.ops.iter().enumerate() {
            if i > 0 {
                out.push('\n');
            }
            let receiver = CsNaming.field_name(&h.tag);
            out.push_str(&operation(
                op,
                &receiver,
                &format!("{handle}<TProfile>"),
                &format!("{receiver}.Client"),
                ctx,
            ));
        }
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    out
}

fn all_ops(surface: &Surface) -> Vec<&Op> {
    let mut ops: Vec<&Op> = surface
        .handles
        .iter()
        .flat_map(|h| h.ops.iter())
        .chain(surface.flat.iter())
        .collect();
    ops.sort_by(|a, b| a.line.cmp(&b.line));
    ops
}

fn handle_type(tag: &str) -> String {
    format!("{}Handle", tag.to_upper_camel_case())
}

fn params_record(type_name: &str, op: &Op, ctx: &Ctx) -> String {
    let mut out = format!(
        "\n    /// <summary>The query parameters of <c>{}</c>.</summary>\n    public sealed record {type_name}\n    {{\n",
        op.line
    );
    for (i, q) in op.query.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        let doc = if q.doc.is_empty() {
            format!("<c>{}</c>.", q.name)
        } else {
            xml(&q.doc)
        };
        let (ty, _) = cs_type(&q.ty, ctx, &[]);
        let (required, ty) = if q.required {
            ("required ", ty)
        } else {
            ("", format!("{ty}?"))
        };
        let _ = writeln!(
            out,
            "        /// <summary>{doc}</summary>\n        public {required}{ty} {} {{ get; init; }}",
            property(&q.name, type_name)
        );
    }
    out.push_str("    }\n");
    out
}

/// An operation's parameters and their `<param>` lines: the receiver, the path
/// parameters, the query record, the body and the cancellation token.
fn parameters(op: &Op, receiver: &str, receiver_type: &str) -> (Vec<String>, Vec<String>) {
    let naming = CsNaming;
    let mut params = vec![format!("this {receiver_type} {receiver}")];
    let mut docs = vec![format!(
        "        /// <param name=\"{}\">The client, or its handle.</param>",
        receiver.trim_start_matches('@')
    )];
    for p in &op.path_params {
        let name = naming.field_name(&p.name);
        params.push(format!("string {name}"));
        let doc = if p.doc.is_empty() {
            format!("<c>{}</c>.", p.name)
        } else {
            xml(&p.doc)
        };
        docs.push(format!(
            "        /// <param name=\"{}\">{doc}</param>",
            name.trim_start_matches('@')
        ));
    }
    if let Some(t) = &op.params_type {
        if op.query.iter().any(|q| q.required) {
            params.push(format!("{t} query"));
        } else {
            params.push(format!("{t}? query = null"));
        }
        docs.push("        /// <param name=\"query\">The query parameters.</param>".into());
    }
    if let Some(body) = &op.body {
        params.push(format!("{body} body"));
        docs.push("        /// <param name=\"body\">The request body.</param>".into());
    }
    params.push("global::System.Threading.CancellationToken cancellationToken = default".into());
    docs.push(
        "        /// <param name=\"cancellationToken\">Cancels the call, retries included.</param>"
            .into(),
    );
    (params, docs)
}

/// One operation as an extension method over the runtime's request path.
fn operation(op: &Op, receiver: &str, receiver_type: &str, client: &str, ctx: &Ctx) -> String {
    let rt = &ctx.runtime;
    let naming = CsNaming;
    let response = op
        .response
        .clone()
        .unwrap_or_else(|| "global::System.Text.Json.JsonElement".into());
    let (params, docs) = parameters(op, receiver, receiver_type);
    let path: String = op
        .segments
        .iter()
        .map(|s| match s {
            Segment::Literal { text } => text.replace('{', "{{").replace('}', "}}"),
            Segment::Param { name } => {
                // Parenthesised: the `::` of `global::` would read as a format specifier.
                format!(
                    "{{({rt}.Codegen.PathSegment({}))}}",
                    naming.field_name(name)
                )
            }
        })
        .collect();
    let path = if op.path_params.is_empty() {
        format!("\"{path}\"")
    } else {
        format!("$\"{path}\"")
    };
    let scopes: Vec<String> = op.scopes.iter().map(|s| format!("\"{s}\"")).collect();
    // Static calls, not the extension form: the surface's files name everything in full and
    // import no namespace, so an extension method would not be found outside the runtime.
    let mut body = format!(
        "            var operation = {rt}.Codegen.Operation(\"{}\", {rt}.Method.{}, {path}, [{}]{});\n",
        op.hook_name,
        method(op.method),
        scopes.join(", "),
        if op.idempotent_override {
            ", idempotent: true"
        } else {
            ""
        }
    );
    if !op.query.is_empty() {
        let q: Vec<String> = op
            .query
            .iter()
            .map(|q| {
                let prop = property(&q.name, op.params_type.as_deref().unwrap_or_default());
                format!("(\"{}\", query?.{prop})", q.name)
            })
            .collect();
        let _ = writeln!(
            body,
            "            operation = {rt}.Codegen.WithQuery(operation, {});",
            q.join(", ")
        );
    }
    if op.body.is_some() {
        let _ = writeln!(
            body,
            "            operation = {rt}.Codegen.WithJson(operation, body);"
        );
    }
    let mut text = format!("<c>{}</c>{}.", op.line, scopes_note(op));
    if !op.doc.is_empty() {
        let _ = write!(text, " {}", xml(&op.doc));
    }
    format!(
        "        /// <summary>{text}</summary>\n        /// <typeparam name=\"TProfile\">The client's profile, whose cut holds the operation.</typeparam>\n{}\n        /// <returns>The answer, typed, and the raw one.</returns>\n        public static global::System.Threading.Tasks.Task<{rt}.Response<{response}>> {}Async<TProfile>({})\n            where TProfile : {}\n        {{\n{body}            return {client}.RequestAsync<{response}>(operation, cancellationToken);\n        }}\n",
        docs.join("\n"),
        naming.method_name(&op.name),
        params.join(", "),
        marker(&op.marker)
    )
}
