// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
// swiftlint:disable all

import Foundation
import InOrbit

/// Profile `acme-ci`: the operations its cut holds. `Client.fromEnv()` reads `INORBIT_ACME_CI_TOKEN`, or `INORBIT_ACME_CI_KEY_ID`, `INORBIT_ACME_CI_KEY_SECRET` and `INORBIT_ACME_CI_SCOPES`, and nothing else.
public enum AcmeCi:
    InOrbit.Profile,
    AllowsDeleteEndpoint,
    AllowsDeleteInbox,
    AllowsGetMe,
    AllowsGetUnits,
    AllowsGetUsage,
    AllowsListUnitCategories,
    AllowsStreamEvents,
    AllowsListEventTypes,
    AllowsMe,
    AllowsListDigests,
    AllowsGetDigest,
    AllowsListItems,
    AllowsListEndpoints,
    AllowsGetEndpoint,
    AllowsListDeliveries,
    AllowsListInboxes,
    AllowsListInboxRequests,
    AllowsUpdateEndpoint,
    AllowsRetryDelivery,
    AllowsCreateEndpoint,
    AllowsRotateSecret,
    AllowsSendTest,
    AllowsCreateInbox,
    AllowsAccountsArea,
    AllowsEventsArea,
    AllowsRadarArea
{
    public static let name = "acme-ci"
    public static let env = "ACME_CI"
}

/// Profile `personal`: the operations its cut holds. `Client.fromEnv()` reads `INORBIT_PERSONAL_TOKEN`, or `INORBIT_PERSONAL_KEY_ID`, `INORBIT_PERSONAL_KEY_SECRET` and `INORBIT_PERSONAL_SCOPES`, and nothing else.
public enum Personal:
    InOrbit.Profile,
    AllowsMe,
    AllowsListDigests,
    AllowsGetDigest,
    AllowsListItems,
    AllowsRadarArea
{
    public static let name = "personal"
    public static let env = "PERSONAL"
}
