// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
//! One marker trait per operation, implemented for the profiles whose cut holds it.
//! An operation's method is bounded by its marker, so calling it on a profile that
//! may not is a compile error, not a 403.
/// `DELETE /v1/webhooks/endpoints/{endpoint_id}`
pub trait DeleteEndpoint: inorbithr::Profile {}
impl DeleteEndpoint for super::profiles::AcmeCi {}
/// `DELETE /v1/webhooks/inboxes/{inbox_id}`
pub trait DeleteInbox: inorbithr::Profile {}
impl DeleteInbox for super::profiles::AcmeCi {}
/// `GET /v1/accounts/me`
pub trait GetMe: inorbithr::Profile {}
impl GetMe for super::profiles::AcmeCi {}
/// `GET /v1/accounts/orgs/{org_id}/units`
pub trait GetUnits: inorbithr::Profile {}
impl GetUnits for super::profiles::AcmeCi {}
/// `GET /v1/accounts/orgs/{org_id}/usage`
pub trait GetUsage: inorbithr::Profile {}
impl GetUsage for super::profiles::AcmeCi {}
/// `GET /v1/accounts/units/categories`
pub trait ListUnitCategories: inorbithr::Profile {}
impl ListUnitCategories for super::profiles::AcmeCi {}
/// `GET /v1/events/events`
pub trait StreamEvents: inorbithr::Profile {}
impl StreamEvents for super::profiles::AcmeCi {}
/// `GET /v1/events/types`
pub trait ListEventTypes: inorbithr::Profile {}
impl ListEventTypes for super::profiles::AcmeCi {}
/// `GET /v1/me`
pub trait Me: inorbithr::Profile {}
impl Me for super::profiles::AcmeCi {}
impl Me for super::profiles::Personal {}
/// `GET /v1/radar/digests`
pub trait ListDigests: inorbithr::Profile {}
impl ListDigests for super::profiles::AcmeCi {}
impl ListDigests for super::profiles::Personal {}
/// `GET /v1/radar/digests/{id}`
pub trait GetDigest: inorbithr::Profile {}
impl GetDigest for super::profiles::AcmeCi {}
impl GetDigest for super::profiles::Personal {}
/// `GET /v1/radar/items`
pub trait ListItems: inorbithr::Profile {}
impl ListItems for super::profiles::AcmeCi {}
impl ListItems for super::profiles::Personal {}
/// `GET /v1/webhooks/endpoints`
pub trait ListEndpoints: inorbithr::Profile {}
impl ListEndpoints for super::profiles::AcmeCi {}
/// `GET /v1/webhooks/endpoints/{endpoint_id}`
pub trait GetEndpoint: inorbithr::Profile {}
impl GetEndpoint for super::profiles::AcmeCi {}
/// `GET /v1/webhooks/endpoints/{endpoint_id}/deliveries`
pub trait ListDeliveries: inorbithr::Profile {}
impl ListDeliveries for super::profiles::AcmeCi {}
/// `GET /v1/webhooks/inboxes`
pub trait ListInboxes: inorbithr::Profile {}
impl ListInboxes for super::profiles::AcmeCi {}
/// `GET /v1/webhooks/inboxes/{inbox_id}/requests`
pub trait ListInboxRequests: inorbithr::Profile {}
impl ListInboxRequests for super::profiles::AcmeCi {}
/// `PATCH /v1/webhooks/endpoints/{endpoint_id}`
pub trait UpdateEndpoint: inorbithr::Profile {}
impl UpdateEndpoint for super::profiles::AcmeCi {}
/// `POST /v1/webhooks/deliveries/{delivery_id}/retry`
pub trait RetryDelivery: inorbithr::Profile {}
impl RetryDelivery for super::profiles::AcmeCi {}
/// `POST /v1/webhooks/endpoints`
pub trait CreateEndpoint: inorbithr::Profile {}
impl CreateEndpoint for super::profiles::AcmeCi {}
/// `POST /v1/webhooks/endpoints/{endpoint_id}/rotate`
pub trait RotateSecret: inorbithr::Profile {}
impl RotateSecret for super::profiles::AcmeCi {}
/// `POST /v1/webhooks/endpoints/{endpoint_id}/test`
pub trait SendTest: inorbithr::Profile {}
impl SendTest for super::profiles::AcmeCi {}
/// `POST /v1/webhooks/inboxes`
pub trait CreateInbox: inorbithr::Profile {}
impl CreateInbox for super::profiles::AcmeCi {}
