// Generated by iohr sdk generate for cuts acme-ci=sha256:abababababababababababababababababababababababababababababababab, personal=sha256:abababababababababababababababababababababababababababababababab; do not edit.
//! The profiles this surface was generated for: one zero-sized type each, the type
//! parameter of `Client`. A profile's client reads `INORBIT_<NAME>_*` and calls only
//! the operations its cut holds.
/// Profile `acme-ci`: `Client::<AcmeCi>::from_env()` reads `INORBIT_ACME_CI_TOKEN`, or
/// `INORBIT_ACME_CI_KEY_ID`, `INORBIT_ACME_CI_KEY_SECRET` and `INORBIT_ACME_CI_SCOPES`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct AcmeCi;
impl inorbithr::Profile for AcmeCi {
    const NAME: &'static str = "acme-ci";
}
/// Profile `personal`: `Client::<Personal>::from_env()` reads `INORBIT_PERSONAL_TOKEN`, or
/// `INORBIT_PERSONAL_KEY_ID`, `INORBIT_PERSONAL_KEY_SECRET` and `INORBIT_PERSONAL_SCOPES`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Personal;
impl inorbithr::Profile for Personal {
    const NAME: &'static str = "personal";
}
