// Generated by iohr sdk generate for cuts hooks=sha256:4dc13e4d8f09c98a436261733cb81a3ffa1fad694bc49df1d1305290ad629270; do not edit.
/**
 * The InOrbit API surface for `hooks` (API 0.1.0).
 *
 * Generated by `iohr sdk generate`: the models and the operations these profiles may
 * call, on the `@inorbithr/sdk` runtime. Regenerate it, never edit it; `iohr sdk check` says
 * when the API's cut has moved.
 *
 * @module
 */

import { codegen } from "@inorbithr/sdk";

/** A surface generated for another runtime version fails to compile here: run `iohr sdk generate` again. */
export const SURFACE_VERSION: 1 = codegen.VERSION;

export type * from "./models.js";
export type * from "./operations.js";
export * from "./profiles.js";
