// Generated by iohr sdk generate for cuts hooks=sha256:73edcea796e8c99f0a3d82db0cac9816cafa8ece7f5b1daa5294ecbaaa7880e1; do not edit.
import { type Code, type Detail, codegen } from "@inorbithr/sdk";

/** `iohr.events.v1.CreateEndpointRequest` */
export interface CreateEndpointRequest {
  account_id: string;
  description: string;
  event_types: string[];
  url: string;
}

/** `iohr.events.v1.CreateEndpointResponse` */
export interface CreateEndpointResponse {
  endpoint?: Endpoint;
  secret: string;
}

/** `iohr.events.v1.CreateInboxRequest` */
export interface CreateInboxRequest {
  account_id: string;
}

/** `iohr.events.v1.CreateInboxResponse` */
export interface CreateInboxResponse {
  inbox?: Inbox;
}

/** `iohr.events.v1.DeleteEndpointResponse` */
export type DeleteEndpointResponse = Record<string, never>;

/** `iohr.events.v1.DeleteInboxResponse` */
export type DeleteInboxResponse = Record<string, never>;

/** `iohr.events.v1.Delivery` */
export interface Delivery {
  attempts: number;
  created_at: string;
  endpoint_id: string;
  event_id: string;
  event_type: string;
  id: string;
  last_error: string;
  last_latency_ms: number;
  last_status_code: number;
  next_attempt_at: string;
  status: string;
  updated_at: string;
}

/** `iohr.events.v1.Endpoint` */
export interface Endpoint {
  created_at: string;
  description: string;
  disabled_reason: string;
  enabled: boolean;
  event_types: string[];
  failed_24h: number;
  id: string;
  last_delivery_at: string;
  last_delivery_status: string;
  secret_rotated_at: string;
  succeeded_24h: number;
  url: string;
}

/** `iohr.events.v1.Inbox` */
export interface Inbox {
  created_at: string;
  expires_at: string;
  id: string;
  url: string;
}

/** `{"code","error","details"}`: the REST body and the SSE `error` payload. */
export interface Problem {
  /** The slug. */
  code: Code;
  /** Typed details. */
  details: Detail[];
  /** The sentence. */
  error: string;
}

/** `iohr.events.v1.RetryDeliveryResponse` */
export interface RetryDeliveryResponse {
  delivery?: Delivery;
}

/** `iohr.events.v1.RotateSecretResponse` */
export interface RotateSecretResponse {
  previous_expires_at: string;
  secret: string;
}

/** `iohr.events.v1.SendTestResponse` */
export interface SendTestResponse {
  delivery?: Delivery;
}

/** `iohr.events.v1.UpdateEndpointRequest` */
export interface UpdateEndpointRequest {
  description: string;
  enabled: boolean;
  endpoint_id: string;
  event_types: string[];
  url: string;
}

/** Where each model holds a 64-bit integer, for the runtime to convert. */
export const shapes: codegen.Shapes = {
};
